import React, { useState } from 'react';
import { BookMarked, Plus, Trash2 } from 'lucide-react';

type Item={id:string;judul:string;keterangan:string};
const KEY='annajiyah_v2_buku_kerja_guru';
const load=():Item[]=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
export const BukuKerjaGuruView:React.FC=()=>{
 const [items,setItems]=useState<Item[]>(load); const [judul,setJudul]=useState(''); const [ket,setKet]=useState(''); const [show,setShow]=useState(false);
 const save=(e:React.FormEvent)=>{e.preventDefault();if(!judul.trim())return;const n=[...items,{id:`bkg-${Date.now()}`,judul:judul.trim(),keterangan:ket.trim()}];setItems(n);localStorage.setItem(KEY,JSON.stringify(n));setJudul('');setKet('');setShow(false)};
 const del=(id:string)=>{const n=items.filter(x=>x.id!==id);setItems(n);localStorage.setItem(KEY,JSON.stringify(n))};
 return <div className="space-y-5 pb-12"><div className="flex items-end justify-between gap-4"><div><h1 className="flex items-center gap-2 text-2xl font-black"><BookMarked className="h-6 w-6 text-emerald-700"/>Buku Kerja Guru</h1><p className="mt-1 text-xs text-slate-500">Tidak ada dokumen contoh/fiktif. Daftar ini hanya berisi dokumen yang ditambahkan pengguna.</p></div><button onClick={()=>setShow(true)} className="rounded-xl bg-emerald-800 px-4 py-2 text-xs font-bold text-white"><Plus className="mr-1 inline h-4 w-4"/>Tambah Dokumen</button></div>{items.length===0?<div className="rounded-2xl border border-dashed bg-white p-10 text-center text-sm text-slate-500">Belum ada dokumen Buku Kerja Guru.</div>:<div className="grid gap-3 md:grid-cols-2">{items.map(x=><div key={x.id} className="rounded-2xl border bg-white p-4"><div className="flex justify-between gap-3"><div><div className="font-black">{x.judul}</div>{x.keterangan&&<p className="mt-1 text-xs text-slate-500">{x.keterangan}</p>}</div><button onClick={()=>del(x.id)} className="text-rose-700"><Trash2 className="h-4 w-4"/></button></div></div>)}</div>}{show&&<div className="fixed inset-0 z-50 bg-slate-950/60 p-4"><div className="mx-auto mt-16 max-w-lg rounded-3xl bg-white p-6"><h3 className="font-black">Tambah Dokumen Buku Kerja Guru</h3><form onSubmit={save} className="mt-4 space-y-3"><label className="block text-xs font-bold">Judul<input value={judul} onChange={e=>setJudul(e.target.value)} className="mt-1 w-full rounded-xl border p-2.5 font-normal"/></label><label className="block text-xs font-bold">Keterangan<textarea value={ket} onChange={e=>setKet(e.target.value)} className="mt-1 w-full rounded-xl border p-2.5 font-normal"/></label><div className="flex justify-end gap-2"><button type="button" onClick={()=>setShow(false)} className="px-4 py-2 text-xs font-bold">Batal</button><button className="rounded-xl bg-emerald-800 px-4 py-2 text-xs font-bold text-white">Simpan</button></div></form></div></div>}</div>
};