import React, { useMemo, useState } from 'react';
import { Calendar, CalendarOff, Plus, Save, Trash2 } from 'lucide-react';

interface HariLiburViewProps { userRole?: string }
type Agenda = { id:string; judul:string; mulai:string; selesai:string; kategori:'KBM'|'Ujian'|'Libur'|'Pondok'|'Muhafadloh'; keterangan:string; kunciAbsensi:boolean };
type Libur = { id:string; mulai:string; selesai:string; keterangan:string };
const AGENDA_KEY='annajiyah_v2_kalender_production';
const LIBUR_KEY='annajiyah_v2_libur_production';
const read=<T,>(key:string, fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||'') as T}catch{return fallback}};
const format=(s:string)=>{if(!s)return '—';const d=new Date(`${s}T00:00:00`);return Number.isNaN(d.getTime())?s:d.toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'})};

export const HariLiburView: React.FC<HariLiburViewProps> = ({userRole='Admin'}) => {
 const isAdmin=userRole.toLowerCase()==='admin';
 const [tab,setTab]=useState<'agenda'|'libur'>('agenda');
 const [agenda,setAgenda]=useState<Agenda[]>(()=>read<Agenda[]>(AGENDA_KEY,[]));
 const [libur,setLibur]=useState<Libur[]>(()=>read<Libur[]>(LIBUR_KEY,[]));
 const [showAgenda,setShowAgenda]=useState(false); const [showLibur,setShowLibur]=useState(false);
 const [a,setA]=useState<Omit<Agenda,'id'>>({judul:'',mulai:'',selesai:'',kategori:'KBM',keterangan:'',kunciAbsensi:false});
 const [l,setL]=useState<Omit<Libur,'id'>>({mulai:'',selesai:'',keterangan:''});
 const saveAgenda=(e:React.FormEvent)=>{e.preventDefault(); if(!a.judul.trim()||!a.mulai)return; const item={...a,selesai:a.selesai||a.mulai,id:`agenda-${Date.now()}`}; const next=[...agenda,item]; setAgenda(next);localStorage.setItem(AGENDA_KEY,JSON.stringify(next)); if(item.kunciAbsensi){const li={id:`libur-${Date.now()}`,mulai:item.mulai,selesai:item.selesai,keterangan:item.judul};const nl=[...libur,li];setLibur(nl);localStorage.setItem(LIBUR_KEY,JSON.stringify(nl));} setA({judul:'',mulai:'',selesai:'',kategori:'KBM',keterangan:'',kunciAbsensi:false});setShowAgenda(false)};
 const saveLibur=(e:React.FormEvent)=>{e.preventDefault();if(!l.mulai||!l.keterangan.trim())return; const item={...l,selesai:l.selesai||l.mulai,id:`libur-${Date.now()}`};const next=[...libur,item];setLibur(next);localStorage.setItem(LIBUR_KEY,JSON.stringify(next));setL({mulai:'',selesai:'',keterangan:''});setShowLibur(false)};
 const sorted=useMemo(()=>[...agenda].sort((x,y)=>x.mulai.localeCompare(y.mulai)),[agenda]);
 return <div className="space-y-5 pb-12">
  <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-black"><Calendar className="h-6 w-6 text-emerald-700"/>Kalender Pendidikan & Hari Libur</h1><p className="mt-1 text-xs text-slate-500">Tidak ada agenda/libur yang dibuat otomatis. Admin mengisi berdasarkan keputusan resmi madrasah.</p></div>{isAdmin&&<div className="flex gap-2"><button onClick={()=>setShowAgenda(true)} className="rounded-xl bg-emerald-800 px-4 py-2 text-xs font-bold text-white"><Plus className="mr-1 inline h-4 w-4"/>Agenda</button><button onClick={()=>{setTab('libur');setShowLibur(true)}} className="rounded-xl bg-rose-800 px-4 py-2 text-xs font-bold text-white"><CalendarOff className="mr-1 inline h-4 w-4"/>Hari Libur</button></div>}</div>
  <div className="flex gap-2 rounded-2xl border bg-white p-2"><button onClick={()=>setTab('agenda')} className={`rounded-xl px-4 py-2 text-xs font-bold ${tab==='agenda'?'bg-emerald-800 text-white':'text-slate-600'}`}>Kalender Pendidikan</button><button onClick={()=>setTab('libur')} className={`rounded-xl px-4 py-2 text-xs font-bold ${tab==='libur'?'bg-rose-800 text-white':'text-slate-600'}`}>Hari Libur / Kunci Absensi</button></div>
  {tab==='agenda'?<div className="space-y-3">{sorted.length===0?<Empty text="Belum ada agenda pendidikan yang ditetapkan."/>:sorted.map(x=><div key={x.id} className="rounded-2xl border bg-white p-4"><div className="flex justify-between gap-3"><div><div className="text-sm font-black">{x.judul}</div><div className="mt-1 text-xs text-slate-500">{format(x.mulai)}{x.selesai!==x.mulai?` – ${format(x.selesai)}`:''} · {x.kategori}</div>{x.keterangan&&<p className="mt-2 text-xs text-slate-600">{x.keterangan}</p>}{x.kunciAbsensi&&<span className="mt-2 inline-block rounded-full bg-rose-50 px-2 py-1 text-[10px] font-bold text-rose-700">Absensi dikunci</span>}</div>{isAdmin&&<button onClick={()=>{const n=agenda.filter(v=>v.id!==x.id);setAgenda(n);localStorage.setItem(AGENDA_KEY,JSON.stringify(n))}} className="h-8 rounded-lg border px-2 text-rose-700"><Trash2 className="h-4 w-4"/></button>}</div></div>)}</div>:<div className="space-y-3">{libur.length===0?<Empty text="Belum ada hari libur resmi yang ditetapkan."/>:libur.map(x=><div key={x.id} className="rounded-2xl border border-rose-100 bg-white p-4"><div className="flex justify-between"><div><div className="text-sm font-black">{x.keterangan}</div><div className="mt-1 text-xs text-slate-500">{format(x.mulai)}{x.selesai!==x.mulai?` – ${format(x.selesai)}`:''}</div></div>{isAdmin&&<button onClick={()=>{const n=libur.filter(v=>v.id!==x.id);setLibur(n);localStorage.setItem(LIBUR_KEY,JSON.stringify(n))}} className="h-8 rounded-lg border px-2 text-rose-700"><Trash2 className="h-4 w-4"/></button>}</div></div>)}</div>}
  {showAgenda&&<Modal title="Tambah Agenda" close={()=>setShowAgenda(false)}><form onSubmit={saveAgenda} className="space-y-3"><Input label="Judul agenda" value={a.judul} set={v=>setA({...a,judul:v})}/><Dates mulai={a.mulai} selesai={a.selesai} setMulai={v=>setA({...a,mulai:v})} setSelesai={v=>setA({...a,selesai:v})}/><label className="block text-xs font-bold">Kategori<select value={a.kategori} onChange={e=>setA({...a,kategori:e.target.value as Agenda['kategori']})} className="mt-1 w-full rounded-xl border p-2.5 font-normal">{['KBM','Ujian','Libur','Pondok','Muhafadloh'].map(v=><option key={v}>{v}</option>)}</select></label><Input label="Keterangan" value={a.keterangan} set={v=>setA({...a,keterangan:v})}/><label className="flex gap-2 text-xs"><input type="checkbox" checked={a.kunciAbsensi} onChange={e=>setA({...a,kunciAbsensi:e.target.checked})}/>Tetapkan juga sebagai libur/kunci absensi</label><Submit/></form></Modal>}
  {showLibur&&<Modal title="Tambah Hari Libur" close={()=>setShowLibur(false)}><form onSubmit={saveLibur} className="space-y-3"><Input label="Keterangan libur" value={l.keterangan} set={v=>setL({...l,keterangan:v})}/><Dates mulai={l.mulai} selesai={l.selesai} setMulai={v=>setL({...l,mulai:v})} setSelesai={v=>setL({...l,selesai:v})}/><Submit/></form></Modal>}
 </div>
};
const Empty=({text}:{text:string})=><div className="rounded-2xl border border-dashed bg-white p-10 text-center text-sm text-slate-500">{text}</div>;
const Modal=({title,close,children}:{title:string;close:()=>void;children:React.ReactNode})=><div className="fixed inset-0 z-50 bg-slate-950/60 p-4"><div className="mx-auto mt-12 max-w-lg rounded-3xl bg-white p-6"><div className="mb-4 flex justify-between"><h3 className="font-black">{title}</h3><button onClick={close} type="button">×</button></div>{children}</div></div>;
const Input=({label,value,set}:{label:string;value:string;set:(v:string)=>void})=><label className="block text-xs font-bold">{label}<input value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded-xl border p-2.5 font-normal"/></label>;
const Dates=({mulai,selesai,setMulai,setSelesai}:{mulai:string;selesai:string;setMulai:(v:string)=>void;setSelesai:(v:string)=>void})=><div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold">Mulai<input type="date" value={mulai} onChange={e=>setMulai(e.target.value)} className="mt-1 w-full rounded-xl border p-2.5 font-normal"/></label><label className="text-xs font-bold">Selesai<input type="date" value={selesai} onChange={e=>setSelesai(e.target.value)} className="mt-1 w-full rounded-xl border p-2.5 font-normal"/></label></div>;
const Submit=()=> <button className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-800 px-4 py-2.5 text-xs font-bold text-white"><Save className="h-4 w-4"/>Simpan</button>;
