import React, { useMemo, useState } from 'react';
import { Award, Edit2, Printer, Save, ShieldAlert, X } from 'lucide-react';
import { storageService } from './storageServiceProduction';
import { UserProfile } from './types';

type NilaiIjazah = { no:number; mapel:string; angka:number; huruf?:string };
interface IjazahViewProps { currentUser?:UserProfile; userRole?:string }
const MAPEL = ['Tasawwuf','Fiqih','Tauhid','Aswaja','Baca Kitab','Baca Al-Qur’an','Muhafadhoh'];
const terbilang=(n:number):string=>{const d=['','Satu','Dua','Tiga','Empat','Lima','Enam','Tujuh','Delapan','Sembilan','Sepuluh','Sebelas'];if(!n||n<0)return '—';const b=(x:number):string=>x<12?d[x]:x<20?`${b(x-10)} belas`:x<100?`${b(Math.floor(x/10))} puluh${x%10?` ${b(x%10)}`:''}`:String(x);return b(Math.round(n));};

export const IjazahView:React.FC<IjazahViewProps>=({currentUser,userRole='Guru'})=>{
  const isAdmin=userRole.toLowerCase()==='admin', isSiswa=userRole.toLowerCase()==='siswa';
  const students=useMemo(()=>storageService.getStudents(),[]), kelas6=useMemo(()=>students.filter(s=>String(s.kelas).replace(/^Kelas\s+/i,'')==='6'),[students]);
  const own=useMemo(()=>{if(!isSiswa||!currentUser)return null;const nis=(currentUser.nipOrNis||'').replace(/\D/g,'');return students.find(s=>s.nis.replace(/\D/g,'')===nis)||null;},[isSiswa,currentUser,students]);
  if(isSiswa&&(!own||String(own.kelas).replace(/^Kelas\s+/i,'')!=='6'))return <div className="mx-auto my-12 max-w-lg rounded-3xl border border-rose-200 bg-white p-8 text-center"><ShieldAlert className="mx-auto mb-3 h-12 w-12 text-rose-600"/><h2 className="font-black">Akses Ijazah Dibatasi</h2><p className="mt-2 text-xs text-slate-600">Ijazah hanya tersedia untuk santri kelas 6 yang telah ditetapkan lulus.</p></div>;
  const [selectedNis,setSelectedNis]=useState(own?.nis||kelas6[0]?.nis||'');
  const [overrides,setOverrides]=useState(()=>storageService.getIjazahOverrides());
  const [signatures,setSignatures]=useState(()=>storageService.getSignaturesAndMusrif());
  const [page,setPage]=useState<'depan'|'belakang'>('depan'),[showEdit,setShowEdit]=useState(false);
  const selected=isSiswa?own:(kelas6.find(s=>s.nis===selectedNis)||kelas6[0]); if(!selected)return <div className="rounded-2xl border bg-white p-8 text-center text-sm text-slate-500">Belum ada data santri kelas 6.</div>;
  const o=overrides[selected.nis]||{}, base:NilaiIjazah[]=MAPEL.map((mapel,i)=>({no:i+1,mapel,angka:0,huruf:'—'})), scores:NilaiIjazah[]=o.nilaiMapel?.length?o.nilaiMapel:base;
  const [nomor,setNomor]=useState(''),[status,setStatus]=useState('LULUS'),[tempat,setTempat]=useState(''),[tanggal,setTanggal]=useState(''),[titimangsa,setTitimangsa]=useState(''),[pengasuh,setPengasuh]=useState(''),[editScores,setEditScores]=useState<NilaiIjazah[]>(base);
  const openEdit=()=>{setNomor(o.nomorIjazah||signatures.nomorIjazahTemplate?.replace('{NIS}',selected.nis)||'');setStatus(o.statusKelulusan||'LULUS');setTempat(o.tempatLahir||selected.tempatLahir||'');setTanggal(o.tanggalLahir||selected.tanggalLahir||'');setTitimangsa(signatures.titimangsaIjazah||'');setPengasuh(signatures.namaPengasuh||'');setEditScores(scores.map(s=>({...s})));setShowEdit(true);};
  const save=(e:React.FormEvent)=>{e.preventDefault();storageService.saveIjazahOverride(selected.nis,{nomorIjazah:nomor.trim(),statusKelulusan:status.trim(),tempatLahir:tempat.trim(),tanggalLahir:tanggal.trim(),nilaiMapel:editScores.map(s=>({...s,angka:Number(s.angka)||0,huruf:terbilang(Number(s.angka)||0)}))});const sig={...signatures,titimangsaIjazah:titimangsa.trim(),namaPengasuh:pengasuh.trim()};storageService.saveSignaturesAndMusrif(sig);setSignatures(sig);setOverrides(storageService.getIjazahOverrides());setShowEdit(false);};
  const nums=scores.map(s=>Number(s.angka)||0).filter(n=>n>0), complete=nums.length===scores.length, total=complete?nums.reduce((a,b)=>a+b,0):null, avg=complete&&total!==null?Math.round(total/scores.length):null;
  const nomorTampil=o.nomorIjazah||signatures.nomorIjazahTemplate?.replace('{NIS}',selected.nis)||'........................';
  const tempatTampil=o.tempatLahir||selected.tempatLahir||'........................', tanggalTampil=o.tanggalLahir||selected.tanggalLahir||'........................';
  const tgl=signatures.titimangsaIjazah||'........................', pimpinan=signatures.namaPengasuh||'........................';

  return <div className="space-y-5 pb-10">
    <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between print:hidden"><div><div className="text-[10px] font-black uppercase tracking-widest text-emerald-700">Dokumen Kelulusan</div><h1 className="flex items-center gap-2 text-2xl font-black"><Award className="h-6 w-6 text-emerald-700"/>Ijazah Madrasah Diniyah</h1><p className="text-xs text-slate-500">Susunan dua halaman dan bingkai dibuat mengikuti contoh ijazah yang diberikan.</p></div><div className="flex flex-wrap gap-2">{!isSiswa&&<select value={selected.nis} onChange={e=>setSelectedNis(e.target.value)} className="rounded-xl border bg-white px-3 py-2 text-xs">{kelas6.map(s=><option key={s.nis} value={s.nis}>{s.nama} — {s.nis}</option>)}</select>}<button onClick={()=>setPage(page==='depan'?'belakang':'depan')} className="rounded-xl border bg-white px-3 py-2 text-xs font-bold">{page==='depan'?'Lihat Halaman Nilai':'Lihat Halaman Depan'}</button>{isAdmin&&<button onClick={openEdit} className="rounded-xl bg-amber-400 px-3 py-2 text-xs font-black"><Edit2 className="mr-1 inline h-4 w-4"/>Edit</button>}<button onClick={()=>window.print()} className="rounded-xl bg-emerald-800 px-3 py-2 text-xs font-bold text-white"><Printer className="mr-1 inline h-4 w-4"/>Cetak</button></div></div>
    {page==='depan'?<Depan nama={selected.nama} nomor={nomorTampil} status={o.statusKelulusan||'LULUS'} tempat={tempatTampil} tanggal={tanggalTampil} tgl={tgl} pimpinan={pimpinan}/>:<Belakang nama={selected.nama} scores={scores} total={total} avg={avg} tgl={tgl} pimpinan={pimpinan}/>} 
    {showEdit&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-4 print:hidden"><form onSubmit={save} className="mx-auto my-6 max-w-3xl rounded-3xl bg-white p-6"><div className="flex justify-between"><h3 className="font-black">Edit Ijazah — {selected.nama}</h3><button type="button" onClick={()=>setShowEdit(false)}><X className="h-5 w-5"/></button></div><div className="mt-4 grid gap-3 sm:grid-cols-2 text-xs"><Input label="Nomor Ijazah" value={nomor} set={setNomor}/><Input label="Status Kelulusan" value={status} set={setStatus}/><Input label="Tempat Lahir" value={tempat} set={setTempat}/><Input label="Tanggal Lahir" value={tanggal} set={setTanggal}/><Input label="Titimangsa" value={titimangsa} set={setTitimangsa}/><Input label="Nama Pengasuh" value={pengasuh} set={setPengasuh}/></div><div className="mt-4 overflow-hidden rounded-xl border"><table className="w-full text-xs"><tbody>{editScores.map((s,i)=><tr key={s.mapel} className="border-t first:border-0"><td className="p-2 font-semibold">{s.mapel}</td><td className="w-32 p-2"><input type="number" min="0" max="100" value={s.angka||''} onChange={e=>setEditScores(p=>p.map((x,j)=>j===i?{...x,angka:Number(e.target.value)||0}:x))} className="w-full rounded-lg border px-2 py-1.5 text-center"/></td></tr>)}</tbody></table></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setShowEdit(false)} className="rounded-xl border px-4 py-2 text-xs font-bold">Batal</button><button className="rounded-xl bg-emerald-800 px-4 py-2 text-xs font-bold text-white"><Save className="mr-1 inline h-4 w-4"/>Simpan</button></div></form></div>}
    <style>{`@media print{body *{visibility:hidden}.ijazah-page,.ijazah-page *{visibility:visible}.ijazah-page{position:absolute;left:0;top:0}@page{size:A4 portrait;margin:0}}`}</style>
  </div>;
};

const Frame=({children}:{children:React.ReactNode})=><section className="ijazah-page relative mx-auto min-h-[297mm] w-full max-w-[210mm] overflow-hidden bg-white px-[25mm] py-[28mm] font-serif text-black shadow-xl print:m-0 print:min-h-[297mm] print:w-[210mm] print:max-w-none print:shadow-none"><Ornamen/><img src="/logo.png" alt="" className="pointer-events-none absolute left-1/2 top-[52%] w-[120mm] -translate-x-1/2 -translate-y-1/2 opacity-[0.09]"/><div className="relative z-10">{children}</div></section>;
const Ornamen=()=>{const row=Array.from({length:13},(_,i)=><span key={i} className="mx-[2px] text-[23px] text-emerald-700">❦</span>);const side=Array.from({length:18},(_,i)=><span key={i} className="block text-[22px] leading-[14mm] text-emerald-700">❦</span>);return <><div className="absolute left-[7mm] right-[7mm] top-[5mm] h-[12mm] overflow-hidden whitespace-nowrap border-y-2 border-amber-400 text-center">{row}</div><div className="absolute bottom-[5mm] left-[7mm] right-[7mm] h-[12mm] overflow-hidden whitespace-nowrap border-y-2 border-amber-400 text-center">{row}</div><div className="absolute bottom-[17mm] left-[5mm] top-[17mm] w-[13mm] overflow-hidden border-x-2 border-amber-400 text-center">{side}</div><div className="absolute bottom-[17mm] right-[5mm] top-[17mm] w-[13mm] overflow-hidden border-x-2 border-amber-400 text-center">{side}</div><div className="absolute left-[5mm] top-[5mm] text-4xl font-black text-amber-500">✾</div><div className="absolute right-[5mm] top-[5mm] text-4xl font-black text-amber-500">✾</div><div className="absolute bottom-[5mm] left-[5mm] text-4xl font-black text-amber-500">✾</div><div className="absolute bottom-[5mm] right-[5mm] text-4xl font-black text-amber-500">✾</div></>};

const Depan=({nama,nomor,status,tempat,tanggal,tgl,pimpinan}:{nama:string;nomor:string;status:string;tempat:string;tanggal:string;tgl:string;pimpinan:string})=><Frame><div className="text-center"><img src="/logo.png" alt="Logo" className="mx-auto h-20 w-20 object-contain"/><div className="mt-7 text-[28px]" dir="rtl">المعهد الإسلامي الناجية ٢ بحر العلوم</div><div className="mt-6 text-[30px] font-black tracking-[0.25em] underline">IJAZAH</div><div className="text-[20px] font-bold">MADRASAH DINIYAH</div><div className="text-[15px] font-bold">PONDOK PESANTREN AN-NAJIYAH 2 BAHRUL ‘ULUM</div><div className="text-[15px] font-bold">TAMBAKBERAS JOMBANG JAWA TIMUR</div><div className="mt-5 text-[14px]">Nomor : <b>{nomor}</b></div></div><div className="mt-7 text-[14px] leading-7">Yang bertandatangan dibawah ini, Pengasuh Pondok Pesantren An-Najiyah 2 Bahrul ‘Ulum Tambakberas Jombang menerangkan bahwa :</div><div className="mt-6 text-center text-[25px] font-black underline decoration-dashed underline-offset-[10px]">{nama}</div><div className="mt-7 text-[14px]">Tempat / Tanggal Lahir : <b>{tempat}, {tanggal}</b></div><div className="mt-5 text-[14px]">Dinyatakan :</div><div className="mt-4 text-center text-[30px] font-black underline decoration-dashed underline-offset-[10px]">{status}</div><div className="mt-7 text-[14px] leading-7">Dari Pendidikan Madrasah Diniyah Takmiliyah Pondok Pesantren An-Najiyah 2 Bahrul ‘Ulum Tambakberas Jombang berdasarkan Ujian Akhir Madrasah Diniyah.</div><div className="ml-auto mt-7 w-[80mm] text-center text-[14px]"><div>Jombang, {tgl}</div><div>Pengasuh PP. An-Najiyah 2 Bahrul ‘Ulum</div><div className="h-24"></div><div className="font-bold">{pimpinan}</div></div></Frame>;
const Belakang=({nama,scores,total,avg,tgl,pimpinan}:{nama:string;scores:NilaiIjazah[];total:number|null;avg:number|null;tgl:string;pimpinan:string})=><Frame><div className="mt-4 text-center"><div className="text-[24px] font-black">DAFTAR NILAI UJIAN AKHIR MADRASAH DINIYAH</div><div className="text-[16px] font-bold">PONDOK PESANTREN AN-NAJIYAH 2 BAHRUL ‘ULUM</div><div className="text-[16px] font-bold">TAMBAKBERAS JOMBANG</div></div><div className="mt-8 text-[14px]">Dari : <b>{nama}</b></div><table className="mt-6 w-full border-collapse text-[14px]"><thead><tr><th rowSpan={2} className="border border-black p-2">NO</th><th rowSpan={2} className="border border-black p-2">MATA PELAJARAN</th><th colSpan={2} className="border border-black p-2">NILAI</th></tr><tr><th className="border border-black p-2">ANGKA</th><th className="border border-black p-2">HURUF</th></tr></thead><tbody>{scores.map(s=><tr key={s.no}><td className="border border-black p-2 text-center">{s.no}</td><td className="border border-black p-2">{s.mapel}</td><td className="border border-black p-2 text-center">{s.angka>0?s.angka:'—'}</td><td className="border border-black p-2">{s.angka>0?(s.huruf||terbilang(s.angka)):'—'}</td></tr>)}<tr><td colSpan={2} className="border border-black p-2 text-center font-bold">JUMLAH NILAI</td><td className="border border-black p-2 text-center">{total??'—'}</td><td className="border border-black p-2">{total?terbilang(total):'—'}</td></tr><tr><td colSpan={2} className="border border-black p-2 text-center font-bold">RATA-RATA</td><td className="border border-black p-2 text-center">{avg??'—'}</td><td className="border border-black p-2">{avg?terbilang(avg):'—'}</td></tr></tbody></table><div className="ml-auto mt-7 w-[80mm] text-center text-[14px]"><div>Jombang, {tgl}</div><div>Pengasuh PP. An-Najiyah 2 Bahrul ‘Ulum</div><div className="h-24"></div><div className="font-bold">{pimpinan}</div></div></Frame>;
const Input=({label,value,set}:{label:string;value:string;set:(v:string)=>void})=><label className="font-bold">{label}<input value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2"/></label>;
