import React,{useMemo,useState}from'react';
import{Award,Edit2,Printer,Save,ShieldAlert,X}from'lucide-react';
import{storageService}from'../services/storageService';
import{UserProfile}from'../types';

interface IjazahViewProps{currentUser?:UserProfile;userRole?:string}
type NilaiIjazah={no:number;mapel:string;angka:number;huruf?:string};
const MAPEL_IJAZAH=['Tasawwuf','Fiqih','Tauhid','Aswaja','Baca Kitab','Baca Al-Qur’an','Muhafadhoh'];
const terbilang=(n:number):string=>{const d=['','Satu','Dua','Tiga','Empat','Lima','Enam','Tujuh','Delapan','Sembilan','Sepuluh','Sebelas'];if(!Number.isFinite(n)||n<=0)return'—';const x=Math.round(n);const baca=(v:number):string=>v<12?d[v]:v<20?`${baca(v-10)} Belas`:v<100?`${baca(Math.floor(v/10))} Puluh${v%10?` ${baca(v%10)}`:''}`:String(v);return baca(x)};

export const IjazahView:React.FC<IjazahViewProps>=({currentUser,userRole='Guru'})=>{
 const isAdmin=userRole.toLowerCase()==='admin';const isSiswa=userRole.toLowerCase()==='siswa';
 const students=useMemo(()=>storageService.getStudents(),[]);const kelas6=useMemo(()=>students.filter(s=>String(s.kelas).replace(/^Kelas\s+/i,'')==='6'),[students]);
 const ownStudent=useMemo(()=>{if(!isSiswa||!currentUser)return null;const nis=(currentUser.nipOrNis||'').replace(/\D/g,'');return students.find(s=>s.nis.replace(/\D/g,'')===nis)||null},[isSiswa,currentUser,students]);
 const[selectedNis,setSelectedNis]=useState(()=>ownStudent?.nis||kelas6[0]?.nis||'');
 const[overrides,setOverrides]=useState(()=>storageService.getIjazahOverrides());const[signatures,setSignatures]=useState(()=>storageService.getSignaturesAndMusrif());const[showEdit,setShowEdit]=useState(false);const[activePage,setActivePage]=useState<'depan'|'belakang'>('depan');
 const baseScores=useMemo<NilaiIjazah[]>(()=>MAPEL_IJAZAH.map((mapel,i)=>({no:i+1,mapel,angka:0,huruf:'—'})),[]);
 const[editNomor,setEditNomor]=useState('');const[editStatus,setEditStatus]=useState('');const[editTempatLahir,setEditTempatLahir]=useState('');const[editTanggalLahir,setEditTanggalLahir]=useState('');const[editTitimangsa,setEditTitimangsa]=useState('');const[editPengasuh,setEditPengasuh]=useState('');const[editScores,setEditScores]=useState<NilaiIjazah[]>(baseScores);
 const selected=isSiswa?ownStudent:(kelas6.find(s=>s.nis===selectedNis)||kelas6[0]);const o=selected?overrides[selected.nis]||{}:{};const scores:NilaiIjazah[]=o.nilaiMapel?.length?o.nilaiMapel:baseScores;
 const diterbitkan=Boolean(o.statusKelulusan&&o.statusKelulusan.replace(/\s/g,'').toUpperCase()==='LULUS');
 const tahunAjaran=storageService.getTahunAjaran();
 const openEdit=()=>{if(!selected)return;setEditNomor(o.nomorIjazah||signatures.nomorIjazahTemplate?.replace('{NIS}',selected.nis)||'');setEditStatus(o.statusKelulusan||'');setEditTempatLahir(o.tempatLahir||selected.tempatLahir||'');setEditTanggalLahir(o.tanggalLahir||selected.tanggalLahir||'');setEditTitimangsa(signatures.titimangsaIjazah||'');setEditPengasuh(signatures.namaPengasuh||'');setEditScores(scores.map(s=>({...s})));setShowEdit(true)};
 const saveEdit=(e:React.FormEvent)=>{e.preventDefault();if(!selected)return;storageService.saveIjazahOverride(selected.nis,{nomorIjazah:editNomor.trim(),statusKelulusan:editStatus.trim(),tempatLahir:editTempatLahir.trim(),tanggalLahir:editTanggalLahir.trim(),nilaiMapel:editScores.map(s=>({...s,angka:Number(s.angka)||0,huruf:terbilang(Number(s.angka)||0)}))});const sig={...signatures,titimangsaIjazah:editTitimangsa.trim(),namaPengasuh:editPengasuh.trim()};storageService.saveSignaturesAndMusrif(sig);setSignatures(sig);setOverrides(storageService.getIjazahOverrides());setShowEdit(false)};
 if(isSiswa&&(!ownStudent||String(ownStudent.kelas).replace(/^Kelas\s+/i,'')!=='6'))return <Notice title="Akses Ijazah Dibatasi" text="Ijazah hanya tersedia untuk santri tingkat akhir."/>;
 if(!selected)return <Notice title="Belum Ada Data" text="Belum ada data santri kelas 6."/>;
 if(isSiswa&&!diterbitkan)return <Notice title="Ijazah Belum Diterbitkan" text="Status kelulusan dan penerbitan ijazah belum ditetapkan administrator."/>;
 const nomor=o.nomorIjazah||signatures.nomorIjazahTemplate?.replace('{NIS}',selected.nis)||'—';const tempat=o.tempatLahir||selected.tempatLahir||'—';const tanggal=o.tanggalLahir||selected.tanggalLahir||'—';const status=o.statusKelulusan||'BELUM DITETAPKAN';const total=scores.every(s=>s.angka>0)?scores.reduce((a,b)=>a+b.angka,0):0;const rata=total?(total/scores.length).toFixed(2):'—';
 return <div className="space-y-5 pb-10"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between print:hidden"><div><div className="text-[10px] font-black uppercase tracking-widest text-emerald-700">Dokumen Kelulusan</div><h1 className="flex items-center gap-2 text-2xl font-black"><Award className="h-6 w-6 text-emerald-700"/>Ijazah Madrasah Diniyah</h1><p className="mt-1 text-xs text-slate-500">Format dua halaman mengikuti contoh ijazah resmi yang diberikan.</p></div><div className="flex flex-wrap gap-2">{!isSiswa&&<select value={selected.nis} onChange={e=>setSelectedNis(e.target.value)} className="rounded-xl border bg-white px-3 py-2 text-xs">{kelas6.map(s=><option key={s.nis} value={s.nis}>{s.nama} — {s.nis}</option>)}</select>}<button onClick={()=>setActivePage(activePage==='depan'?'belakang':'depan')} className="rounded-xl border bg-white px-3 py-2 text-xs font-bold">{activePage==='depan'?'Halaman Nilai':'Halaman Depan'}</button>{isAdmin&&<button onClick={openEdit} className="rounded-xl bg-amber-400 px-3 py-2 text-xs font-black text-emerald-950"><Edit2 className="mr-1 inline h-4 w-4"/>Edit Ijazah</button>}<button onClick={()=>window.print()} className="rounded-xl bg-emerald-800 px-3 py-2 text-xs font-bold text-white"><Printer className="mr-1 inline h-4 w-4"/>Cetak</button></div></div>
 {activePage==='depan'?<Depan nama={selected.nama} nomor={nomor} tempat={tempat} tanggal={tanggal} status={status} tahun={tahunAjaran} titimangsa={signatures.titimangsaIjazah||'—'} pengasuh={signatures.namaPengasuh||'—'}/>:<Belakang nama={selected.nama} scores={scores} total={total} rata={rata} tahun={tahunAjaran} titimangsa={signatures.titimangsaIjazah||'—'} pengasuh={signatures.namaPengasuh||'—'}/>} 
 {showEdit&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-4 print:hidden"><form onSubmit={saveEdit} className="mx-auto my-6 max-w-3xl rounded-3xl bg-white p-6"><div className="flex justify-between"><div><h3 className="font-black">Edit Ijazah — {selected.nama}</h3><p className="text-xs text-slate-500">Isi hanya data resmi. Status LULUS harus ditetapkan secara eksplisit.</p></div><button type="button" onClick={()=>setShowEdit(false)}><X className="h-5 w-5"/></button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Input label="Nomor Ijazah" value={editNomor} set={setEditNomor}/><Input label="Status Kelulusan" value={editStatus} set={setEditStatus}/><Input label="Tempat Lahir" value={editTempatLahir} set={setEditTempatLahir}/><Input label="Tanggal Lahir" value={editTanggalLahir} set={setEditTanggalLahir}/><Input label="Titimangsa" value={editTitimangsa} set={setEditTitimangsa}/><Input label="Nama Pengasuh" value={editPengasuh} set={setEditPengasuh}/></div><table className="mt-4 w-full border-collapse text-xs"><thead><tr className="bg-slate-100"><th className="border p-2 text-left">Mata Pelajaran</th><th className="border p-2 w-32">Nilai</th></tr></thead><tbody>{editScores.map((s,i)=><tr key={s.mapel}><td className="border p-2">{s.mapel}</td><td className="border p-2"><input type="number" min="0" max="100" value={s.angka||''} onChange={e=>setEditScores(p=>p.map((x,j)=>j===i?{...x,angka:Number(e.target.value)||0}:x))} className="w-full rounded-lg border p-1.5 text-center"/></td></tr>)}</tbody></table><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setShowEdit(false)} className="px-4 py-2 text-xs font-bold">Batal</button><button className="rounded-xl bg-emerald-800 px-5 py-2 text-xs font-bold text-white"><Save className="mr-1 inline h-4 w-4"/>Simpan</button></div></form></div>}</div>;
};

const Frame=({children}:{children:React.ReactNode})=><div className="ijazah-page relative mx-auto min-h-[1120px] w-full max-w-[790px] overflow-hidden bg-white px-[72px] py-[78px] font-serif text-black shadow-xl print:min-h-[297mm] print:w-[210mm] print:max-w-none print:shadow-none"><div className="pointer-events-none absolute inset-4 rounded-[24px] border-[7px] border-emerald-700"/><div className="pointer-events-none absolute inset-7 rounded-[20px] border-[3px] border-amber-400"/>{[['left-8 top-7','❧'],['right-8 top-7','❧'],['left-8 bottom-7','❧'],['right-8 bottom-7','❧']].map(([p,t],i)=><div key={i} className={`absolute ${p} text-5xl font-black text-emerald-700`}>{t}</div>)}<img src="/logo.png" alt="" className="pointer-events-none absolute left-1/2 top-[53%] w-[470px] -translate-x-1/2 -translate-y-1/2 opacity-[0.10]"/><div className="relative z-10">{children}</div></div>;
const Depan=({nama,nomor,tempat,tanggal,status,tahun,titimangsa,pengasuh}:{nama:string;nomor:string;tempat:string;tanggal:string;status:string;tahun:string;titimangsa:string;pengasuh:string})=><Frame><div className="text-center"><img src="/logo.png" className="mx-auto h-24 w-24 object-contain"/><div className="mt-8 text-3xl font-bold" dir="rtl">المعهد الإسلامي الناجية ٢ بحر العلوم</div><div className="mt-7 text-4xl font-black tracking-[0.25em] underline">IJAZAH</div><div className="mt-1 text-2xl font-black">MADRASAH DINIYAH</div><div className="text-lg">PONDOK PESANTREN AN-NAJIYAH 2 BAHRUL ‘ULUM</div><div className="text-lg">TAMBAKBERAS JOMBANG JAWA TIMUR</div><div className="mt-5 text-lg">Tahun Pelajaran : {tahun}</div><div className="text-lg">Nomor : {nomor}</div></div><p className="mt-10 text-lg leading-relaxed">Yang bertandatangan dibawah ini, Pengasuh Pondok Pesantren An-Najiyah 2 Bahrul ‘Ulum Tambakberas Jombang menerangkan bahwa :</p><div className="mt-6 border-b border-dashed pb-2 text-center text-3xl font-black">{nama}</div><div className="mt-5 grid grid-cols-[130px_20px_1fr] text-lg"><span>Tempat lahir</span><span>:</span><b>{tempat}</b><span>Tanggal lahir</span><span>:</span><b>{tanggal}</b></div><div className="mt-7 text-lg">Dinyatakan :</div><div className="mx-auto mt-3 w-2/3 border-b border-dashed pb-2 text-center text-4xl font-black">{status}</div><p className="mt-6 text-lg leading-relaxed">Dari Pendidikan Madrasah Diniyah Takmiliyah Pondok Pesantren An-Najiyah 2 Bahrul ‘Ulum Tambakberas Jombang berdasarkan Ujian Akhir Madrasah Diniyah.</p><Signature titimangsa={titimangsa} pengasuh={pengasuh}/></Frame>;
const Belakang=({nama,scores,total,rata,tahun,titimangsa,pengasuh}:{nama:string;scores:NilaiIjazah[];total:number;rata:string;tahun:string;titimangsa:string;pengasuh:string})=><Frame><div className="mt-16 text-center"><div className="text-2xl font-black">DAFTAR NILAI UJIAN AKHIR MADRASAH DINIYAH</div><div className="mt-1 text-lg">PONDOK PESANTREN AN-NAJIYAH 2 BAHRUL ‘ULUM</div><div className="text-lg">TAMBAKBERAS JOMBANG</div><div className="text-lg">TAHUN PELAJARAN {tahun}</div></div><div className="mt-8 text-lg">Dari&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <b>{nama}</b></div><table className="mt-7 w-full border-collapse text-lg"><thead><tr><th rowSpan={2} className="border border-black p-2">NO</th><th rowSpan={2} className="border border-black p-2 text-left">MATA PELAJARAN</th><th colSpan={2} className="border border-black p-2">NILAI</th></tr><tr><th className="border border-black p-2">ANGKA</th><th className="border border-black p-2">HURUF</th></tr></thead><tbody>{scores.map(s=><tr key={s.no}><td className="border border-black p-2 text-center">{s.no}</td><td className="border border-black p-2">{s.mapel}</td><td className="border border-black p-2 text-center">{s.angka||'—'}</td><td className="border border-black p-2">{s.angka?terbilang(s.angka).toLowerCase():'—'}</td></tr>)}<tr><td colSpan={2} className="border border-black p-2 text-center font-bold">JUMLAH NILAI</td><td className="border border-black p-2 text-center">{total||'—'}</td><td className="border border-black p-2">{total?terbilang(total).toLowerCase():'—'}</td></tr><tr><td colSpan={2} className="border border-black p-2 text-center font-bold">RATA-RATA</td><td className="border border-black p-2 text-center">{rata}</td><td className="border border-black p-2">{rata!=='—'?terbilang(Number(rata)).toLowerCase():'—'}</td></tr></tbody></table><Signature titimangsa={titimangsa} pengasuh={pengasuh}/></Frame>;
const Signature=({titimangsa,pengasuh}:{titimangsa:string;pengasuh:string})=><div className="ml-auto mt-12 w-[340px] text-center text-lg"><div>{titimangsa}</div><div className="mt-2">Pengasuh PP. An-Najiyah 2 Bahrul ‘Ulum</div><div className="h-24"/><div className="font-bold">{pengasuh}</div></div>;
const Notice=({title,text}:{title:string;text:string})=><div className="mx-auto my-12 max-w-lg rounded-3xl border border-rose-200 bg-white p-8 text-center"><ShieldAlert className="mx-auto mb-3 h-12 w-12 text-rose-600"/><h2 className="text-lg font-black">{title}</h2><p className="mt-2 text-xs text-slate-600">{text}</p></div>;
const Input=({label,value,set}:{label:string;value:string;set:(v:string)=>void})=><label className="text-xs font-bold">{label}<input value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2 font-normal"/></label>;
