import React, { useState } from 'react';
import { Calendar, Plus, Save, Trash2, X } from 'lucide-react';
import { JadwalSlotItem, GuruJadwal } from './types';

interface JadwalViewProps { userRole?: string; }
const SLOT_KEY='annajiyah_v2_schedule_prod';
const GURU_KEY='annajiyah_v2_teachers_prod';
const load=<T,>(key:string,fallback:T):T=>{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}};
const save=(key:string,value:unknown)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}};
const HARI:JadwalSlotItem['hari'][]=["Jum'at",'Sabtu','Minggu','Selasa','Rabu'];
const KELAS=['1A','1B','2A','2B','3A','3B','3C','4A','4B','5A','5B','6'];

export const JadwalView:React.FC<JadwalViewProps>=({userRole='Guru'})=>{
  const isAdmin=userRole.toLowerCase()==='admin';
  const [slots,setSlots]=useState<JadwalSlotItem[]>(()=>load(SLOT_KEY,[]));
  const [gurus,setGurus]=useState<GuruJadwal[]>(()=>load(GURU_KEY,[]));
  const [showSlot,setShowSlot]=useState(false); const [showGuru,setShowGuru]=useState(false);
  const [kelas,setKelas]=useState('1A'); const [hari,setHari]=useState<JadwalSlotItem['hari']>("Jum'at"); const [kitab,setKitab]=useState(''); const [fan,setFan]=useState(''); const [guruKode,setGuruKode]=useState(0);
  const [guruNama,setGuruNama]=useState(''); const [kodeBaru,setKodeBaru]=useState(1);
  const addSlot=(e:React.FormEvent)=>{e.preventDefault();if(!kitab.trim()||!fan.trim()||!guruKode)return;const next=[...slots.filter(s=>!(s.kelas===kelas&&s.hari===hari)),{id:`jadwal-${Date.now()}`,kelas,hari,kitab:kitab.trim(),fanIlmu:fan.trim(),kodeGuru:guruKode}];setSlots(next);save(SLOT_KEY,next);setShowSlot(false);setKitab('');setFan('')};
  const addGuru=(e:React.FormEvent)=>{e.preventDefault();if(!guruNama.trim()||gurus.some(g=>g.kode===kodeBaru))return;const next=[...gurus,{kode:kodeBaru,nama:guruNama.trim(),warnaBadge:'bg-emerald-700 text-white'}];setGurus(next);save(GURU_KEY,next);setGuruNama('');setKodeBaru(kodeBaru+1);setShowGuru(false)};
  const removeSlot=(id:string)=>{const next=slots.filter(s=>s.id!==id);setSlots(next);save(SLOT_KEY,next)};
  return <div className="space-y-6 pb-12"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-black flex items-center gap-2"><Calendar className="w-6 h-6 text-emerald-700"/>Jadwal Pelajaran</h1><p className="text-xs text-slate-500 mt-1">Jadwal contoh lama tidak ditampilkan. Data hanya muncul setelah dimasukkan oleh admin.</p></div>{isAdmin&&<div className="flex gap-2"><button onClick={()=>setShowGuru(true)} className="border rounded-xl px-3 py-2 text-xs font-bold">Kelola Guru</button><button onClick={()=>setShowSlot(true)} className="bg-emerald-800 text-white rounded-xl px-3 py-2 text-xs font-bold flex items-center gap-1"><Plus className="w-4 h-4"/>Tambah Jadwal</button></div>}</div>
  {slots.length===0?<div className="rounded-3xl border bg-white p-10 text-center text-sm text-slate-500">Belum ada jadwal resmi yang dimasukkan.</div>:<div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-[800px] w-full text-xs border-collapse"><thead className="bg-slate-100"><tr><th className="border p-2">Kelas</th><th className="border p-2">Hari</th><th className="border p-2">Fan Ilmu</th><th className="border p-2">Kitab</th><th className="border p-2">Guru</th>{isAdmin&&<th className="border p-2">Aksi</th>}</tr></thead><tbody>{slots.sort((a,b)=>a.kelas.localeCompare(b.kelas)).map(s=><tr key={s.id}><td className="border p-2 text-center font-bold">{s.kelas}</td><td className="border p-2 text-center">{s.hari}</td><td className="border p-2">{s.fanIlmu}</td><td className="border p-2">{s.kitab}</td><td className="border p-2">{gurus.find(g=>g.kode===s.kodeGuru)?.nama||'Belum ditetapkan'}</td>{isAdmin&&<td className="border p-2 text-center"><button onClick={()=>removeSlot(s.id)} className="text-rose-700"><Trash2 className="w-4 h-4 inline"/></button></td>}</tr>)}</tbody></table></div>}
  {showSlot&&<div className="fixed inset-0 z-50 bg-slate-950/60 p-4"><form onSubmit={addSlot} className="max-w-lg mx-auto mt-20 rounded-3xl bg-white p-6 space-y-3"><div className="flex justify-between"><h3 className="font-black">Tambah Jadwal</h3><button type="button" onClick={()=>setShowSlot(false)}><X className="w-5 h-5"/></button></div><select value={kelas} onChange={e=>setKelas(e.target.value)} className="w-full border rounded-xl p-2">{KELAS.map(k=><option key={k}>{k}</option>)}</select><select value={hari} onChange={e=>setHari(e.target.value as JadwalSlotItem['hari'])} className="w-full border rounded-xl p-2">{HARI.map(h=><option key={h}>{h}</option>)}</select><input value={fan} onChange={e=>setFan(e.target.value)} placeholder="Fan ilmu" className="w-full border rounded-xl p-2"/><input value={kitab} onChange={e=>setKitab(e.target.value)} placeholder="Nama kitab" className="w-full border rounded-xl p-2"/><select value={guruKode} onChange={e=>setGuruKode(Number(e.target.value))} className="w-full border rounded-xl p-2"><option value={0}>Pilih guru</option>{gurus.map(g=><option key={g.kode} value={g.kode}>{g.nama}</option>)}</select><button className="w-full bg-emerald-800 text-white rounded-xl py-2 font-bold flex justify-center gap-2"><Save className="w-4 h-4"/>Simpan</button></form></div>}
  {showGuru&&<div className="fixed inset-0 z-50 bg-slate-950/60 p-4"><form onSubmit={addGuru} className="max-w-lg mx-auto mt-20 rounded-3xl bg-white p-6 space-y-3"><div className="flex justify-between"><h3 className="font-black">Tambah Guru Jadwal</h3><button type="button" onClick={()=>setShowGuru(false)}><X className="w-5 h-5"/></button></div><input type="number" min={1} value={kodeBaru} onChange={e=>setKodeBaru(Number(e.target.value)||1)} className="w-full border rounded-xl p-2"/><input value={guruNama} onChange={e=>setGuruNama(e.target.value)} placeholder="Nama guru" className="w-full border rounded-xl p-2"/><button className="w-full bg-emerald-800 text-white rounded-xl py-2 font-bold flex justify-center gap-2"><Save className="w-4 h-4"/>Simpan Guru</button></form></div>}
  </div>;
};
