// Master data derived strictly from the official CSV datasets:
// 1. Denah_Nama_Ruang_Kelas_AI_Studio.csv
// 2. Peraturan_Tata_Tertib_Pengajar_Musrif_Santri_AI_Studio.csv
// 3. Silabus_Target_Pembelajaran_Kelas_1_sampai_6_AI_Studio.csv
// 4. Template_Ijazah_Madin_AI_Studio.csv
// 5. Template_Rapot_Madin_AI_Studio.csv

export interface DenahRuangKelas {
  kelas: string;
  tingkat: number;
  namaRuang: string;
  lantai: string;
  keterangan: string;
}

export const DENAH_KELAS_DATA: DenahRuangKelas[] = [
  { kelas: '1A', tingkat: 1, namaRuang: 'Teras Kompleks Umar', lantai: 'Lantai 2', keterangan: 'Sesuai denah dokumen' },
  { kelas: '1B', tingkat: 1, namaRuang: 'Teras Kompleks Umar', lantai: 'Lantai 2', keterangan: 'Sesuai denah dokumen' },
  { kelas: '2A', tingkat: 2, namaRuang: 'Aula', lantai: 'Lantai 1', keterangan: 'Sesuai denah dokumen' },
  { kelas: '2B', tingkat: 2, namaRuang: 'Aula', lantai: 'Lantai 1', keterangan: 'Sesuai denah dokumen' },
  { kelas: '3A', tingkat: 3, namaRuang: 'Ustman 4', lantai: 'Lantai 2', keterangan: 'Sesuai denah dokumen' },
  { kelas: '3B', tingkat: 3, namaRuang: 'Ustman 2', lantai: 'Lantai 2', keterangan: 'Sesuai denah dokumen' },
  { kelas: '3C', tingkat: 3, namaRuang: 'Ustman 1', lantai: 'Lantai 2', keterangan: 'Sesuai denah dokumen' },
  { kelas: '4A', tingkat: 4, namaRuang: 'Aula', lantai: 'Lantai 1', keterangan: 'Sesuai denah dokumen' },
  { kelas: '4B', tingkat: 4, namaRuang: 'Teras Kompleks Abu Bakar', lantai: 'Lantai 1', keterangan: 'Sesuai denah dokumen' },
  { kelas: '5A', tingkat: 5, namaRuang: 'Teras Kompleks Abu Bakar', lantai: 'Lantai 1', keterangan: 'Sesuai denah dokumen' },
  { kelas: '5B', tingkat: 5, namaRuang: 'Teras Kompleks Abu Bakar', lantai: 'Lantai 1', keterangan: 'Sesuai denah dokumen' },
  { kelas: '6', tingkat: 6, namaRuang: 'Musholla', lantai: 'Lantai 1', keterangan: 'Sesuai denah dokumen' },
];

export interface TataTertibItem {
  subjek: 'Pengajar' | 'Musrif/Wali Kelas' | 'Santri';
  kategori: 'Kewajiban' | 'Larangan' | 'Sanksi' | 'Aturan Tambahan';
  pasalBagian?: string;
  nomor?: number;
  ketentuan: string;
}

export const TATA_TERTIB_DATA: TataTertibItem[] = [
  // Pengajar
  { subjek: 'Pengajar', kategori: 'Kewajiban', pasalBagian: 'Umum', nomor: 1, ketentuan: 'Mendidik dan mengajar siswa.' },
  { subjek: 'Pengajar', kategori: 'Kewajiban', pasalBagian: 'Umum', nomor: 2, ketentuan: 'Mengatur ketertiban dan kedisiplinan dalam ruang belajar.' },
  { subjek: 'Pengajar', kategori: 'Kewajiban', pasalBagian: 'Umum', nomor: 3, ketentuan: 'Mengawasi kebersihan dan kedisiplinan siswa.' },
  { subjek: 'Pengajar', kategori: 'Kewajiban', pasalBagian: 'Umum', nomor: 4, ketentuan: "Berusaha meningkatkan kemampuan siswa, terutama dalam menghafal dan muroja'ah (mengulangi) pelajaran yang telah lewat." },
  { subjek: 'Pengajar', kategori: 'Kewajiban', pasalBagian: 'Umum', nomor: 5, ketentuan: 'Mengajarkan materi yang telah ditetapkan dalam 2 semester.' },
  { subjek: 'Pengajar', kategori: 'Kewajiban', pasalBagian: 'Akan Mengajar', nomor: 1, ketentuan: 'Mempersiapkan pelajaran yang akan diajarkan.' },
  { subjek: 'Pengajar', kategori: 'Kewajiban', pasalBagian: 'Akan Mengajar', nomor: 2, ketentuan: "Berpakaian sopan, syar'an wa 'adatan." },
  { subjek: 'Pengajar', kategori: 'Kewajiban', pasalBagian: 'Akan Mengajar', nomor: 3, ketentuan: 'Datang tepat waktu di ruang belajar.' },
  { subjek: 'Pengajar', kategori: 'Kewajiban', pasalBagian: 'Akan Mengajar', nomor: 4, ketentuan: 'Bermusyawarah dengan sesama pengajar dan ustaz senior guna menyeragamkan makna serta pemahaman materi yang diajarkan.' },
  { subjek: 'Pengajar', kategori: 'Kewajiban', pasalBagian: 'Di Dalam Kelas', nomor: 1, ketentuan: 'Membubuhkan tanda tangan dalam absensi pengajar.' },
  { subjek: 'Pengajar', kategori: 'Kewajiban', pasalBagian: 'Di Dalam Kelas', nomor: 2, ketentuan: 'Meneliti absen siswa dan sekali tempo mengabsennya.' },
  { subjek: 'Pengajar', kategori: 'Kewajiban', pasalBagian: 'Di Dalam Kelas', nomor: 3, ketentuan: 'Berlaku adil terhadap semua siswa.' },
  { subjek: 'Pengajar', kategori: 'Kewajiban', pasalBagian: 'Di Dalam Kelas', nomor: 4, ketentuan: 'Berbicara sopan dan santun.' },
  { subjek: 'Pengajar', kategori: 'Kewajiban', pasalBagian: 'Di Dalam Kelas', nomor: 5, ketentuan: 'Menyampaikan pelajaran.' },
  { subjek: 'Pengajar', kategori: 'Kewajiban', pasalBagian: 'Di Dalam Kelas', nomor: 6, ketentuan: 'Mengawasi dan mendisiplinkan siswa di ruang belajar.' },
  { subjek: 'Pengajar', kategori: 'Kewajiban', pasalBagian: 'Di Dalam Kelas', nomor: 7, ketentuan: 'Berada dalam ruangan belajar selama jam pelajaran berlangsung.' },
  { subjek: 'Pengajar', kategori: 'Kewajiban', pasalBagian: 'Di Luar Ruang Belajar', nomor: 1, ketentuan: 'Menegur dan menindak dengan bijak pada siswa yang melakukan pelanggaran.' },
  { subjek: 'Pengajar', kategori: 'Kewajiban', pasalBagian: 'Di Luar Ruang Belajar', nomor: 2, ketentuan: 'Menjadi contoh dan tauladan dalam segala hal kebaikan.' },
  { subjek: 'Pengajar', kategori: 'Kewajiban', pasalBagian: 'Di Luar Ruang Belajar', nomor: 3, ketentuan: 'Bila tidak mengajar/udzur, sehari sebelumnya harus memberitahukan kepada pengurus madrasah.' },
  { subjek: 'Pengajar', kategori: 'Larangan', nomor: 1, ketentuan: 'Mengubah kurikulum pelajaran.' },
  { subjek: 'Pengajar', kategori: 'Larangan', nomor: 2, ketentuan: 'Memberikan keterangan yang tidak dapat dipahami oleh siswa.' },
  { subjek: 'Pengajar', kategori: 'Larangan', nomor: 3, ketentuan: 'Melakukan sesuatu yang dapat merendahkan kehormatan.' },
  { subjek: 'Pengajar', kategori: 'Larangan', nomor: 4, ketentuan: 'Bergurau/mbanyol terutama dengan siswa.' },
  { subjek: 'Pengajar', kategori: 'Larangan', nomor: 5, ketentuan: 'Pulang sebelum waktunya.' },
  { subjek: 'Pengajar', kategori: 'Sanksi', ketentuan: 'Pengajar yang tidak mematuhi tata tertib ini, wajib tunduk atas kebijakan Madrasah.' },

  // Musrif / Wali Kelas
  { subjek: 'Musrif/Wali Kelas', kategori: 'Kewajiban', pasalBagian: 'Umum', nomor: 1, ketentuan: 'Me-manage kelas baik dari segi teknik edukatif maupun administratif.' },
  { subjek: 'Musrif/Wali Kelas', kategori: 'Kewajiban', pasalBagian: 'Umum', nomor: 2, ketentuan: 'Memantau sekaligus melaporkan keadaan kelas kepada kepala madrasah.' },
  { subjek: 'Musrif/Wali Kelas', kategori: 'Kewajiban', pasalBagian: 'Umum', nomor: 3, ketentuan: 'Mengetahui jumlah anak didik dan nama-namanya.' },
  { subjek: 'Musrif/Wali Kelas', kategori: 'Kewajiban', pasalBagian: 'Umum', nomor: 4, ketentuan: 'Ikut bertanggung jawab atas kemajuan dan kemunduran kelasnya.' },
  { subjek: 'Musrif/Wali Kelas', kategori: 'Kewajiban', pasalBagian: 'Di Dalam Kelas', nomor: 1, ketentuan: 'Mengadakan pengawasan absensi siswanya.' },
  { subjek: 'Musrif/Wali Kelas', kategori: 'Kewajiban', pasalBagian: 'Di Dalam Kelas', nomor: 2, ketentuan: 'Ikut memberikan bimbingan dan motivasi kepada siswanya.' },
  { subjek: 'Musrif/Wali Kelas', kategori: 'Kewajiban', pasalBagian: 'Di Dalam Kelas', nomor: 3, ketentuan: 'Memasuki ruangan belajar 15 menit sebelum KBM (lalaran).' },
  { subjek: 'Musrif/Wali Kelas', kategori: 'Kewajiban', pasalBagian: 'Di Dalam Kelas', nomor: 4, ketentuan: 'Mengadakan lalaran bersama siswanya.' },
  { subjek: 'Musrif/Wali Kelas', kategori: 'Kewajiban', pasalBagian: 'Di Luar Kelas', nomor: 1, ketentuan: 'Menjadi penyemak hafalan setoran Takhassus untuk anak didiknya.' },
  { subjek: 'Musrif/Wali Kelas', kategori: 'Kewajiban', pasalBagian: 'Di Luar Kelas', nomor: 2, ketentuan: 'Mengetahui masalah-masalah anak didiknya (masalah pelajaran atau sosial siswanya).' },
  { subjek: 'Musrif/Wali Kelas', kategori: 'Kewajiban', pasalBagian: 'Di Luar Kelas', nomor: 3, ketentuan: 'Mengadakan setoran mingguan (per minggu 7 bait).' },
  { subjek: 'Musrif/Wali Kelas', kategori: 'Kewajiban', pasalBagian: 'Di Luar Kelas', nomor: 4, ketentuan: 'Mengisi daftar nilai atau buku legger.' },
  { subjek: 'Musrif/Wali Kelas', kategori: 'Kewajiban', pasalBagian: 'Di Luar Kelas', nomor: 5, ketentuan: 'Mengisi dan membagikan raport.' },
  { subjek: 'Musrif/Wali Kelas', kategori: 'Kewajiban', pasalBagian: 'Di Luar Kelas', nomor: 6, ketentuan: 'Mempertimbangkan kenaikan kelas dan menetapkan nilai kelakuan dan kedisiplinan siswa.' },
  { subjek: 'Musrif/Wali Kelas', kategori: 'Larangan', nomor: 1, ketentuan: 'Menyalahgunakan jabatan untuk kepentingan pribadi atau golongan.' },
  { subjek: 'Musrif/Wali Kelas', kategori: 'Larangan', nomor: 2, ketentuan: 'Bersifat pilih kasih atau diskriminatif kepada santri.' },
  { subjek: 'Musrif/Wali Kelas', kategori: 'Larangan', nomor: 3, ketentuan: 'Mengabaikan tugas pembinaan, pendampingan dan pemantauan perkembangan santri.' },
  { subjek: 'Musrif/Wali Kelas', kategori: 'Larangan', nomor: 4, ketentuan: 'Menyebarluaskan data kepada pihak yang tidak berkepentingan.' },
  { subjek: 'Musrif/Wali Kelas', kategori: 'Sanksi', ketentuan: 'Musrif yang tidak mematuhi tata tertib ini, wajib tunduk atas kebijakan Madrasah.' },

  // Santri
  { subjek: 'Santri', kategori: 'Kewajiban', pasalBagian: 'Akan Masuk Kelas', nomor: 1, ketentuan: "Berpakaian sopan, syar'an wa 'adatan." },
  { subjek: 'Santri', kategori: 'Kewajiban', pasalBagian: 'Akan Masuk Kelas', nomor: 2, ketentuan: 'Membawa kitab dan buku catatan sesuai dengan jadwal pelajaran yang sudah ditentukan.' },
  { subjek: 'Santri', kategori: 'Kewajiban', pasalBagian: 'Akan Masuk Kelas', nomor: 3, ketentuan: 'Menyiapkan dan membersihkan ruang kelas, baik sebelum atau sesudah kegiatan belajar mengajar dilaksanakan.' },
  { subjek: 'Santri', kategori: 'Kewajiban', pasalBagian: 'Akan Masuk Kelas', nomor: 4, ketentuan: 'Sudah berada di kelas masing-masing paling lambat 15 menit sebelum Kegiatan Belajar Mengajar dimulai.' },
  { subjek: 'Santri', kategori: 'Kewajiban', pasalBagian: 'Di Dalam Kelas', nomor: 1, ketentuan: 'Mengikuti lalaran harian yang dipimpin oleh Mushrif.' },
  { subjek: 'Santri', kategori: 'Kewajiban', pasalBagian: 'Di Dalam Kelas', nomor: 2, ketentuan: 'Mengikuti pelajaran dengan penuh konsentrasi, semangat dan tidak bermain-main saat jam pelajaran sedang berlangsung.' },
  { subjek: 'Santri', kategori: 'Kewajiban', pasalBagian: 'Di Dalam Kelas', nomor: 3, ketentuan: 'Bersikap sopan dan santun terhadap semua guru dan teman sekelas.' },
  { subjek: 'Santri', kategori: 'Kewajiban', pasalBagian: 'Di Dalam Kelas', nomor: 4, ketentuan: 'Patuh dan bersungguh-sungguh dalam mengerjakan tugas yang diberikan oleh para guru.' },
  { subjek: 'Santri', kategori: 'Kewajiban', pasalBagian: 'Di Dalam Kelas', nomor: 5, ketentuan: 'Selalu izin kepada guru ketika akan keluar dan masuk kelas.' },
  { subjek: 'Santri', kategori: 'Kewajiban', pasalBagian: 'Di Dalam Kelas', nomor: 6, ketentuan: 'Menjaga kebersihan lingkungan kelas dan membuang sampah pada tempatnya.' },
  { subjek: 'Santri', kategori: 'Kewajiban', pasalBagian: 'Di Dalam Kelas', nomor: 7, ketentuan: 'Harus izin ketika memiliki udzur/halangan (sakit, pulang, dsb), dengan menyertakan Surat Izin untuk kemudian diserahkan kepada guru pengajar.' },
  { subjek: 'Santri', kategori: 'Kewajiban', pasalBagian: 'Di Luar Kelas', nomor: 1, ketentuan: 'Menjaga nama baik Madrasah dan Pondok Pesantren, baik di dalam maupun di luar.' },
  { subjek: 'Santri', kategori: 'Kewajiban', pasalBagian: 'Di Luar Kelas', nomor: 2, ketentuan: 'Menghormati pengajar, buku dan kitab-kitabnya.' },
  { subjek: 'Santri', kategori: 'Kewajiban', pasalBagian: 'Di Luar Kelas', nomor: 3, ketentuan: 'Berbudi baik dan sopan, haliyah dan maqoliyah.' },
  { subjek: 'Santri', kategori: 'Kewajiban', pasalBagian: 'Di Luar Kelas', nomor: 4, ketentuan: "Sholat berjama'ah di mushola dengan berpakaian sopan syar'an wa 'adatan." },
  { subjek: 'Santri', kategori: 'Kewajiban', pasalBagian: 'Di Luar Kelas', nomor: 5, ketentuan: 'Mengaji sesuai dengan martabatnya.' },
  { subjek: 'Santri', kategori: 'Kewajiban', pasalBagian: 'Di Luar Kelas', nomor: 6, ketentuan: 'Mematuhi segala ketentuan administrasi.' },
  { subjek: 'Santri', kategori: 'Kewajiban', pasalBagian: 'Di Luar Kelas', nomor: 7, ketentuan: 'Meminta izin kepada sekretaris madrasah sewaktu tidak dapat mengikuti diniyah.' },
  { subjek: 'Santri', kategori: 'Larangan', nomor: 1, ketentuan: 'Terlambat masuk ruang kelas.' },
  { subjek: 'Santri', kategori: 'Larangan', nomor: 2, ketentuan: 'Gaduh/bergurau pada saat Kegiatan Belajar Mengajar berlangsung.' },
  { subjek: 'Santri', kategori: 'Larangan', nomor: 3, ketentuan: 'Duduk membelakangi guru atau duduk menjauhi guru.' },
  { subjek: 'Santri', kategori: 'Larangan', nomor: 4, ketentuan: 'Keluar masuk ruang kelas tanpa seizin guru.' },
  { subjek: 'Santri', kategori: 'Larangan', nomor: 5, ketentuan: 'Membawa novel, komik, dan sejenisnya ke dalam kelas, serta membuang sampah sembarangan.' },
  { subjek: 'Santri', kategori: 'Larangan', nomor: 6, ketentuan: 'Meninggalkan kelas sebelum kegiatan belajar mengajar selesai.' },
  { subjek: 'Santri', kategori: 'Larangan', nomor: 7, ketentuan: 'Merusak fasilitas madrasah (papan tulis, meja, kursi, dampar, dsb).' },
  { subjek: 'Santri', kategori: 'Larangan', nomor: 8, ketentuan: 'Tidak masuk diniyah tanpa keterangan (Alpha) melebihi batas yang sudah ditetapkan oleh Madrasah, yaitu 15 hari selama 1 semester.' },
  { subjek: 'Santri', kategori: 'Sanksi', nomor: 1, ketentuan: 'Peringatan lisan.' },
  { subjek: 'Santri', kategori: 'Sanksi', nomor: 2, ketentuan: 'Peringatan tertulis.' },
  { subjek: 'Santri', kategori: 'Sanksi', nomor: 3, ketentuan: 'Pemanggilan orang tua.' },
  { subjek: 'Santri', kategori: 'Sanksi', nomor: 4, ketentuan: 'Skorsing / tidak naik kelas.' },
  { subjek: 'Santri', kategori: 'Aturan Tambahan', nomor: 1, ketentuan: 'Kedisiplinan sebagai syarat kenaikan kelas.' },
  { subjek: 'Santri', kategori: 'Aturan Tambahan', nomor: 2, ketentuan: 'Hal-hal yang belum termaktub dalam tata tertib ini akan diatur kemudian.' },
];

export interface SilabusItem {
  id: string;
  kelas: string;
  mataPelajaran: string;
  semester: 'Ganjil' | 'Genap' | 'Ganjil & Genap';
  sumberBelajar: string;
  materi: string;
  kompetensiUmum: string;
  indikatorPencapaian: string;
  targetPembelajaran: string;
  metodePembelajaran: string;
}

// Data Silabus 1 sampai 6 diambil langsung dari Silabus_Target_Pembelajaran_Kelas_1_sampai_6_AI_Studio.csv
// ALOKASI WAKTU DIBUANG / TIDAK DITAMPILKAN SESUAI MANDAT
export const SILABUS_DATA_1_SAMPAI_6: SilabusItem[] = [
  // Kelas 1
  {
    id: 's-1-1',
    kelas: '1',
    mataPelajaran: 'Fiqih',
    semester: 'Ganjil',
    sumberBelajar: 'فصلاتن',
    materi: 'مقدمة',
    kompetensiUmum: 'Memahami isi muqodimah kitab Fasholatan beserta pengarangnya',
    indikatorPencapaian: 'Memahami isi muqodimah kitab Fasholatan beserta pengarangnya',
    targetPembelajaran: 'Memahami isi muqodimah kitab Fasholatan beserta pengarangnya',
    metodePembelajaran: 'Klasikal',
  },
  {
    id: 's-1-2',
    kelas: '1',
    mataPelajaran: 'Fiqih',
    semester: 'Ganjil',
    sumberBelajar: 'فصلاتن',
    materi: 'فصل في لأذان ولإقامة',
    kompetensiUmum: 'Memahami lafadz adzan, jawaban adzan, doa setelah adzan, dan lafadz iqomah',
    indikatorPencapaian: 'Mampu melafadzkan adzan, menjawab adzan, doa setelah adzan, dan iqomah secara tertib',
    targetPembelajaran: 'Menguasai praktik adzan dan iqomah beserta doanya dengan tartil',
    metodePembelajaran: 'Klasikal',
  },
  {
    id: 's-1-3',
    kelas: '1',
    mataPelajaran: 'Fiqih',
    semester: 'Ganjil',
    sumberBelajar: 'فصلاتن',
    materi: 'فصل في الوضوء',
    kompetensiUmum: 'Memahami hukum, rukun, sunnah, doa, dan pembatal wudhu',
    indikatorPencapaian: 'Menjelaskan rukun wudhu, mempraktikkan wudhu secara runtut dan doa sesudahnya',
    targetPembelajaran: 'Praktik bersuci wudhu secara sempurna dan mandiri',
    metodePembelajaran: 'Klasikal',
  },
  {
    id: 's-1-4',
    kelas: '1',
    mataPelajaran: 'Fiqih',
    semester: 'Ganjil',
    sumberBelajar: 'فصلاتن',
    materi: 'فصل في للصلاة وأذكارها',
    kompetensiUmum: 'Memahami syarat, rukun, anjuran salat, niat 5 waktu, bacaan takbir hingga salam dan doa qunut',
    indikatorPencapaian: 'Menghafal bacaan shalat dari ruku, sujud, tahiyat, doa qunut hingga wiridan',
    targetPembelajaran: 'Menguasai tata cara shalat fardhu secara amaliyah dan qauliyah',
    metodePembelajaran: 'Klasikal',
  },
  {
    id: 's-1-5',
    kelas: '1',
    mataPelajaran: 'Shorof',
    semester: 'Ganjil',
    sumberBelajar: 'الأمثلة التّصريفية',
    materi: 'مقدمة',
    kompetensiUmum: 'Memahami definisi Shorof, Bina’, Sighat, Wazan dan Mauzun, serta Tashrif Istilahi',
    indikatorPencapaian: 'Siswa dapat menjelaskan pengertian Shorof, Bina’, Sighot, dan Wazan Mauzun beserta contohnya',
    targetPembelajaran: 'Memahami dasar-dasar ilmu shorof dan kaidah timbangan kalimat Arab',
    metodePembelajaran: 'Klasikal',
  },
  {
    id: 's-1-6',
    kelas: '1',
    mataPelajaran: 'Shorof',
    semester: 'Ganjil',
    sumberBelajar: 'الأمثلة التّصريفية',
    materi: 'تصرف الإصتلاح ثلاث مجرّد',
    kompetensiUmum: 'Memahami Tashrif Istilahi Tsulatsi Mujarrod Bab 1 sampai Bab 6',
    indikatorPencapaian: 'Siswa dapat mempraktikkan & menjelaskan Tashrif Istilahi Bab 1-Bab 6 serta membedakan Wazan dan Mauzun',
    targetPembelajaran: 'Hafal lancar tashrifan tsulatsi mujarrod 6 bab',
    metodePembelajaran: 'Klasikal',
  },
  {
    id: 's-1-7',
    kelas: '1',
    mataPelajaran: 'Tauhid',
    semester: 'Ganjil',
    sumberBelajar: 'عقيدة العوام',
    materi: 'مقدمة علم نظم عقيدة العوام بيت ١-٤',
    kompetensiUmum: 'Memahami isi muqaddimah kitab Aqidatul Awwam, Rukun Iman, Rukun Islam, dan sifat Aqa’id',
    indikatorPencapaian: 'Siswa dapat menghafal bait 1-4 dan menyebutkan Rukun Iman, Islam, dan sifat Aqoid',
    targetPembelajaran: 'Menguasai pondasi keimanan Ahlussunnah wal Jama’ah',
    metodePembelajaran: 'Klasikal',
  },
  {
    id: 's-1-8',
    kelas: '1',
    mataPelajaran: 'Tauhid',
    semester: 'Ganjil',
    sumberBelajar: 'عقيدة العوام',
    materi: 'نظم عقيدة العوام بيت ٥-١٤',
    kompetensiUmum: 'Memahami dan menghafal 20 sifat wajib, mustahil, dan jaiz bagi Allah serta sifat Rasul',
    indikatorPencapaian: 'Siswa dapat menjelaskan dan melantunkan bait sifat wajib Allah dan Rasul',
    targetPembelajaran: 'Hafal 20 sifat wajib Allah dan sifat para Rasul',
    metodePembelajaran: 'Klasikal',
  },
  {
    id: 's-1-9',
    kelas: '1',
    mataPelajaran: 'Pegon',
    semester: 'Ganjil',
    sumberBelajar: 'Buku Pintar Pego',
    materi: 'Penulisan Pego & Simbol Makna',
    kompetensiUmum: 'Memahami abjad Arab Pegon, huruf gandeng, simbol makna dan ruju’ pesantren',
    indikatorPencapaian: 'Siswa mampu menulis dan membaca tulisan Pegon serta menerapkan rumus utawi/iku/ing/kerana',
    targetPembelajaran: 'Mampu memberi makna gandul kitab kuning dengan Pegon Jawa/Indonesia',
    metodePembelajaran: 'Klasikal',
  },
  {
    id: 's-1-10',
    kelas: '1',
    mataPelajaran: 'Tajwid',
    semester: 'Ganjil',
    sumberBelajar: 'شفاء الجنان',
    materi: 'باب احكام التنوين و النون الساكنة',
    kompetensiUmum: 'Memahami hukum nun sukun dan tanwin: Idzhar, Idgham bighunnah/bilaghunnah, Iqlab, Ikhfa’',
    indikatorPencapaian: 'Siswa dapat menjelaskan kaidah hukum dan membedakan contoh-contoh dalam ayat Al-Qur’an',
    targetPembelajaran: 'Penerapan fasih bacaan nun sukun dan tanwin saat tilawah',
    metodePembelajaran: 'Klasikal',
  },
  {
    id: 's-1-11',
    kelas: '1',
    mataPelajaran: 'Akhlak',
    semester: 'Genap',
    sumberBelajar: 'الالا',
    materi: 'Bait 1-13 (Syarat Mencari Ilmu & Memilih Teman)',
    kompetensiUmum: 'Memahami 6 syarat menuntut ilmu, memilih sahabat shaleh, dan keutamaan ilmu',
    indikatorPencapaian: 'Siswa mampu melantunkan nadhom Ala La dan menerapkannya dalam pergaulan asrama',
    targetPembelajaran: 'Terbentuknya adab santri pembelajar yang berakhlak mulia',
    metodePembelajaran: 'Klasikal',
  },

  // Kelas 2
  {
    id: 's-2-1',
    kelas: '2',
    mataPelajaran: 'Fiqih',
    semester: 'Ganjil',
    sumberBelajar: 'الغاية و التقريب',
    materi: 'كتاب الطهارة (Pembagian Air, Samak, Siwak, Fardhu & Sunnah Wudhu)',
    kompetensiUmum: 'Siswa dapat memahami macam-macam air pensuci, menyamak kulit bangkai, fardhu & sunnah wudhu, serta istinja’',
    indikatorPencapaian: 'Siswa mampu menyebutkan pembagian air dan mempraktikkan wudhu sesuai matan Taqrib',
    targetPembelajaran: 'Menguasai bab Thaharah dasar kitab matan Al-Ghayah wat Taqrib',
    metodePembelajaran: 'Klasikal',
  },
  {
    id: 's-2-2',
    kelas: '2',
    mataPelajaran: 'Hadits',
    semester: 'Ganjil',
    sumberBelajar: 'الاربعين النووية',
    materi: 'الحديث الاول الى العاشر',
    kompetensiUmum: 'Memahami hadits Niat, Hadits Jibril (Islam, Iman, Ihsan), Rukun Islam, Penciptaan Manusia, Bid’ah, dan Halal-Haram',
    indikatorPencapaian: 'Siswa mampu membaca teks hadits, mengartikan perkata, dan menjelaskan pokok hukum',
    targetPembelajaran: 'Hafal matan hadits 1 sampai 10 dan memahami intisarinya',
    metodePembelajaran: 'Klasikal',
  },
  {
    id: 's-2-3',
    kelas: '2',
    mataPelajaran: 'Nahwu Jurumiyah',
    semester: 'Ganjil',
    sumberBelajar: 'جرومية',
    materi: 'مقدمة علم نحو & باب الكلام & باب الإعراب',
    kompetensiUmum: 'Memahami definisi kalam, pembagian kalimat (isim, fi’il, huruf), dan tanda-tanda i’rab',
    indikatorPencapaian: 'Siswa mampu mengidentifikasi kalimat isim, fi’il, huruf, serta tanda rofa’, nashob, jer, dan jazm',
    targetPembelajaran: 'Menguasai konsep dasar tata bahasa Arab Matan Al-Ajurrumiyyah',
    metodePembelajaran: 'Klasikal',
  },
  {
    id: 's-2-4',
    kelas: '2',
    mataPelajaran: 'Shorof',
    semester: 'Ganjil',
    sumberBelajar: 'الامثلة التصرفية',
    materi: 'الفعل الثلاثي المزيد الرباعي والخماسي',
    kompetensiUmum: 'Memahami wazan tsulatsi mazid ruba’i dan khumasi beserta faedah-faedahnya',
    indikatorPencapaian: 'Siswa dapat mentashrif fa’ala, faa’ala, af’ala, tafaa’ala, tafa’ala, ifta’ala, infa’ala',
    targetPembelajaran: 'Lancar mentashrif bentuk bina’ mazid bi harfin wa biharfaini',
    metodePembelajaran: 'Klasikal',
  },
  {
    id: 's-2-5',
    kelas: '2',
    mataPelajaran: 'Tauhid',
    semester: 'Ganjil',
    sumberBelajar: 'الجواهر الكلمية',
    materi: 'المبحث الاول في الايمان بالله والملائكة والكتب والرسل واليوم الاخر',
    kompetensiUmum: 'Memahami rukun iman, sifat wajib, mustahil, dan jaiz bagi Allah dan para Rasul secara argumentatif',
    indikatorPencapaian: 'Siswa mampu menjelaskan dalil naqli dan aqli sifat Ketuhanan',
    targetPembelajaran: 'Memperkokoh aqidah tauhid dari syubhat aliran sesat',
    metodePembelajaran: 'Klasikal',
  },

  // Kelas 3
  {
    id: 's-3-1',
    kelas: '3',
    mataPelajaran: 'Shorof',
    semester: 'Ganjil',
    sumberBelajar: 'كتاب القواعد الاعلال',
    materi: 'القاعدة الأولى إلى العاشرة',
    kompetensiUmum: 'Menjelaskan kaidah-kaidah I’lal huruf wawu dan ya’ menjadi alif dan pemindahan harakat',
    indikatorPencapaian: 'Siswa mampu mengurai asal kalimat mu’tal dan menjelaskan proses I’lal langkah demi langkah',
    targetPembelajaran: 'Menguasai 19 kaidah I’lal untuk membaca kitab gundul secara teliti',
    metodePembelajaran: 'Klasikal',
  },
  {
    id: 's-3-2',
    kelas: '3',
    mataPelajaran: 'Tauhid',
    semester: 'Ganjil',
    sumberBelajar: 'Kitab Tijan Addarori',
    materi: 'الصفات الواجبات في حق الله تعالى والمستحيلة والجائزة',
    kompetensiUmum: 'Memahami secara mendalam 20 sifat wajib Allah, mustahil, dan jaiz beserta dalil ijmali dan tafshili',
    indikatorPencapaian: 'Siswa mampu membedakan sifat nafsiyah, salbiyah, ma’ani, dan ma’nawiyah',
    targetPembelajaran: 'Khatam pemahaman matan Tijan Ad-Darari fi At-Tauhid',
    metodePembelajaran: 'Klasikal',
  },
  {
    id: 's-3-3',
    kelas: '3',
    mataPelajaran: 'Nahwu',
    semester: 'Ganjil',
    sumberBelajar: 'كتاب الجرومية',
    materi: 'باب منصوبات الأسماء (المفعول به، المصدر، الظرف، الحال، التمييز، الاستثناء)',
    kompetensiUmum: 'Memahami ragam isim yang dibaca nashob dan peran fungsionalnya dalam tarkib kalimat',
    indikatorPencapaian: 'Siswa mampu mentarkib (i’rab) kalimat berkedudukan maf’ul, hal, tamyiz, dan mustatsna',
    targetPembelajaran: 'Mampu menelaah teks bahasa Arab dan memberi harakat secara benar',
    metodePembelajaran: 'Klasikal',
  },
  {
    id: 's-3-4',
    kelas: '3',
    mataPelajaran: 'Hadist',
    semester: 'Ganjil & Genap',
    sumberBelajar: 'الترغيب والترهيب',
    materi: 'كتاب طلب العلم والطهارة والصلاة',
    kompetensiUmum: 'Menjelaskan hadits keutamaan thalabul ilmi, bersuci, shalat fardhu, dan shalat sunnah',
    indikatorPencapaian: 'Siswa mampu memaknai kitab hadits dan mengambil ibrah motivasi ibadah',
    targetPembelajaran: 'Penguatan spiritualitas dan pemahaman fiqih hadits nabawi',
    metodePembelajaran: 'Bandongan',
  },
  {
    id: 's-3-5',
    kelas: '3',
    mataPelajaran: 'Fiqih',
    semester: 'Ganjil & Genap',
    sumberBelajar: 'كتاب الغاية و التقريب',
    materi: 'باب البيوع والربا والرهن والشركات والنكاح',
    kompetensiUmum: 'Memahami hukum transaksi muamalah maliyah, riba, khiyar, sewa menyewa, dan hukum perkawinan',
    indikatorPencapaian: 'Siswa mampu membedakan akad jual beli yang sah dan yang fasid serta rukun nikah',
    targetPembelajaran: 'Menguasai fikih muamalah dan munakahat dasar masyarakat',
    metodePembelajaran: 'Klasikal',
  },

  // Kelas 4
  {
    id: 's-4-1',
    kelas: '4',
    mataPelajaran: 'Fiqih',
    semester: 'Ganjil',
    sumberBelajar: 'كتاب فتح القريب',
    materi: 'مقدمة & كتاب أحكام الطهارة & كتاب أحكام الصلاة',
    kompetensiUmum: 'Menjelaskan mabadi’ asyrah ilmu fiqih dan syarah matan Taqrib bab thaharah dan shalat',
    indikatorPencapaian: 'Siswa dapat membaca dan menguraikan redaksi syarah Fathul Qarib secara gramatikal dan fikih',
    targetPembelajaran: 'Mampu muthala’ah mandiri kitab Fathul Qarib Al-Mujib',
    metodePembelajaran: 'Bandongan',
  },
  {
    id: 's-4-2',
    kelas: '4',
    mataPelajaran: 'Shorof',
    semester: 'Ganjil',
    sumberBelajar: 'كتاب القواعد الصرفية',
    materi: 'أبنية الأسماء والأفعال والمضاعف والمعتل والمهموز',
    kompetensiUmum: 'Memahami konstruksi kalimat isim dan fi’il ditinjau dari jenis bina’ dan kaidah sharaf lanjutan',
    indikatorPencapaian: 'Siswa dapat mengidentifikasi bina’ ajwaf, naqish, lafif maqrun, lafif mafruq',
    targetPembelajaran: 'Keahlian morfologi bahasa Arab tingkat menengah',
    metodePembelajaran: 'Klasikal',
  },
  {
    id: 's-4-3',
    kelas: '4',
    mataPelajaran: 'Hadist Ahkam',
    semester: 'Ganjil & Genap',
    sumberBelajar: 'كتاب الترغيب والترهيب',
    materi: 'كتاب البيوع والفرائض والنكاح والحدود',
    kompetensiUmum: 'Memahami hadits-hadits hukum terkait akad muamalah, warits, nikah, dan jinayat',
    indikatorPencapaian: 'Siswa dapat menjelaskan dalil hadits yang melandasi fatwa fiqih',
    targetPembelajaran: 'Memadukan keilmuan fiqih madzhab dengan hadits sumber hukum',
    metodePembelajaran: 'Bandongan: Memaknai kitab dan penyampaian materi',
  },
  {
    id: 's-4-4',
    kelas: '4',
    mataPelajaran: 'Nahwu',
    semester: 'Ganjil & Genap',
    sumberBelajar: 'كتاب العمريطى',
    materi: 'المقدمة & باب الكلام & الإعراب & العلامات & المعربات & الأفعال',
    kompetensiUmum: 'Menghafal dan memahami nadhom Imrithi karya Syaikh Syarafuddin Al-Imrithi',
    indikatorPencapaian: 'Siswa mampu melantunkan bait-bait nadhom dan mengaplikasikannya pada teks Arab gundul',
    targetPembelajaran: 'Hafal dan faham nadhom Imrithi bab kalam sampai marfu’atil asma’',
    metodePembelajaran: 'Klasikal',
  },
  {
    id: 's-4-5',
    kelas: '4',
    mataPelajaran: 'Tauhid',
    semester: 'Ganjil & Genap',
    sumberBelajar: 'كتاب فتح المجيد',
    materi: 'مقدمة & صفات وجب لحق تعالى (Wujud, Qidam, Baqo’, Mukholafah lil Hawadits)',
    kompetensiUmum: 'Menjelaskan Mabadi’ Asyrah kitab Fathul Majid dan hakikat sifat salbiyah serta ma’ani',
    indikatorPencapaian: 'Siswa mampu menguraikan ta’alluq sifat dan membantah faham ilhad/ateisme',
    targetPembelajaran: 'Kematangan teologi Asy’ariyah dan Maturidiyah',
    metodePembelajaran: 'Klasikal',
  },

  // Kelas 5
  {
    id: 's-5-1',
    kelas: '5',
    mataPelajaran: 'Aswaja',
    semester: 'Ganjil',
    sumberBelajar: 'حجّة أهل السنّة و الجماعة',
    materi: 'مقدمة & amalan mengirim pahala mayit, shalat sunnah qabliyah jum’at, talqin, dan tarawih 20 rakaat',
    kompetensiUmum: 'Memahami dalil-dalil amaliyah Ahlussunnah wal Jama’ah An-Nahdliyyah karya KH. Ali Ma’shum',
    indikatorPencapaian: 'Siswa mampu menjelaskan argumentasi hadits dan pendapat ulama 4 madzhab terkait tradisi amaliyah NU',
    targetPembelajaran: 'Mencetak kader santri berwawasan Aswaja kokoh dan toleran',
    metodePembelajaran: 'Memaknai kitab & penyampaian materi',
  },
  {
    id: 's-5-2',
    kelas: '5',
    mataPelajaran: 'Fiqih',
    semester: 'Ganjil & Genap',
    sumberBelajar: 'Kitab Fathul Qarib',
    materi: 'Kitab Jual Beli, Riba, Khiyar, Rahn, Faraidh, Nikah, Mahar, Talaq, Ruju’, Iddah, Jinayah',
    kompetensiUmum: 'Mendalami syarah Fathul Qarib secara komprehensif pada bab Muamalah dan Munakahat lanjutan',
    indikatorPencapaian: 'Siswa mampu menyelesaikan studi kasus mawaris (faraidh) dan hukum keluarga Islam',
    targetPembelajaran: 'Menguasai fikih praktis keumatan dan literasi kitab kuning tingkat atas',
    metodePembelajaran: 'Memaknai kitab & penyampaian materi',
  },
  {
    id: 's-5-3',
    kelas: '5',
    mataPelajaran: 'Nahwu',
    semester: 'Ganjil & Genap',
    sumberBelajar: 'العمريطي',
    materi: 'باب المنصوبات والمخفوضات والإضافة وخاتمة',
    kompetensiUmum: 'Menuntaskan nadhom Imrithi bab manshubat, makhfudhat, dan idhafah',
    indikatorPencapaian: 'Siswa mampu melalarkan nadhom secara fasih dan mentarkib susunan idhafah dan maf’ul',
    targetPembelajaran: 'Khatam dan hafal nadhom Imrithi secara tuntas',
    metodePembelajaran: 'Memaknai kitab & penyampaian materi',
  },
  {
    id: 's-5-4',
    kelas: '5',
    mataPelajaran: 'Shorof',
    semester: 'Ganjil',
    sumberBelajar: 'قواعد الصرفية',
    materi: 'الفعل الماضي المضاعف المقترن بضمير الرفع & صنت وبعت & جموع التكسير',
    kompetensiUmum: 'Memahami I’lal tingkat tinggi dan kaidah wazan jamak taksir dalam bahasa Arab',
    indikatorPencapaian: 'Siswa dapat menjelaskan pembentukan jamak taksir qillah dan katsrah beserta wazannya',
    targetPembelajaran: 'Menguasai pembentukan kata bahasa Arab tingkat tinggi',
    metodePembelajaran: 'Memaknai kitab & praktek',
  },
  {
    id: 's-5-5',
    kelas: '5',
    mataPelajaran: 'Tauhid',
    semester: 'Ganjil & Genap',
    sumberBelajar: 'فتح المجيد',
    materi: 'صفات المعاني (القدرة، الإرادة، العلم، الحياة، السمع، البصر، الكلام) والصفات المعنوية',
    kompetensiUmum: 'Memahami sifat ma’ani dan sifat ma’nawiyah serta dalil aqli dan naqlinya',
    indikatorPencapaian: 'Siswa mampu menerangkan konsekuensi logis dari sifat ma’ani Allah SWT',
    targetPembelajaran: 'Mencapai derajat keimanan berlandaskan dalil burhani',
    metodePembelajaran: 'Memaknai kitab & penyampaian materi',
  },

  // Kelas 6
  {
    id: 's-6-1',
    kelas: '6',
    mataPelajaran: 'Fiqih - Bagian I',
    semester: 'Ganjil',
    sumberBelajar: 'Kitab Fathul Qarib',
    materi: 'كتاب أحكام البيوع والفرائض والوصايا وكتاب أحكام النكاح وما يتعلق به',
    kompetensiUmum: 'Memahami hukum-hukum transaksi muamalah, pembagian waris faraidl, wasiat, dan perkawinan',
    indikatorPencapaian: 'Dapat menyebutkan hukum dan ketentuan syarah matan secara fasih dan terperinci',
    targetPembelajaran: 'Tuntas menguasai bab muamalah dan munakahat tingkat akhir',
    metodePembelajaran: 'Klasikal & Musyawarah',
  },
  {
    id: 's-6-2',
    kelas: '6',
    mataPelajaran: 'Fiqih - Bagian II',
    semester: 'Ganjil & Genap',
    sumberBelajar: 'فتح القريب',
    materi: 'كتاب أحكام الحدود، الجنايات، الصيد والذبائح، الجهاد، الأقضية والشهادات، والعتق',
    kompetensiUmum: 'Memahami hukum pidana Islam (jinayat & hudud), tata cara peradilan, persaksian hakim, dan perburuan',
    indikatorPencapaian: 'Siswa mampu menjelaskan 15 syarat qadhi, kriteria saksi adil, dan hukum-hukum had',
    targetPembelajaran: 'Khatam kitab Fathul Qarib tingkat akhir (kelas 6)',
    metodePembelajaran: 'Memaknai kitab & penyampaian materi',
  },
  {
    id: 's-6-3',
    kelas: '6',
    mataPelajaran: 'Ke-NU-an',
    semester: 'Ganjil & Genap',
    sumberBelajar: 'حجة اهل السنة والجماعة',
    materi: 'زيارة القبور، نعيم القبر وعذابه، زيارة الرسول وشد الرحال، والتوسل بالأنبياء والصالحين',
    kompetensiUmum: 'Memahami dalil-dalil ziarah kubur, tawasul, syafa’at, dan kekhususan makam Nabi SAW',
    indikatorPencapaian: 'Siswa mampu memaparkan dalil dari hadits shahih dan atsar sahabat tentang kebolehan tawasul dan ziarah kubur',
    targetPembelajaran: 'Kesiapan menjadi da’i dan penjaga aqidah Ahlussunnah wal Jama’ah di masyarakat',
    metodePembelajaran: 'Memaknai kitab & diskusi ilmiah',
  },
  {
    id: 's-6-4',
    kelas: '6',
    mataPelajaran: 'Tauhid',
    semester: 'Ganjil & Genap',
    sumberBelajar: 'كتاب فتح المجيد',
    materi: 'الصفات المعنوية، الجائز في حقه تعالى، صفات الرسل، والإيمان بالسمعيات واليوم الآخر',
    kompetensiUmum: 'Memahami sifat jaiz Allah, sifat wajib Rasul (Shiddiq, Amanah, Tabligh, Fathonah), dan hal gaib (ba’ats, hisab, mizan, shirath, surga, neraka)',
    indikatorPencapaian: 'Siswa mampu menjabarkan makna syahadat dan aqoid 50 secara lengkap',
    targetPembelajaran: 'Khatam kitab Fathul Majid tingkat akhir',
    metodePembelajaran: 'Memaknai kitab & penyampaian materi',
  },
  {
    id: 's-6-5',
    kelas: '6',
    mataPelajaran: 'Tashawwuf',
    semester: 'Ganjil & Genap',
    sumberBelajar: 'ايها الولد',
    materi: 'ثبت الرسالة، الوقت هو الحياة، متى ينفع العلم، عناصر الكمال، اتخذ لك مرشدا، خصال التصوف، ودعاء الإمام الغزالي',
    kompetensiUmum: 'Memahami nasihat-nasihat tasawwuf Hujjatul Islam Imam Al-Ghazali tentang urgensi pengamalan ilmu, tarbiyah ruhani, dan zuhud',
    indikatorPencapaian: 'Siswa mampu menjelaskan perumpamaan ilmu tanpa amal dan syarat mursyid penuntun jalan akhirat',
    targetPembelajaran: 'Terbentuknya kepribadian santri mutafaqqih fiddin yang berhati suci dan berakhlak mulia',
    metodePembelajaran: 'Memaknai kitab & pengijazahan',
  },
];

// Mapel list per kelas based strictly on the silabus kurikulum CSV
export const MAPEL_RESMI_PER_KELAS: Record<string, { ganjil: { mapel: string; kitab: string }[]; genap: { mapel: string; kitab: string }[] }> = {
  '1': {
    ganjil: [
      { mapel: 'Tauhid', kitab: 'عقيدة العوام' },
      { mapel: 'Fiqih', kitab: 'فصلاتن' },
      { mapel: 'Tajwid', kitab: 'شفاء الجنان' },
      { mapel: 'Shorof', kitab: 'الأمثلة التصريفية' },
      { mapel: 'Pegon', kitab: 'Buku Pintar Pego' },
    ],
    genap: [
      { mapel: 'Tauhid', kitab: 'عقيدة العوام' },
      { mapel: 'Fiqih', kitab: 'فصلاتن' },
      { mapel: 'Shorof', kitab: 'الأمثلة التصريفية' },
      { mapel: 'Akhlak', kitab: 'الالا' },
      { mapel: 'Tajwid', kitab: 'شفاء الجنان' },
    ],
  },
  '2': {
    ganjil: [
      { mapel: 'Fiqih', kitab: 'الغاية و التقريب' },
      { mapel: 'Hadits', kitab: 'الاربعين النووية' },
      { mapel: 'Nahwu Jurumiyah', kitab: 'جرومية' },
      { mapel: 'Shorof', kitab: 'الامثلة التصرفية' },
      { mapel: 'Tauhid', kitab: 'الجواهر الكلمية' },
    ],
    genap: [
      { mapel: 'Fiqih', kitab: 'الغاية و التقريب' },
      { mapel: 'Hadits', kitab: 'الاربعين النووية' },
      { mapel: 'Nahwu Jurumiyah', kitab: 'جرومية' },
      { mapel: 'Shorof', kitab: 'الامثلة التصرفية' },
      { mapel: 'Tauhid', kitab: 'الجواهر الكلمية' },
    ],
  },
  '3': {
    ganjil: [
      { mapel: 'Shorof', kitab: 'كتاب القواعد الاعلال' },
      { mapel: 'Tauhid', kitab: 'Kitab Tijan Addarori' },
      { mapel: 'Nahwu', kitab: 'كتاب الجرومية' },
      { mapel: 'Hadist', kitab: 'الترغيب والترهيب' },
      { mapel: 'Fiqih', kitab: 'كتاب الغاية و التقريب' },
    ],
    genap: [
      { mapel: 'Shorof', kitab: 'كتاب القواعد الاعلal' },
      { mapel: 'Tauhid', kitab: 'Kitab Tijan Addarori' },
      { mapel: 'Nahwu', kitab: 'كتاب الجرومية' },
      { mapel: 'Hadist', kitab: 'الترغيب والترهيب' },
      { mapel: 'Fiqih', kitab: 'كتاب الغاية و التقريب' },
    ],
  },
  '4': {
    ganjil: [
      { mapel: 'Fiqih', kitab: 'كتاب فتح القريب' },
      { mapel: 'Shorof', kitab: 'كتاب القواعد الصرفية' },
      { mapel: 'Hadist Ahkam', kitab: 'كتاب الترغيب والترهيب' },
      { mapel: 'Nahwu', kitab: 'كتاب العمريطى' },
      { mapel: 'Tauhid', kitab: 'كتاب فتح المجيد' },
    ],
    genap: [
      { mapel: 'Fiqih', kitab: 'كتاب فتح القريب' },
      { mapel: 'Hadist Ahkam', kitab: 'كتاب الترغيب والترهيب' },
      { mapel: 'Nahwu', kitab: 'كتاب العمريطى' },
      { mapel: 'Tauhid', kitab: 'كتاب فتح المجيد' },
    ],
  },
  '5': {
    ganjil: [
      { mapel: 'Aswaja', kitab: 'حجّة أهل السنّة و الجماعة' },
      { mapel: 'Fiqih', kitab: 'Kitab Fathul Qarib' },
      { mapel: 'Nahwu', kitab: 'العمريطي' },
      { mapel: 'Shorof', kitab: 'قواعد الصرفية' },
      { mapel: 'Tauhid', kitab: 'فتح المجيد' },
    ],
    genap: [
      { mapel: 'Aswaja', kitab: 'حجّة أهل السنّة و الجماعة' },
      { mapel: 'Fiqih', kitab: 'Kitab Fathul Qarib' },
      { mapel: 'Nahwu', kitab: 'العمريطي' },
      { mapel: 'Tauhid', kitab: 'فتح المجيد' },
    ],
  },
  '6': {
    ganjil: [
      { mapel: 'Fiqih', kitab: 'فتح القريب' },
      { mapel: 'Ke-NU-an / Aswaja', kitab: 'حجة اهل السنة والجماعة' },
      { mapel: 'Tauhid', kitab: 'كتاب فتح المجيد' },
      { mapel: 'Tashawwuf', kitab: 'ايها الولد' },
    ],
    genap: [
      { mapel: 'Fiqih', kitab: 'فتح القريب' },
      { mapel: 'Ke-NU-an / Aswaja', kitab: 'حجة اهل السنة والجماعة' },
      { mapel: 'Tauhid', kitab: 'كتاب فتح المجيد' },
      { mapel: 'Tashawwuf', kitab: 'ايها الولد' },
    ],
  },
};
