import {
  UserProfile,
  Santri,
  SesiAbsensi,
  NilaiSiswaItem,
  JadwalPelajaranItem,
  GuruJadwal,
  JadwalSlotItem,
  SilabusItem,
  MateriItem,
  BukuKerjaItem,
  SoalItem,
  NotifikasiItem,
  DokumenPesantrenItem,
  RaportSiswa,
  IjazahSiswa,
} from '../types';

export const PESANTREN_INFO = {
  nama: 'Madrasah Diniyah Takmiliyah Annajiyah 2',
  namaLengkap: 'MADRASAH DINIYAH TAKMILIYAH ANNAJIYAH 2 BAHRUL ULUM TAMBAKBERAS JOMBANG',
  namaPendek: 'MDT. Annajiyah 2',
  lembagaInduk: 'Yayasan Pondok Pesantren Bahrul Ulum Tambakberas Jombang',
  tagline: 'Satu Sistem untuk Pendidikan, Akademik, dan Administrasi Madrasah.',
  nomorStatistik: '510035170012',
  logoUrl: '/logo.png',
  akreditasi: 'A (Unggul) Kemenag RI',
  tahunBerdiri: '2004',
  pimpinan: 'KH. M. Salman Al-Faries, Lc., M.Hi',
  tokohPendiri: 'KH. M. Salman Al-Faries, Lc., M.Hi (Didirikan Tahun 2004)',
  pengasuh: 'KH. M. Salman Al-Faries, Lc., M.Hi',
  sejarah: 'Madrasah Diniyyah An-Najiyah 2 berdiri di lingkungan pesantren dibawah naungan Yayasan Pondok Pesantren Bahrul Ulum Tambakberas Jombang. Berdirinya Madrasah Diniyyah An-Najiyah 2 di lingkungan pesantren berdampak positif terhadap kegiatan belajar dan mengajar, diantaranya dapat mempraktikkan secara langsung pelajaran yang ada pada kegiatan Diniyyah, dengan dibimbing dan dibina oleh Asatidz yang ada di lingkungan pesantren. Didirikannya Madrasah Diniyyah An-Najiyah 2 ini tidak terlepas dari didirikannya Pondok Pesantren An-Najiyah 2 pada tahun 2004 oleh KH. M. Salman Al-Faries melalui dukungan dari guru dan juga keluarga. Guna menjawab kebutuhan masyarakat luas tentang pentingnya ilmu keagamaan dan juga mendidik para santri menjadi muslim yang bertaqwa kepada Allah, berakhlaq mulia, memiliki kecerdasan, keterampilan, dan sehat lahir juga batin sebagai warga negara yang berpancasila. Dengan berjalannya waktu, Pondok Pesantren An-Najiyah 2 secara umum terus mendapatkan kepercayaan besar dari masyarakat luas berkaitan dengan Pendidikan Kepesantrenan. Oleh sebab itu, Pondok Pesantren An-Najiyah 2 secara umum melakukan upaya-upaya perbaikan secara kualitas dan kuantitas, dari bentuk fisik dan juga sistem pendidikan, maupun berupaya mewujudkan pilar-pilar standar nasional pendidikan, dengan harapan Pondok Pesantren An-Najiyah 2 menjadi Pondok yang bisa diandalkan. Dengan bertambahnya banyaknya santri yang ada di Pondok Pesantren An-Najiyah 2 Bahrul Ulum dan dengan adanya dukungan dan saran dari alumni, tokoh agama serta para wali santri agar diadakannya pendalaman dalam pendidikan keagamaan diluar jam sekolah yang lain seperti belajar Al-Qur\'an, Akhlaq, Tauhid, Fiqih, dan sebagainya. Sehingga Pengurus Madrasah membuat suatu program seperti apa yang disarankan oleh para alumni dengan mengadakan Program Pendidikan Madrasah Diniyyah yang bertujuan membentuk generasi muda yang religius dan berakhlaqul karimah.',
  alamat: 'Dsn. Tambakberas RT.004 RW.004, Ds. Tambakrejo, Kec. Jombang, Kab. Jombang, Jawa Timur 61451',
  telepon: '+62 321 861234',
  email: 'sekretariat@annajiyah2.bahrululum.or.id',
  website: 'www.bahrululum.or.id',
  visi: 'Menjadikan Tambakberas sebagai pusat terciptanya santri yang cerdas, berkualitas, mandiri, dan berwawasan berlandaskan Al-Qur’an dan Hadits dengan dasar iman, taqwa, dan Ahlussunah wal Jama’ah',
  misi: [
    'Meningkatkan kualitas santri yang unggul berlandaskan nilai-nilai Al-Qur\'an dan Hadits.',
    'Menumbuhkan generasi muda yang berakhlak mulia melalui pembiasaan akhlaqul karimah.',
    'Mewujudkan kemandirian santri melalui pendidikan terpadu dan pembiasaan hidup mandiri.',
    'Menciptakan iklim pembelajaran yang kondusif, dinamis, dan terarah bagi pengembangan potensi santri.',
    'Membina persaudaraan dan solidaritas antar santri guna mewujudkan ukhuwah Islamiyah.'
  ],
  pancaJiwa: [
    { nama: 'Keikhlasan', makna: 'Bekerja, belajar, dan mengabdi semata-mata lillahi ta\'ala tanpa pamrih keduniaan.' },
    { nama: 'Kesederhanaan', makna: 'Bersahaja dalam bersikap, berpakaian, dan konsumsi, namun berjiwa besar serta berwawasan luas.' },
    { nama: 'Berdikari (Self-Reliance)', makna: 'Mampu mengurus diri sendiri, mandiri secara ekonomi, emosional, dan kepribadian.' },
    { nama: 'Ukhuwah Islamiyah', makna: 'Persaudaraan sesama muslim melampaui sekat kedaerahan, suku bangsa, dan status sosial.' },
    { nama: 'Kebebasan Berpikir', makna: 'Bebas mencari kebenaran dalam koridor syariat dengan pandangan optimis dan terbuka.' }
  ],
  totalSantri: 247,
  totalGuru: 17,
  totalKelas: 12,
  totalHafidz: 247,
};

export const MOCK_USERS: Record<string, UserProfile> = {
  admin: {
    id: 'usr-admin',
    name: 'Ust. Ach. Aldyansyah, S.Pd',
    role: 'admin',
    roleTitle: 'Administrator Utama',
    nipOrNis: 'NIP. 197805122004011002',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    email: 'admin@pesantrenterpadu.sch.id',
    unreadNotifications: 4,
  },
  guru: {
    id: 'usr-guru',
    name: 'Ustadz Ahmad Fauzi, S.Pd.I',
    role: 'guru',
    roleTitle: 'Guru Pengampu / Wali Kelas',
    nipOrNis: 'NIP. 198503142010011008',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    email: 'ahmad.fauzi@pesantrenterpadu.sch.id',
    kelas: '5A',
    unreadNotifications: 3,
  },
  siswa: {
    id: 'usr-siswa',
    name: 'Ahmad Zaki Mubarak',
    role: 'siswa',
    roleTitle: 'Santri Kelas 5A',
    nipOrNis: 'NIS. 202305012',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    email: 'zaki.mubarak@santri.pesantren.id',
    kelas: 'Kelas 5A',
    unreadNotifications: 2,
  },
};

export const MOCK_SANTRI: Santri[] = [
  {
    id: 's-1',
    nis: '202305012',
    nisn: '0087654321',
    nama: 'Ahmad Zaki Mubarak',
    gender: 'L',
    kelas: 'Kelas 5A',
    tahunMasuk: '2023',
    status: 'Aktif',
    tempatLahir: 'Bandung',
    tanggalLahir: '14 Mei 2008',
    namaWali: 'H. Muhammad Ridwan',
    noHpWali: '0812-3456-7890',
    alamat: 'Jl. Dago Asri No. 45, Coblong, Kota Bandung',
    hafalanJuz: 8,
    mutqinSurah: 'Juz 1 s/d Juz 8 & Surah Al-Kahfi',
    akhlakPredikat: 'A (Sangat Baik)',
    foto: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    kehadiranPercent: 98,
    rataRataNilai: 91.5,
    catatanWaliKelas: 'Santri sangat aktif dalam diskusi Bahasa Arab dan berdisiplin tinggi dalam sholat berjamaah 5 waktu di masjid jamik.',
  },
  {
    id: 's-2',
    nis: '202305013',
    nisn: '0087654322',
    nama: 'Muhammad Farhan Al-Habsyi',
    gender: 'L',
    kelas: 'Kelas 5A',
    tahunMasuk: '2023',
    status: 'Aktif',
    tempatLahir: 'Jakarta Selatan',
    tanggalLahir: '21 Agustus 2008',
    namaWali: 'Ir. Faisal Habsyi',
    noHpWali: '0813-8899-7711',
    alamat: 'Jl. Tebet Barat Dalam No. 12, Jakarta Selatan',
    hafalanJuz: 10,
    mutqinSurah: 'Juz 1 s/d Juz 10',
    akhlakPredikat: 'A (Sangat Baik)',
    foto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    kehadiranPercent: 96,
    rataRataNilai: 89.2,
    catatanWaliKelas: 'Kemampuan Nahwu dan Shorof sangat menonjol. Perlu peningkatan ritme hafalan Hadits Arbain.',
  },
  {
    id: 's-3',
    nis: '202305014',
    nisn: '0087654323',
    nama: 'Bilal Abdurrahman',
    gender: 'L',
    kelas: 'Kelas 5A',
    tahunMasuk: '2023',
    status: 'Aktif',
    tempatLahir: 'Tasikmalaya',
    tanggalLahir: '03 November 2008',
    namaWali: 'Drs. H. Dedi Kusnadi',
    noHpWali: '0812-7711-2233',
    alamat: 'Cihideung, Kota Tasikmalaya',
    hafalanJuz: 6,
    mutqinSurah: 'Juz 28 s/d 30, Juz 1 s/d 3',
    akhlakPredikat: 'B (Baik)',
    foto: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    kehadiranPercent: 92,
    rataRataNilai: 84.8,
    catatanWaliKelas: 'Pernah izin sakit 2 hari pekan lalu. Sudah kembali mengikuti jadwal kajian ba\'da Subuh dengan baik.',
  },
  {
    id: 's-4',
    nis: '202305015',
    nisn: '0087654324',
    nama: 'Danish Rayhan Pratama',
    gender: 'L',
    kelas: 'Kelas 5A',
    tahunMasuk: '2023',
    status: 'Aktif',
    tempatLahir: 'Bogor',
    tanggalLahir: '17 Februari 2008',
    namaWali: 'Kurniawan Pratama',
    noHpWali: '0852-1234-9876',
    alamat: 'Ciomas, Kabupaten Bogor',
    hafalanJuz: 7,
    mutqinSurah: 'Juz 1 s/d 7',
    akhlakPredikat: 'A (Sangat Baik)',
    foto: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    kehadiranPercent: 99,
    rataRataNilai: 93.0,
    catatanWaliKelas: 'Juara 1 Musabaqah Qira\'atil Kutub (MQK) tingkat Kabupaten bidang Fathul Qorib.',
  },
  {
    id: 's-5',
    nis: '202305016',
    nisn: '0087654325',
    nama: 'Ziyad Al-Ghifari',
    gender: 'L',
    kelas: 'Kelas 5A',
    tahunMasuk: '2023',
    status: 'Aktif',
    tempatLahir: 'Surabaya',
    tanggalLahir: '29 Juni 2008',
    namaWali: 'H. Lukman Hakim',
    noHpWali: '0811-9988-2244',
    alamat: 'Rungkut Asri, Kota Surabaya',
    hafalanJuz: 9,
    mutqinSurah: 'Juz 1 s/d 9',
    akhlakPredikat: 'A (Sangat Baik)',
    foto: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80',
    kehadiranPercent: 97,
    rataRataNilai: 88.5,
    catatanWaliKelas: 'Khatib dan Imam muda masjid jami pesantren. Sangat santun dan teladan bagi adik kelas.',
  },
  {
    id: 's-6',
    nis: '202305017',
    nisn: '0087654326',
    nama: 'Fatih Khalid Hamizan',
    gender: 'L',
    kelas: 'Kelas 5A',
    tahunMasuk: '2023',
    status: 'Aktif',
    tempatLahir: 'Yogyakarta',
    tanggalLahir: '11 Oktober 2008',
    namaWali: 'Dr. Hamdan Hamizan',
    noHpWali: '0818-4455-6677',
    alamat: 'Kaliurang Km 7, Sleman, D.I. Yogyakarta',
    hafalanJuz: 8,
    mutqinSurah: 'Juz 1 s/d 8',
    akhlakPredikat: 'B (Baik)',
    foto: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80',
    kehadiranPercent: 94,
    rataRataNilai: 86.4,
    catatanWaliKelas: 'Minat tinggi dalam ekstrakurikuler Kaligrafi Khot Naskhi dan Riq\'ah.',
  },
  {
    id: 's-7',
    nis: '202305018',
    nisn: '0087654327',
    nama: 'Salman Al-Farisi',
    gender: 'L',
    kelas: 'Kelas 5B',
    tahunMasuk: '2023',
    status: 'Aktif',
    tempatLahir: 'Semarang',
    tanggalLahir: '05 Januari 2008',
    namaWali: 'H. Mardhianto',
    noHpWali: '0812-9900-1122',
    alamat: 'Banyumanik, Kota Semarang',
    hafalanJuz: 12,
    mutqinSurah: 'Juz 1 s/d 12',
    akhlakPredikat: 'A (Sangat Baik)',
    foto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    kehadiranPercent: 99,
    rataRataNilai: 94.6,
    catatanWaliKelas: 'Santri berprestasi dengan kefasihan makharijul huruf dan hafalan paling lancar di angkatannya.',
  },
  {
    id: 's-8',
    nis: '202305019',
    nisn: '0087654328',
    nama: 'Muhammad Ihsan Kamil',
    gender: 'L',
    kelas: 'Kelas 5B',
    tahunMasuk: '2023',
    status: 'Aktif',
    tempatLahir: 'Solo',
    tanggalLahir: '19 April 2008',
    namaWali: 'H. Suryanto',
    noHpWali: '0813-7722-3344',
    alamat: 'Laweyan, Kota Surakarta',
    hafalanJuz: 9,
    mutqinSurah: 'Juz 1 s/d 9',
    akhlakPredikat: 'A (Sangat Baik)',
    foto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    kehadiranPercent: 97,
    rataRataNilai: 90.1,
    catatanWaliKelas: 'Juara Pidato Bahasa Arab (Khitabah) Pekan Olahraga & Seni Santri (POSPEDA).',
  },
  {
    id: 's-k6-1',
    nis: '202106001',
    nisn: '0067829101',
    nama: 'Muhammad Rayhan Al-Baqir',
    gender: 'L',
    kelas: 'Kelas 6',
    tahunMasuk: '2021',
    status: 'Aktif',
    tempatLahir: 'Jombang',
    tanggalLahir: '10 Mei 2007',
    namaWali: 'H. Abdul Rasyid',
    noHpWali: '0812-3344-5566',
    alamat: 'Jl. Merdeka No. 10, Tambakberas, Jombang',
    hafalanJuz: 10,
    mutqinSurah: 'Juz 1 s/d Juz 10',
    akhlakPredikat: 'A (Sangat Baik)',
    foto: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    kehadiranPercent: 99,
    rataRataNilai: 94.5,
    catatanWaliKelas: 'Calon wisudawan teladan. Telah menyelesaikan kurikulum takmiliyah 6 tahun dengan predikat Mumtaz.',
  },
  {
    id: 's-k6-2',
    nis: '202106002',
    nisn: '0067829102',
    nama: 'Umar Faruq As-Suyuthi',
    gender: 'L',
    kelas: 'Kelas 6',
    tahunMasuk: '2021',
    status: 'Aktif',
    tempatLahir: 'Surabaya',
    tanggalLahir: '14 Agustus 2007',
    namaWali: 'Drs. H. M. Sholihin',
    noHpWali: '0813-4455-8899',
    alamat: 'Ketintang, Kota Surabaya',
    hafalanJuz: 15,
    mutqinSurah: 'Juz 1 s/d Juz 15',
    akhlakPredikat: 'A (Sangat Baik)',
    foto: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    kehadiranPercent: 98,
    rataRataNilai: 93.8,
    catatanWaliKelas: 'Telah lulus seluruh imtihan tahriri dan syafahi kelas 6 dengan hasil sangat memuaskan.',
  }
];

export const INITIAL_ABSENSI_SESSION: SesiAbsensi = {
  id: 'abs-20260906-5a',
  tanggal: '2026-09-06',
  kelas: 'Kelas 5A',
  mataPelajaran: 'Bahasa Arab (Muhadatsah & Nahwu)',
  jamKe: 'Jam Ke-1 & 2 (07.30 - 09.00 WIB)',
  ruang: 'Ruang 3 Ibnu Rusyd',
  guruPengampu: 'Ustadz Ahmad Fauzi, S.Pd.I',
  isCompleted: false, // matches "⚠ Absensi hari ini belum lengkap"
  records: [
    { santriId: 's-1', nama: 'Ahmad Zaki Mubarak', nis: '202305012', status: 'Hadir' },
    { santriId: 's-2', nama: 'Muhammad Farhan Al-Habsyi', nis: '202305013', status: 'Hadir' },
    { santriId: 's-3', nama: 'Bilal Abdurrahman', nis: '202305014', status: 'Izin', keterangan: 'Pemeriksaan di Klinik Pesantren' },
    { santriId: 's-4', nama: 'Danish Rayhan Pratama', nis: '202305015', status: 'Hadir' },
    { santriId: 's-5', nama: 'Ziyad Al-Ghifari', nis: '202305016', status: 'Hadir' },
    { santriId: 's-6', nama: 'Fatih Khalid Hamizan', nis: '202305017', status: 'Hadir' },
  ],
};

export const MOCK_SESI_ABSENSI = INITIAL_ABSENSI_SESSION;

export const INITIAL_NILAI_LIST: NilaiSiswaItem[] = [
  {
    santriId: 's-1',
    nama: 'Ahmad Zaki Mubarak',
    nis: '202305012',
    tugas: 92,
    ulanganHarian: 88,
    uts: 94,
    uas: 90,
    praktik: 95,
    hafalan: 93,
    akhlak: 96,
    kehadiran: 98,
    nilaiAkhir: 93,
    predikat: 'A (Mumtaz)',
    status: 'Lengkap',
  },
  {
    santriId: 's-2',
    nama: 'Muhammad Farhan Al-Habsyi',
    nis: '202305013',
    tugas: 88,
    ulanganHarian: 86,
    uts: 90,
    uas: 89,
    praktik: 92,
    hafalan: 95,
    akhlak: 92,
    kehadiran: 96,
    nilaiAkhir: 91,
    predikat: 'A (Mumtaz)',
    status: 'Lengkap',
  },
  {
    santriId: 's-3',
    nama: 'Bilal Abdurrahman',
    nis: '202305014',
    tugas: 80,
    ulanganHarian: 78,
    uts: 82,
    uas: 84,
    praktik: 85,
    hafalan: 82,
    akhlak: 86,
    kehadiran: 90,
    nilaiAkhir: 83,
    predikat: 'B+ (Jayyid Jiddan)',
    status: 'Lengkap',
  },
  {
    santriId: 's-4',
    nama: 'Danish Rayhan Pratama',
    nis: '202305015',
    tugas: 95,
    ulanganHarian: 92,
    uts: 96,
    uas: 94,
    praktik: 96,
    hafalan: 92,
    akhlak: 95,
    kehadiran: 99,
    nilaiAkhir: 95,
    predikat: 'A (Mumtaz)',
    status: 'Lengkap',
  },
  {
    santriId: 's-5',
    nama: 'Ziyad Al-Ghifari',
    nis: '202305016',
    tugas: 85,
    ulanganHarian: 82,
    uts: 88,
    uas: 87,
    praktik: 90,
    hafalan: 94,
    akhlak: 95,
    kehadiran: 97,
    nilaiAkhir: 89,
    predikat: 'B+ (Jayyid Jiddan)',
    status: 'Lengkap',
  },
  {
    santriId: 's-6',
    nama: 'Fatih Khalid Hamizan',
    nis: '202305017',
    tugas: 82,
    ulanganHarian: 80,
    uts: 84,
    uas: 0, // Belum ujian susulan
    praktik: 86,
    hafalan: 88,
    akhlak: 88,
    kehadiran: 92,
    nilaiAkhir: 74,
    predikat: 'C (Maqbul)',
    status: 'Belum lengkap', // Causes 92% completion banner!
  },
];

export const MOCK_GURU_JADWAL: GuruJadwal[] = [
  { kode: 1, nama: 'Ust. M. Irham S. Pd.I.', warnaBadge: 'bg-red-600 text-white' },
  { kode: 2, nama: 'Ust. Shidqi Fadli', warnaBadge: 'bg-orange-600 text-white' },
  { kode: 3, nama: 'Ust. Abdullah Faqih', warnaBadge: 'bg-amber-500 text-slate-950' },
  { kode: 4, nama: 'Ust. Zainurrohim, M.pd.', warnaBadge: 'bg-yellow-400 text-slate-950' },
  { kode: 5, nama: 'Ust. M. Faza Azkannasr, M.p.d.', warnaBadge: 'bg-lime-500 text-slate-950' },
  { kode: 6, nama: 'Ust. Rois Sekti Aji, S.P.d.', warnaBadge: 'bg-emerald-600 text-white' },
  { kode: 7, nama: 'M. Firjaun Asrof Shiatsi, S.Ag.', warnaBadge: 'bg-cyan-500 text-slate-950' },
  { kode: 8, nama: 'Ust. M. Ilyas, S.Pd.I.', warnaBadge: 'bg-purple-600 text-white' },
  { kode: 9, nama: 'Ust. H. Ahmad Fauzi, Lc.', warnaBadge: 'bg-blue-600 text-white' },
  { kode: 10, nama: 'Ust. K.H. Abdul Wahab', warnaBadge: 'bg-amber-700 text-white' },
  { kode: 11, nama: 'Ust. M. Syaifuddin, S.Pd.I.', warnaBadge: 'bg-cyan-400 text-slate-950' },
  { kode: 12, nama: 'Ust. M. Syukron, S.Pd.', warnaBadge: 'bg-slate-300 text-slate-900' },
  { kode: 13, nama: 'Ust. Khairuddin', warnaBadge: 'bg-amber-600 text-white' },
  { kode: 14, nama: 'Nabiha Ahmad', warnaBadge: 'bg-slate-200 text-slate-800' },
  { kode: 15, nama: 'M. Jalaluddin Al-Hasuni', warnaBadge: 'bg-amber-200 text-amber-950' },
  { kode: 16, nama: 'M. Al-Fatih Pasya', warnaBadge: 'bg-green-500 text-white' },
  { kode: 17, nama: 'Azka Muhammad Satria', warnaBadge: 'bg-fuchsia-500 text-white' },
  { kode: 18, nama: 'Faiz Askiya\'', warnaBadge: 'bg-lime-400 text-slate-950' },
  { kode: 19, nama: 'Naufal Farel Alfaruq', warnaBadge: 'bg-rose-400 text-white' },
  { kode: 20, nama: 'Ust. M. Zulfikar', warnaBadge: 'bg-red-800 text-white' },
  { kode: 21, nama: 'Ust. Ahmad Rifai', warnaBadge: 'bg-slate-100 text-slate-800 border border-slate-300' },
];

export const MOCK_JADWAL_SLOTS: JadwalSlotItem[] = [
  // Jum'at
  { id: 'j-1a-jumat', kelas: '1A', hari: 'Jum\'at', kitab: 'شفاء الجنان', kitabLatin: 'Syifa\'ul Jinan', fanIlmu: 'Tajwid', kodeGuru: 20 },
  { id: 'j-1b-jumat', kelas: '1B', hari: 'Jum\'at', kitab: 'فصلاتن', kitabLatin: 'Fasholatan', fanIlmu: 'Fiqih', kodeGuru: 15 },
  { id: 'j-2a-jumat', kelas: '2A', hari: 'Jum\'at', kitab: 'الامثلة التصريفية', kitabLatin: 'Al-Amtsilah At-Tashrifiyyah', fanIlmu: 'Shorof', kodeGuru: 19 },
  { id: 'j-2b-jumat', kelas: '2B', hari: 'Jum\'at', kitab: 'الاربعين النووى', kitabLatin: 'Al-Arba\'in An-Nawawi', fanIlmu: 'Hadits', kodeGuru: 16 },
  { id: 'j-3a-jumat', kelas: '3A', hari: 'Jum\'at', kitab: 'الترغيب والترهيب', kitabLatin: 'At-Targhib wat-Tarhib', fanIlmu: 'Hadits', kodeGuru: 13 },
  { id: 'j-3b-jumat', kelas: '3B', hari: 'Jum\'at', kitab: 'تيجان الدراري', kitabLatin: 'Tijan Ad-Darari', fanIlmu: 'Tauhid', kodeGuru: 21 },
  { id: 'j-3c-jumat', kelas: '3C', hari: 'Jum\'at', kitab: 'قواعد الإعلال', kitabLatin: 'Qawa\'idul I\'lal', fanIlmu: 'Shorof', kodeGuru: 6 },
  { id: 'j-4a-jumat', kelas: '4A', hari: 'Jum\'at', kitab: 'فتح القريب', kitabLatin: 'Fathul Qorib', fanIlmu: 'Fiqih', kodeGuru: 4 },
  { id: 'j-4b-jumat', kelas: '4B', hari: 'Jum\'at', kitab: 'قواعد الصرفية', kitabLatin: 'Qawa\'idush Shorfiyyah', fanIlmu: 'Shorof', kodeGuru: 8 },
  { id: 'j-5a-jumat', kelas: '5A', hari: 'Jum\'at', kitab: 'فتح القريب', kitabLatin: 'Fathul Qorib', fanIlmu: 'Fiqih', kodeGuru: 11 },
  { id: 'j-5b-jumat', kelas: '5B', hari: 'Jum\'at', kitab: 'فتح المجيد', kitabLatin: 'Fathul Majid', fanIlmu: 'Tauhid', kodeGuru: 12 },
  { id: 'j-6-jumat', kelas: '6', hari: 'Jum\'at', kitab: 'شرح أيها الولد', kitabLatin: 'Syarah Ayyuhal Walad', fanIlmu: 'Tasawwuf', kodeGuru: 3 },

  // Sabtu
  { id: 'j-1a-sabtu', kelas: '1A', hari: 'Sabtu', kitab: 'فصلاتن', kitabLatin: 'Fasholatan', fanIlmu: 'Fiqih', kodeGuru: 15 },
  { id: 'j-1b-sabtu', kelas: '1B', hari: 'Sabtu', kitab: 'عقيدة العوام', kitabLatin: 'Aqidatul Awam', fanIlmu: 'Tauhid', kodeGuru: 18 },
  { id: 'j-2a-sabtu', kelas: '2A', hari: 'Sabtu', kitab: 'جرومية', kitabLatin: 'Jurumiyyah', fanIlmu: 'Nahwu', kodeGuru: 6 },
  { id: 'j-2b-sabtu', kelas: '2B', hari: 'Sabtu', kitab: 'الامثلة التصريفية', kitabLatin: 'Al-Amtsilah At-Tashrifiyyah', fanIlmu: 'Shorof', kodeGuru: 19 },
  { id: 'j-3a-sabtu', kelas: '3A', hari: 'Sabtu', kitab: 'تيجان الدراري', kitabLatin: 'Tijan Ad-Darari', fanIlmu: 'Tauhid', kodeGuru: 21 },
  { id: 'j-3b-sabtu', kelas: '3B', hari: 'Sabtu', kitab: 'تقريب', kitabLatin: 'Taqrib', fanIlmu: 'Fiqih', kodeGuru: 11 },
  { id: 'j-3c-sabtu', kelas: '3C', hari: 'Sabtu', kitab: 'الترغيب والترهيب', kitabLatin: 'At-Targhib wat-Tarhib', fanIlmu: 'Hadist', kodeGuru: 13 },
  { id: 'j-4a-sabtu', kelas: '4A', hari: 'Sabtu', kitab: 'قواعد الصرفية', kitabLatin: 'Qawa\'idush Shorfiyyah', fanIlmu: 'Shorof', kodeGuru: 8 },
  { id: 'j-4b-sabtu', kelas: '4B', hari: 'Sabtu', kitab: 'فتح المجيد', kitabLatin: 'Fathul Majid', fanIlmu: 'Tauhid', kodeGuru: 16 },
  { id: 'j-5a-sabtu', kelas: '5A', hari: 'Sabtu', kitab: 'فتح المجيد', kitabLatin: 'Fathul Majid', fanIlmu: 'Tauhid', kodeGuru: 12 },
  { id: 'j-5b-sabtu', kelas: '5B', hari: 'Sabtu', kitab: 'قواعد الصرفية', kitabLatin: 'Qawa\'idush Shorfiyyah', fanIlmu: 'Shorof', kodeGuru: 5 },
  { id: 'j-6-sabtu', kelas: '6', hari: 'Sabtu', kitab: 'فتح القريب', kitabLatin: 'Fathul Qorib', fanIlmu: 'Baca Kitab', kodeGuru: 10 },

  // Minggu
  { id: 'j-1a-minggu', kelas: '1A', hari: 'Minggu', kitab: 'فكون', kitabLatin: 'Pegon', fanIlmu: 'Pegon', kodeGuru: 17 },
  { id: 'j-1b-minggu', kelas: '1B', hari: 'Minggu', kitab: 'الامثلة التصريفية', kitabLatin: 'Al-Amtsilah At-Tashrifiyyah', fanIlmu: 'Shorof', kodeGuru: 19 },
  { id: 'j-2a-minggu', kelas: '2A', hari: 'Minggu', kitab: 'تقريب', kitabLatin: 'Taqrib', fanIlmu: 'Fiqih', kodeGuru: 7 },
  { id: 'j-2b-minggu', kelas: '2B', hari: 'Minggu', kitab: 'جواهر الكلامية', kitabLatin: 'Jawahirul Kalamiyyah', fanIlmu: 'Tauhid', kodeGuru: 15 },
  { id: 'j-3a-minggu', kelas: '3A', hari: 'Minggu', kitab: 'قواعد الإعلال', kitabLatin: 'Qawa\'idul I\'lal', fanIlmu: 'Shorof', kodeGuru: 6 },
  { id: 'j-3b-minggu', kelas: '3B', hari: 'Minggu', kitab: 'جرومية', kitabLatin: 'Jurumiyyah', fanIlmu: 'Nahwu', kodeGuru: 14 },
  { id: 'j-3c-minggu', kelas: '3C', hari: 'Minggu', kitab: 'تيجان الدراري', kitabLatin: 'Tijan Ad-Darari', fanIlmu: 'Tauhid', kodeGuru: 21 },
  { id: 'j-4a-minggu', kelas: '4A', hari: 'Minggu', kitab: 'فتح المجيد', kitabLatin: 'Fathul Majid', fanIlmu: 'Tauhid', kodeGuru: 16 },
  { id: 'j-4b-minggu', kelas: '4B', hari: 'Minggu', kitab: 'العمريطي', kitabLatin: 'Imrithi', fanIlmu: 'Nahwu', kodeGuru: 12 },
  { id: 'j-5a-minggu', kelas: '5A', hari: 'Minggu', kitab: 'قواعد الصرفية', kitabLatin: 'Qawa\'idush Shorfiyyah', fanIlmu: 'Shorof', kodeGuru: 5 },
  { id: 'j-5b-minggu', kelas: '5B', hari: 'Minggu', kitab: 'فتح القريب', kitabLatin: 'Fathul Qorib', fanIlmu: 'Fiqih', kodeGuru: 11 },
  { id: 'j-6-minggu', kelas: '6', hari: 'Minggu', kitab: 'فتح القريب', kitabLatin: 'Fathul Qorib', fanIlmu: 'Fiqih', kodeGuru: 13 },

  // Selasa
  { id: 'j-1a-selasa', kelas: '1A', hari: 'Selasa', kitab: 'عقيدة العوام', kitabLatin: 'Aqidatul Awam', fanIlmu: 'Tauhid', kodeGuru: 18 },
  { id: 'j-1b-selasa', kelas: '1B', hari: 'Selasa', kitab: 'شفاء الجنان', kitabLatin: 'Syifa\'ul Jinan', fanIlmu: 'Tajwid', kodeGuru: 20 },
  { id: 'j-2a-selasa', kelas: '2A', hari: 'Selasa', kitab: 'جواهر الكلامية', kitabLatin: 'Jawahirul Kalamiyyah', fanIlmu: 'Tauhid', kodeGuru: 1 },
  { id: 'j-2b-selasa', kelas: '2B', hari: 'Selasa', kitab: 'تقريب', kitabLatin: 'Taqrib', fanIlmu: 'Fiqih', kodeGuru: 7 },
  { id: 'j-3a-selasa', kelas: '3A', hari: 'Selasa', kitab: 'جرومية', kitabLatin: 'Jurumiyyah', fanIlmu: 'Nahwu', kodeGuru: 14 },
  { id: 'j-3b-selasa', kelas: '3B', hari: 'Selasa', kitab: 'قواعد الإعلال', kitabLatin: 'Qawa\'idul I\'lal', fanIlmu: 'Shorof', kodeGuru: 6 },
  { id: 'j-3c-selasa', kelas: '3C', hari: 'Selasa', kitab: 'تقريب', kitabLatin: 'Taqrib', fanIlmu: 'Fiqih', kodeGuru: 11 },
  { id: 'j-4a-selasa', kelas: '4A', hari: 'Selasa', kitab: 'العمريطي', kitabLatin: 'Imrithi', fanIlmu: 'Nahwu', kodeGuru: 12 },
  { id: 'j-4b-selasa', kelas: '4B', hari: 'Selasa', kitab: 'الترغيب والترهيب', kitabLatin: 'At-Targhib wat-Tarhib', fanIlmu: 'Hadist', kodeGuru: 13 },
  { id: 'j-5a-selasa', kelas: '5A', hari: 'Selasa', kitab: 'العمريطي', kitabLatin: 'Imrithi', fanIlmu: 'Nahwu', kodeGuru: 2 },
  { id: 'j-5b-selasa', kelas: '5B', hari: 'Selasa', kitab: 'حجة أهل السنة والجماعة', kitabLatin: 'Hujjah Ahlussunnah wal Jama\'ah', fanIlmu: 'Aswaja', kodeGuru: 9 },
  { id: 'j-6-selasa', kelas: '6', hari: 'Selasa', kitab: 'حجة أهل السنة والجماعة', kitabLatin: 'Hujjah Ahlussunnah wal Jama\'ah', fanIlmu: 'Aswaja', kodeGuru: 5 },

  // Rabu
  { id: 'j-1a-rabu', kelas: '1A', hari: 'Rabu', kitab: 'الامثلة التصريفية', kitabLatin: 'Al-Amtsilah At-Tashrifiyyah', fanIlmu: 'Shorof', kodeGuru: 19 },
  { id: 'j-1b-rabu', kelas: '1B', hari: 'Rabu', kitab: 'فكون', kitabLatin: 'Pegon', fanIlmu: 'Pegon', kodeGuru: 17 },
  { id: 'j-2a-rabu', kelas: '2A', hari: 'Rabu', kitab: 'الاربعين النووى', kitabLatin: 'Al-Arba\'in An-Nawawi', fanIlmu: 'Hadits', kodeGuru: 16 },
  { id: 'j-2b-rabu', kelas: '2B', hari: 'Rabu', kitab: 'جرومية', kitabLatin: 'Jurumiyyah', fanIlmu: 'Nahwu', kodeGuru: 6 },
  { id: 'j-3a-rabu', kelas: '3A', hari: 'Rabu', kitab: 'تقريب', kitabLatin: 'Taqrib', fanIlmu: 'Fiqih', kodeGuru: 11 },
  { id: 'j-3b-rabu', kelas: '3B', hari: 'Rabu', kitab: 'الترغيب والترهيب', kitabLatin: 'At-Targhib wat-Tarhib', fanIlmu: 'Hadist', kodeGuru: 13 },
  { id: 'j-3c-rabu', kelas: '3C', hari: 'Rabu', kitab: 'جرومية', kitabLatin: 'Jurumiyyah', fanIlmu: 'Nahwu', kodeGuru: 14 },
  { id: 'j-4a-rabu', kelas: '4A', hari: 'Rabu', kitab: 'الترغيب والترهيب', kitabLatin: 'At-Targhib wat-Tarhib', fanIlmu: 'Hadist', kodeGuru: 18 },
  { id: 'j-4b-rabu', kelas: '4B', hari: 'Rabu', kitab: 'فتح القريب', kitabLatin: 'Fathul Qorib', fanIlmu: 'Fiqih', kodeGuru: 4 },
  { id: 'j-5a-rabu', kelas: '5A', hari: 'Rabu', kitab: 'حجة أهل السنة والجماعة', kitabLatin: 'Hujjah Ahlussunnah wal Jama\'ah', fanIlmu: 'Aswaja', kodeGuru: 9 },
  { id: 'j-5b-rabu', kelas: '5B', hari: 'Rabu', kitab: 'العمريطي', kitabLatin: 'Imrithi', fanIlmu: 'Nahwu', kodeGuru: 2 },
  { id: 'j-6-rabu', kelas: '6', hari: 'Rabu', kitab: 'فتح المجيد', kitabLatin: 'Fathul Majid', fanIlmu: 'Tauhid', kodeGuru: 12 },
];

// Helper to get guru name by code
export const getGuruByKode = (kode: number, guruList: GuruJadwal[] = MOCK_GURU_JADWAL): string => {
  const g = guruList.find(item => item.kode === kode);
  return g ? g.nama : `Guru Kode ${kode}`;
};

export const MOCK_JADWAL: JadwalPelajaranItem[] = MOCK_JADWAL_SLOTS.map((slot) => {
  const guruNama = getGuruByKode(slot.kodeGuru);
  return {
    id: slot.id,
    hari: slot.hari,
    jam: '19.30 - 21.00 WIB',
    mataPelajaran: `${slot.fanIlmu} (${slot.kitabLatin || slot.kitab})`,
    kategori: 'Agama / Syariah',
    guru: guruNama,
    kelas: `Kelas ${slot.kelas}`,
    ruangan: `Gedung Madrasah Lt. ${slot.kelas.startsWith('1') || slot.kelas.startsWith('2') ? '1' : '2'}`,
    status: 'Akan Datang',
    kitab: slot.kitab,
    fanIlmu: slot.fanIlmu,
    kodeGuru: slot.kodeGuru,
  };
});

export const MOCK_SILABUS: SilabusItem[] = [
  {
    id: 'sil-1',
    mataPelajaran: 'Bahasa Arab (Nahwu & Sharaf)',
    kelas: 'Kelas 5',
    semester: 'Ganjil',
    kompetensi: 'Memahami kaidah i\'rab isim marfu\', isim manshub, dan isim majrur serta aplikasinya dalam membaca kitab gundul.',
    materi: 'Kajian Matan Al-Ajurrumiyyah & Mukhtashor Jiddan (Bab Na\'at, Athaf, Taukid, Badal, & Maf\'ul Bih)',
    tujuanPembelajaran: 'Santri mampu menentukan jabatan kata, tanda i\'rab harakat/huruf, dan menerapkannya dalam membaca teks Arab klasik tanpa harakat secara mandiri dan fasih.',
    metodePembelajaran: 'Metode Bandongan, Sorogan, Qawaid wa Tarjamah, serta Drill I\'rab interaktif.',
    alokasiWaktu: '36 Jam Pertemuan (18 Pekan @ 2 Jam)',
    referensi: 'Kitab Mukhtashor Jiddan \'ala Matn Al-Ajurrumiyyah karya Sayyid Ahmad Zaini Dahlan & Kamus Al-Munawwir',
    guruPengampu: 'Ustadz Ahmad Fauzi, S.Pd.I',
    isPublishedToSiswa: true,
  },
  {
    id: 'sil-2',
    mataPelajaran: 'Fiqih Ibadah & Muamalah',
    kelas: 'Kelas 5',
    semester: 'Ganjil',
    kompetensi: 'Menganalisis hukum akad jual beli kontemporer, syirkah, perbankan syariah, dan zakat produktif sesuai madzhab Syafi\'i.',
    materi: 'Kitab Fathul Qorib Al-Mujib (Kitab Al-Buyu\' wa Mu\'amalat Al-Maliyyah)',
    tujuanPembelajaran: 'Santri mampu membedakan transaksi halal dan bathil/riba serta menyelesaikan studi kasus muamalah modern berdasarkan kaidah ushul fiqih.',
    metodePembelajaran: 'Bahtsul Masa\'il, Diskusi Kasus Kontekstual, dan Presentasi Makalah Santri.',
    alokasiWaktu: '36 Jam Pertemuan (18 Pekan @ 2 Jam)',
    referensi: 'Fathul Qorib karya Syaikh Ibnu Qosim Al-Ghazzi & Fiqh Al-Mu\'amalat Al-Mu\'ashirah karya Dr. Wahbah Zuhaili',
    guruPengampu: 'Ustadz Ahmad Fauzi, S.Pd.I',
    isPublishedToSiswa: true,
  },
  {
    id: 'sil-3',
    mataPelajaran: 'Madrasatul Qur\'an & Tajwid',
    kelas: 'Kelas 5',
    semester: 'Ganjil',
    kompetensi: 'Menghafal 3 Juz Al-Qur\'an secara mutqin dengan kaidah Tajwid Matn Al-Jazariyyah.',
    materi: 'Setoran Hafalan Juz 8, 9, 10 dan Ujian Tasmi\' Bil-Ghaib Satu Majelis.',
    tujuanPembelajaran: 'Santri mentuntaskan target hafalan mutqin dengan makhraj dan shifat huruf standar qira\'at Hafs \'an \'Ashim.',
    metodePembelajaran: 'Talaqqi, Tikrar (pengulangan 40x), Simaan Pasangan (Zaujiy), dan Tasmi\' Pekanan.',
    alokasiWaktu: '72 Jam Pertemuan (Halaqah Subuh & Ashar)',
    referensi: 'Mushaf Al-Qur\'an Rasm Utsmani & Syarah Mandzumah Al-Jazariyyah karya Dr. Ayman Suwaid',
    guruPengampu: 'Ustadz Hafidz Al-Mubarok, Lc',
    isPublishedToSiswa: true,
  },
];

export const MOCK_MATERI: MateriItem[] = [
  {
    id: 'mat-1',
    judul: 'Ringkasan Kaidah I\'rab Isim Manshub & Badal',
    mataPelajaran: 'Bahasa Arab (Nahwu)',
    kelas: 'Kelas 5A & 5B',
    guru: 'Ustadz Ahmad Fauzi, S.Pd.I',
    tipe: 'PDF',
    ukuran: '2.4 MB',
    tanggalUpload: '02 Sep 2026',
    deskripsi: 'Modul pegangan santri bab isim manshub dilengkapi bagan warna dan tabel contoh i\'rab dari ayat Al-Qur\'an.',
    coverColor: 'emerald',
    unduhanCount: 142,
  },
  {
    id: 'mat-2',
    judul: 'Matan Al-Ajurrumiyyah Format Teks Saku Digital',
    mataPelajaran: 'Bahasa Arab (Nahwu)',
    kelas: 'Kelas 5 & 6',
    guru: 'Ustadz Ahmad Fauzi, S.Pd.I',
    tipe: 'Buku',
    ukuran: '4.8 MB',
    tanggalUpload: '28 Agu 2026',
    deskripsi: 'Kitab lengkap matan Ajurrumiyyah berharakat jelas dengan terjemah antar baris dan catatan kaki praktis.',
    coverColor: 'amber',
    unduhanCount: 310,
  },
  {
    id: 'mat-3',
    judul: 'Lembar Kerja Praktik Akad Mudharabah & Murabahah',
    mataPelajaran: 'Fiqih Muamalah',
    kelas: 'Kelas 5A',
    guru: 'Ustadz Ahmad Fauzi, S.Pd.I',
    tipe: 'Lembar Kerja',
    ukuran: '1.1 MB',
    tanggalUpload: '04 Sep 2026',
    deskripsi: 'Simulasi kontrak keuangan syariah dengan skenario nyata dan lembar kerja evaluasi mandiri santri.',
    coverColor: 'teal',
    unduhanCount: 98,
  },
  {
    id: 'mat-4',
    judul: 'Bagan Makhorijul Huruf & Sifat Huruf Hijaiyyah HD',
    mataPelajaran: 'Tahfidz Al-Qur\'an',
    kelas: 'Seluruh Santri',
    guru: 'Ustadz Hafidz Al-Mubarok, Lc',
    tipe: 'Gambar',
    ukuran: '5.2 MB',
    tanggalUpload: '15 Agu 2026',
    deskripsi: 'Infografis resolusi tinggi penampang rongga mulut, tenggorokan, dan lidah berdasarkan kitab Tajwid Al-Mushawwar.',
    coverColor: 'blue',
    unduhanCount: 420,
  },
  {
    id: 'mat-5',
    judul: 'Modul Percakapan Bahasa Arab Sehari-hari (Al-Muhawarah)',
    mataPelajaran: 'Bahasa Arab',
    kelas: 'Kelas 5A & 5B',
    guru: 'Ustadz Ahmad Fauzi, S.Pd.I',
    tipe: 'Modul',
    ukuran: '3.6 MB',
    tanggalUpload: '01 Sep 2026',
    deskripsi: 'Ungkapan resmi asrama, masjid, kantin, perpustakaan dan istilah modern dalam Bahasa Arab Fushah.',
    coverColor: 'green',
    unduhanCount: 265,
  },
];

export const MOCK_BUKU_GURU: BukuKerjaItem[] = [
  {
    id: 'bg-1',
    kategori: 'guru',
    judul: 'Pedoman Kode Etik & Tata Tertib Asatidz',
    subJudul: 'Standar Perilaku, Keteladanan, & Kedisiplinan Guru Pesantren',
    jenisDokumen: 'Pedoman Pesantren',
    tahun: '2025/2026',
    ukuran: '3.1 MB',
    halaman: 48,
    penulisOrPenerbit: 'Majelis Pengasuh & Dewan Asatidz',
    deskripsi: 'Memuat aturan kehadiran di madrasah dan asrama, adab berinteraksi dengan santri, panduan busana syar\'i, dan tata tertib pengasuhan.',
  },
  {
    id: 'bg-2',
    kategori: 'guru',
    judul: 'Panduan Pembelajaran Kurikulum Madin Terpadu',
    subJudul: 'Sintaks Model Pembelajaran Salaf & Modern di Ruang Kelas',
    jenisDokumen: 'Panduan Mengajar',
    tahun: '2025/2026',
    ukuran: '5.4 MB',
    halaman: 112,
    penulisOrPenerbit: 'Bagian Kurikulum Akademik',
    deskripsi: 'Standar operasional prosedur (SOP) penyusunan RPP, alur tujuan pembelajaran, integrasi nilai kepesantrenan pada mapel umum.',
  },
  {
    id: 'bg-3',
    kategori: 'guru',
    judul: 'Instrumen & Panduan Penilaian Raport Madin',
    subJudul: 'Pedoman Konversi Nilai, Pembobotan, dan Asesmen Karakter Akhlak',
    jenisDokumen: 'Panduan Penilaian',
    tahun: '2025/2026',
    ukuran: '2.8 MB',
    halaman: 64,
    penulisOrPenerbit: 'Biro Penjaminan Mutu Madrasah',
    deskripsi: 'Petunjuk teknis input nilai tugas, ulangan harian, UTS, UAS, kriteria kelulusan Mumtaz, dan deskripsi capaian raport.',
  },
  {
    id: 'bg-4',
    kategori: 'guru',
    judul: 'Buku Jurnal Mengajar & Absensi Guru Piket',
    subJudul: 'Format Administrasi Harian Asatidz Terintegrasi',
    jenisDokumen: 'Jurnal Guru',
    tahun: '2025/2026',
    ukuran: '1.9 MB',
    halaman: 36,
    penulisOrPenerbit: 'Sekretariat Pesantren Terpadu',
    deskripsi: 'Format resmi pelaporan kehadiran kelas, catatan siswa bermasalah, dan ketercapaian silabus mingguan.',
  },
  {
    id: 'bg-5',
    kategori: 'guru',
    judul: 'Standar Operasional Disiplin & Pengasuhan Asrama',
    subJudul: 'Panduan Musyrif & Wali Kamar dalam Pembinaan Santri 24 Jam',
    jenisDokumen: 'Pedoman Pengasuhan',
    tahun: '2025/2026',
    ukuran: '4.0 MB',
    halaman: 88,
    penulisOrPenerbit: 'Biro Pengasuhan Santri (Tarbiyah)',
    deskripsi: 'Prosedur perizinan pulang, penanganan pelanggaran disiplin, panduan ronda malam, dan pembinaan halaqah tarbiyah.',
  }
];

export const MOCK_BUKU_SISWA: BukuKerjaItem[] = [
  {
    id: 'bs-1',
    kategori: 'siswa',
    judul: 'Buku Panduan & Tata Tertib Santri Terpadu',
    subJudul: 'Qanun Ma\'had: Adab, Hak, Kewajiban, & Larangan Santri',
    jenisDokumen: 'Tata Tertib Santri',
    tahun: '2025/2026',
    ukuran: '2.5 MB',
    halaman: 56,
    penulisOrPenerbit: 'Biro Pengasuhan Santri',
    deskripsi: 'Buku wajib santri baru dan lama yang memuat jadwal harian dari bangun pukul 03.30 sampai istirahat malam pukul 22.00.',
  },
  {
    id: 'bs-2',
    kategori: 'siswa',
    judul: 'Kitab Al-Adab An-Nabawiyyah wa Al-Akhlak Al-Karimah',
    subJudul: 'Kumpulan Matan Doa & Dzikir Harian Al-Ma\'tsurat Pesantren',
    jenisDokumen: 'Doa dan Hafalan',
    tahun: '2025/2026',
    ukuran: '3.2 MB',
    halaman: 72,
    penulisOrPenerbit: 'Bagian Dakwah & Peribadatan',
    deskripsi: 'Kumpulan doa harian, dzikir ba\'da shalat fardhu, wirid Al-Waqi\'ah & Ar-Rahman, dan adab thalabul ilmi karya Imam Al-Ghazali.',
  },
  {
    id: 'bs-3',
    kategori: 'siswa',
    judul: 'Lembar Kerja Santri (LKS) Nahwu Aplikatif Kelas 5',
    subJudul: 'Modul Latihan Analisis I\'rab Teks Kitab Turats Salaf',
    jenisDokumen: 'Lembar Kerja Siswa',
    tahun: '2025/2026',
    ukuran: '3.7 MB',
    halaman: 94,
    penulisOrPenerbit: 'Tim Asatidz Bahasa Arab',
    deskripsi: 'Latihan mingguan santri untuk mempertajam kepekaan struktur kalimat Bahasa Arab, lengkap dengan ruang coretan harakat.',
  },
  {
    id: 'bs-4',
    kategori: 'siswa',
    judul: 'Buku Mutaba\'ah Ibadah & Setoran Tahfidz Mandiri',
    subJudul: 'Kartu Monitoring Shalat Berjamaah, Puasa Sunnah, & Dzikir',
    jenisDokumen: 'Informasi Akademik',
    tahun: '2025/2026',
    ukuran: '1.8 MB',
    halaman: 40,
    penulisOrPenerbit: 'Lembaga Tahfidz & Tarbiyah',
    deskripsi: 'Buku kendali harian yang ditandatangani oleh musyrif kamar setiap pekan untuk memantau konsistensi ibadah yaumiyah.',
  }
];

export const MOCK_SOAL: SoalItem[] = [
  {
    id: 'soal-1',
    mataPelajaran: 'Bahasa Arab (Nahwu)',
    kelas: 'Kelas 5A',
    bab: 'Bab Isim-Isim yang Di-rafa\'kan (Al-Marfu\'at)',
    kompetensi: 'Mengidentifikasi jenis Fa\'il dan Na\'ibul Fa\'il pada kalimat Arab sempurna.',
    tipeSoal: 'pilihan_ganda',
    tingkatKesulitan: 'Sedang',
    pertanyaan: 'Manakah kalimat berikut yang mengandung Na\'ibul Fa\'il dhohir berharakat dhommah?',
    pilihanJawaban: [
      'قَرَأَ الطَّالِبُ الكِتَابَ فِي المَكْتَبَةِ',
      'فُتِحَ البَابُ بَعْدَ أَذَانِ الفَجْرِ',
      'جَلَسَ الأُسْتَاذُ عَلَى الكُرْسِيِّ',
      'يَكْتُبُ زَيْدٌ رِسَالَةً إِلَى وَالِدِهِ',
      'ذَهَبَ الحُجَّاجُ إِلَى مَكَّةَ المُكَرَّمَةِ'
    ],
    kunciJawaban: 'B (فُتِحَ البَابُ بَعْدَ أَذَانِ الفَجْرِ)',
    bobotNilai: 10,
    status: 'Dipublikasikan',
    tanggalDibuat: '01 Sep 2026',
  },
  {
    id: 'soal-2',
    mataPelajaran: 'Fiqih Muamalah',
    kelas: 'Kelas 5A',
    bab: 'Ketentuan Riba & Akad Jual Beli',
    kompetensi: 'Membedakan antara Riba Fadhl, Riba Nasi\'ah, dan Riba Qardh.',
    tipeSoal: 'benar_salah',
    tingkatKesulitan: 'Mudah',
    pertanyaan: 'Pertukaran emas dengan perhiasan emas yang tidak sama berat gramnya termasuk dalam kategori Riba Fadhl meskipun diserahterimakan secara tunai pada majelis yang sama.',
    kunciJawaban: 'BENAR (Emas termasuk amwal ribawiyyah yang mensyaratkan tamatsul/timbangan sama)',
    bobotNilai: 10,
    status: 'Dipublikasikan',
    tanggalDibuat: '02 Sep 2026',
  },
  {
    id: 'soal-3',
    mataPelajaran: 'Bahasa Arab (Nahwu)',
    kelas: 'Kelas 5A',
    bab: 'I\'rab Asma\'ul Khamsah',
    kompetensi: 'Menyebutkan tanda i\'rab ketika marfu\', manshub, dan majrur pada Asma\'ul Khamsah.',
    tipeSoal: 'isian',
    tingkatKesulitan: 'Sedang',
    pertanyaan: 'Tanda i\'rab rofa\' pada lafazh \'Abuka\' (أَبُوكَ) adalah huruf ..., sedangkan tanda nashob-nya adalah huruf ...',
    kunciJawaban: 'Wawu (و), Alif (ا)',
    bobotNilai: 15,
    status: 'Dipublikasikan',
    tanggalDibuat: '03 Sep 2026',
  },
  {
    id: 'soal-4',
    mataPelajaran: 'Fiqih Muamalah',
    kelas: 'Kelas 5A',
    bab: 'Akad Salam & Istishna\'',
    kompetensi: 'Menganalisis perbedaan rukun dan syarat jual beli pesanan salam dengan istishna\'.',
    tipeSoal: 'essay',
    tingkatKesulitan: 'Sulit',
    pertanyaan: 'Jelaskan perbedaan mendasar antara akad Bai\' As-Salam dengan Bai\' Al-Istishna\' ditinjau dari sisi: (1) Waktu pelunasan modal ra\'sul mal, dan (2) Sifat keterikatan akad (Luzum wa Jawaz)!',
    kunciJawaban: 'Pada Salam modal wajib tunai di majelis akad (Fi majlisil aqad) dan akad bersifat lazim; sedangkan pada Istishna\' pembayaran boleh dicicil/tempo sesuai kesepakatan shani\' dan mustashni\'.',
    bobotNilai: 25,
    status: 'Dipublikasikan',
    tanggalDibuat: '04 Sep 2026',
  },
  {
    id: 'soal-5',
    mataPelajaran: 'Hadits Arbain',
    kelas: 'Kelas 5A',
    bab: 'Hadits Ke-1 (Innamal A\'malu Binniyat)',
    kompetensi: 'Menghafal dan menguraikan intisari hadits niat.',
    tipeSoal: 'essay',
    tingkatKesulitan: 'Sedang',
    pertanyaan: 'Tuliskan matan hadits pertama Arbain An-Nawawiyyah beserta perawi utamanya dari kalangan sahabat Nabi!',
    kunciJawaban: 'Diriwayatkan oleh Amirul Mukminin Abu Hafsh Umar bin Khattab radhiyallahu \'anhu: Sami\'tu Rasulallahi ﷺ yaqulu: Innamal a\'malu binniyat...',
    bobotNilai: 20,
    status: 'Draft',
    tanggalDibuat: '05 Sep 2026',
  },
];

export const MOCK_NOTIFIKASI: NotifikasiItem[] = [
  {
    id: 'notif-1',
    judul: 'Absensi Harian Belum Lengkap',
    pesan: 'Anda belum mengisi absensi kelas 5A untuk sesi Bahasa Arab hari ini.',
    waktu: '10 menit yang lalu',
    tipe: 'warning',
    dibaca: false,
    targetRole: ['guru', 'admin'],
    linkModule: 'absensi',
  },
  {
    id: 'notif-2',
    judul: 'Kelengkapan Nilai UTS',
    pesan: 'Nilai UTS kelas 6 belum lengkap (92% terselesaikan). Mohon verifikasi sisa 2 santri susulan.',
    waktu: '45 menit yang lalu',
    tipe: 'warning',
    dibaca: false,
    targetRole: ['guru', 'admin'],
    linkModule: 'nilai',
  },
  {
    id: 'notif-3',
    judul: 'Jadwal Mengajar Hari Ini',
    pesan: 'Ada jadwal mengajar pukul 10.00 di Ruang 3 Ibnu Rusyd (Mata Pelajaran: Bahasa Arab).',
    waktu: '1 jam yang lalu',
    tipe: 'info',
    dibaca: false,
    targetRole: ['guru'],
    linkModule: 'jadwal',
  },
  {
    id: 'notif-4',
    judul: 'Dokumen Baru Ditambahkan',
    pesan: 'Dokumen baru silabus dan kalender akademik pesantren 2026 telah ditambahkan oleh Sekretariat.',
    waktu: '3 jam yang lalu',
    tipe: 'info',
    dibaca: false,
    targetRole: ['admin', 'guru', 'siswa'],
    linkModule: 'dokumen',
  },
  {
    id: 'notif-5',
    judul: 'Soal Ujian Baru Tersedia',
    pesan: 'Soal ujian baru Fiqih Muamalah Semester Ganjil telah dipublikasikan dan siap diujikan.',
    waktu: 'Kemarin',
    tipe: 'success',
    dibaca: true,
    targetRole: ['guru', 'siswa'],
    linkModule: 'soal',
  },
];

export const MOCK_DOKUMEN_PESANTREN: DokumenPesantrenItem[] = [
  {
    id: 'dok-1',
    judul: 'Surat Keputusan Pimpinan Ma\'had No. 042/SK-PONTREN/VIII/2026 tentang Struktur Dewan Asatidz',
    nomorSurat: '042/SK-PONTREN/VIII/2026',
    kategori: 'SK Pimpinan',
    tanggalRilis: '01 Agu 2026',
    ukuran: '1.4 MB',
  },
  {
    id: 'dok-2',
    judul: 'Kalender Akademik & Agenda Kegiatan Santri Pesantren Terpadu T.A. 2025/2026',
    nomorSurat: 'KAL-AKAD/2025-2026',
    kategori: 'Kalender Akademik',
    tanggalRilis: '15 Jul 2026',
    ukuran: '3.8 MB',
  },
  {
    id: 'dok-3',
    judul: 'Kurikulum Resmi Madrasah Diniyah Takmiliyah Terpadu 6 Tahun',
    nomorSurat: 'KUR-MDTA/09/2025',
    kategori: 'Kurikulum',
    tanggalRilis: '20 Jul 2025',
    ukuran: '8.2 MB',
  },
  {
    id: 'dok-4',
    judul: 'Peraturan Disiplin Bahasa Resmi (Arab & Inggris) & Sanksi Edukatif Ma\'had',
    nomorSurat: 'PER-DISP-08/LAC/2026',
    kategori: 'Tata Tertib',
    tanggalRilis: '10 Agu 2026',
    ukuran: '2.1 MB',
  },
  {
    id: 'dok-5',
    judul: 'Standar Operasional Prosedur (SOP) Evaluasi Akademik & Kenaikan Tingkat Santri',
    nomorSurat: 'SOP-AKAD-2026/01',
    kategori: 'Tata Tertib',
    tanggalRilis: '05 Jan 2026',
    ukuran: '1.7 MB',
  },
];

export const MOCK_RAPORT_DEFAULT: RaportSiswa = {
  santri: MOCK_SANTRI[0], // Ahmad Zaki Mubarak
  tahunAjaran: '2025/2026',
  semester: 'Ganjil',
  ranking: 3,
  totalSantriKelas: 32,
  nilaiMapel: [
    {
      kategori: 'Dirasah Islamiyah (Kepesantrenan)',
      mapel: 'Tahfidzul Qur\'an 30 Juz',
      kkm: 80,
      nilaiAngka: 94,
      predikat: 'Mumtaz (A)',
      deskripsi: 'Menyelesaikan hafalan 8 Juz dengan makhraj fasih, waqaf ibtida\' tepat, serta tartil yang indah.',
    },
    {
      kategori: 'Dirasah Islamiyah (Kepesantrenan)',
      mapel: 'Nahwu & Sharaf (Al-Ajurrumiyyah)',
      kkm: 75,
      nilaiAngka: 93,
      predikat: 'Mumtaz (A)',
      deskripsi: 'Sangat menguasai kaidah i\'rab marfu\'at dan mampu mengi\'rab naskah kitab Fathul Qorib dengan lancar.',
    },
    {
      kategori: 'Dirasah Islamiyah (Kepesantrenan)',
      mapel: 'Fiqih Muamalah (Bidayatul Mujtahid)',
      kkm: 75,
      nilaiAngka: 91,
      predikat: 'Mumtaz (A)',
      deskripsi: 'Mampu menjelaskan rukun dan syarat jual beli serta menguraikan illat riba kontemporer.',
    },
    {
      kategori: 'Dirasah Islamiyah (Kepesantrenan)',
      mapel: 'Hadits Arbain An-Nawawiyyah',
      kkm: 75,
      nilaiAngka: 88,
      predikat: 'Jayyid Jiddan (B+)',
      deskripsi: 'Hafal 30 hadits dengan sanad muttashil dan memahami asbabul wurud dengan baik.',
    },
    {
      kategori: 'Bahasa Asing',
      mapel: 'Bahasa Arab (Muhadatsah & Insya\')',
      kkm: 75,
      nilaiAngka: 95,
      predikat: 'Mumtaz (A)',
      deskripsi: 'Sangat aktif berkomunikasi dalam Bahasa Arab fushah di lingkungan asrama dan mahir menulis insya\' 2 halaman.',
    },
    {
      kategori: 'Bahasa Asing',
      mapel: 'Bahasa Inggris (Grammar & Speech)',
      kkm: 75,
      nilaiAngka: 89,
      predikat: 'Jayyid Jiddan (B+)',
      deskripsi: 'Kefasihan dalam public speaking sangat baik, kosa kata bervariasi.',
    },
    {
      kategori: 'Pendidikan Umum',
      mapel: 'Matematika Terpadu',
      kkm: 70,
      nilaiAngka: 87,
      predikat: 'Jayyid Jiddan (B+)',
      deskripsi: 'Menguasai persamaan aljabar dan statistika dasar dengan teliti.',
    },
    {
      kategori: 'Pendidikan Umum',
      mapel: 'Ilmu Pengetahuan Alam (Fisika & Biologi)',
      kkm: 70,
      nilaiAngka: 88,
      predikat: 'Jayyid Jiddan (B+)',
      deskripsi: 'Aktif dalam percobaan laboratorium dan menghubungkan ayat kauniyah dengan sains.',
    },
  ],
  tahfidz: {
    juzTeruji: 'Juz 1 s/d Juz 8 (8 Juz)',
    kelancaran: 'Mumtaz (Sangat Lancar / Mutqin)',
    tajwidMakhraj: 'Jayyid Jiddan (Fasih Sesuai Qira\'at Ashim)',
    predikat: 'Mumtaz (A)',
  },
  akhlakAdab: {
    kedisiplinanIbadah: 'A (Konsisten sholat berjamaah di shaf pertama)',
    adabSantri: 'A (Sangat tawadhu\' kepada asatidz dan pengasuh)',
    kebersihanKamar: 'A (Rapi, disiplin piket kelas & madrasah)',
    bahasaResmiAsrama: 'A (100% disiplin berbahasa Arab & Inggris)',
  },
  absensiSemester: {
    sakit: 2,
    izin: 1,
    alpa: 0,
  },
  catatanWaliKelas: 'Alhamdulillah, santri ananda Ahmad Zaki Mubarak menunjukkan akhlakul karimah yang patut diteladani, hafalan Al-Qur\'an terus bertambah mutqin, serta prestasi akademik yang membanggakan. Pertahankan kesungguhan muthala\'ah kitab di madrasah.',
  tanggalCetak: '20 Desember 2025',
};

export const MOCK_IJAZAH_DEFAULT: IjazahSiswa = {
  nomorIjazah: 'IJZ-MDT-ANJ2/VI/2026/089',
  santri: MOCK_SANTRI[8] || MOCK_SANTRI[0],
  namaPesantren: 'MADRASAH DINIYAH TAKMILIYAH ANNAJIYAH 2 BAHRUL ULUM TAMBAKBERAS JOMBANG',
  tahunKelulusan: '2025/2026 M (1447 H)',
  nomorPokokSekolah: 'NSDT. 311235170044 - Tambakberas Jombang',
  nilaiRataRata: 94.5,
  predikatKelulusan: 'MUMTAZ (Dengan Pujian)',
  namaPengasuh: 'KH. M. Salman Al-Faries, Lc., M.Hi',
  tanggalKelulusan: '24 Juni 2026',
};

export const MOCK_SEJARAH_PESANTREN = {
  ringkasan: 'Madrasah Diniyyah An-Najiyah 2 berdiri di lingkungan pesantren dibawah naungan Yayasan Pondok Pesantren Bahrul Ulum Tambakberas Jombang. Didirikannya Madrasah Diniyyah An-Najiyah 2 ini tidak terlepas dari didirikannya Pondok Pesantren An-Najiyah 2 pada tahun 2004 oleh KH. M. Salman Al-Faries guna menjawab kebutuhan masyarakat luas tentang pentingnya ilmu keagamaan dan mendidik para santri menjadi muslim yang bertaqwa kepada Allah, berakhlaq mulia, memiliki kecerdasan, dan keterampilan.',
  milestones: [
    { tahun: '2004', peristiwa: 'Didirikannya Pondok Pesantren An-Najiyah 2 oleh KH. M. Salman Al-Faries melalui dukungan guru dan keluarga di lingkungan Yayasan PP. Bahrul Ulum Tambakberas.' },
    { tahun: '2008', peristiwa: 'Pengembangan kurikulum takmiliyah terpadu kitab kuning salaf dan penguatan muhafadzoh nadhom berjenjang.' },
    { tahun: '2016', peristiwa: 'Penyempurnaan administrasi madrasah terpadu dan pembakuan jenjang kelas 1 hingga kelas 6.' },
    { tahun: '2024', peristiwa: 'Pemantapan tata kelola digitalisasi madrasah terintegrasi untuk raport, absensi, bank soal, dan muhafadzoh.' },
  ],
  masyayikh: [
    {
      nama: 'KH. M. Salman Al-Faries, Lc., M.Hi',
      jabatan: 'PENGASUH',
      almamater: 'Universitas Al-Azhar Kairo & Pondok Pesantren Bahrul Ulum',
      foto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=250&auto=format&fit=crop&q=80',
      pesan: '"Guna menjawab kebutuhan masyarakat luas tentang pentingnya ilmu keagamaan dan mendidik para santri menjadi generasi religius yang berakhlaqul karimah."'
    },
    {
      nama: 'Gus Muhammad Al Ma\'mun, S.Pd',
      jabatan: 'Penasehat',
      almamater: 'Pondok Pesantren Bahrul Ulum Tambakberas',
      foto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=250&auto=format&fit=crop&q=80',
      pesan: '"Keteraturan disiplin belajar dan muthala\'ah kitab adalah kunci mencetak santri yang mandiri dan berwawasan."'
    },
    {
      nama: 'Ust. Ach. Aldyansyah, S.Pd',
      jabatan: 'Sekretaris Madrasah',
      almamater: 'Madrasah Diniyah Takmiliyah Annajiyah 2',
      foto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=250&auto=format&fit=crop&q=80',
      pesan: '"Menjadikan Tambakberas pusat terciptanya santri yang berkualitas, beriman, dan berakhlakul karimah."'
    }
  ],
  galeri: [
    { judul: 'Kajian Kitab Kuning Ba\'da Maghrib', tag: 'Kajian Salaf', img: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=600&auto=format&fit=crop&q=80' },
    { judul: 'Halaqah Muhafadzoh Nadhom Pagi', tag: 'Muhafadzoh', img: 'https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=600&auto=format&fit=crop&q=80' },
    { judul: 'KBM Diniyah di Ruang Kelas Terpadu', tag: 'KBM Takmiliyah', img: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=600&auto=format&fit=crop&q=80' },
    { judul: 'Latihan Pidato & Muhadhorah Santri', tag: 'Bahasa & Orasi', img: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=600&auto=format&fit=crop&q=80' },
    { judul: 'Pentas Seni & Khot Kaligrafi Santri', tag: 'Ekstrakurikuler', img: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80' },
    { judul: 'Haflah Imtihan & Wisuda Kelulusan Kelas 6', tag: 'Kelulusan', img: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&auto=format&fit=crop&q=80' },
  ]
};

export const BUKU_KERJA_GURU_ITEMS = [
  { no: 1, title: 'Jadwal Pelajaran', desc: 'Jadwal mengajar tatap muka mingguan sesuai penugasan', kode: 'JDW-MDTA-2025', status: 'Lengkap' },
  { no: 2, title: 'Kalender Pendidikan', desc: 'Agenda semester ganjil, pekan ujian, libur maulid, dan imtihan', kode: 'KAL-AKD-2025', status: 'Lengkap' },
  { no: 3, title: 'Peraturan Guru & Pengajar', desc: 'Tata tertib, kewajiban, larangan, dan sanksi pendidik madrasah diniyah', kode: 'TTP-GURU-2025', status: 'Lengkap' },
  { no: 4, title: 'Silabus Pembelajaran', desc: 'Kerangka acuan kompetensi dasar, materi pokok, dan indikator pencapaian', kode: 'SLB-MDTA-2025', status: 'Lengkap' },
  { no: 5, title: 'Modul Ajar / RPP', desc: 'Rencana Pelaksanaan Pembelajaran memuat langkah pembelajaran & asesmen', kode: 'RPP-MDTA-2025', status: 'Lengkap' },
  { no: 6, title: 'Absensi Siswa', desc: 'Rekap presensi santri per kelas yang diampu', kode: 'ABS-MDTA-2025', status: 'Lengkap' },
  { no: 7, title: 'Daftar Nilai Siswa', desc: 'Buku rekapitulasi nilai harian, ujian, dan setoran muhafadzoh', kode: 'DNR-MDTA-2025', status: 'Lengkap' },
  { no: 8, title: 'Kritik dan Saran', desc: 'Kanal penyampaian saran, aspirasi, dan masukan pengajar secara langsung ke pimpinan', kode: 'KRS-MDTA-2025', status: 'Lengkap' },
];

export const BUKU_KERJA_SISWA_ITEMS = [
  { id: 'bks-1', no: 1, title: 'Tata Tertib & Disiplin Santri', arabicTitle: 'نِظَامُ المَعْهَدِ وَآدَابُهُ', desc: 'Pedoman norma, aturan madrasah, tata krama, dan kedisiplinan santri.', halaman: 24, kategori: 'Disiplin Santri' },
  { id: 'bks-2', no: 2, title: 'Buku Kumpulan Doa Harian & Wirid', arabicTitle: 'الأَدْعِيَةُ اليَوْمِيَّةُ وَالمَأْثُورَاتُ', desc: 'Doa belajar, wirid ba\'da shalat fardhu, dan dzikir yaumiyah santri.', halaman: 48, kategori: 'Amalan Harian' },
  { id: 'bks-3', no: 3, title: 'Adab Penuntut Ilmu (Ta\'lim Muta\'allim)', arabicTitle: 'آدَابُ طَالِبِ العِلْمِ', desc: 'Intisari adab santri kepada guru, kitab suci, teman sebaya, serta adab majelis ilmu.', halaman: 36, kategori: 'Akhlak & Adab' },
  { id: 'bks-4', no: 4, title: 'Buku Mutaba\'ah Hafalan Nadhom', arabicTitle: 'سِجِلُّ مُتَابَعَةِ الحِفْظِ', desc: 'Lembar ceklis setoran nadhom Aqidatul Awam, Al-Amtsilah, Al-Jurumiyyah, dan Imrithi.', halaman: 32, kategori: 'Muhafadzoh' },
  { id: 'bks-5', no: 5, title: 'Mufradat & Kosakata Bahasa Arab Harian', arabicTitle: 'مُفْرَدَاتُ اللُّغَةِ العَرَبِيَّةِ اليَوْمِيَّةِ', desc: '1.000 kosakata bahasa Arab percakapan dan istilah kitab turats.', halaman: 64, kategori: 'Bahasa Arab' },
  { id: 'bks-6', no: 6, title: 'Lembar Kerja Siswa (LKS) Takmiliyah', arabicTitle: 'أَوْرَاقُ عَمَلِ الطَّالِبِ التَّطْبِيقِيَّةِ', desc: 'Latihan soal mandiri dan pemahaman kaidah kitab salaf.', halaman: 80, kategori: 'Akademik Santri' },
];

export const MOCK_PAKET_SOAL = [
  {
    id: 'pkt-1',
    judul: 'Ujian Tengah Semester (UTS) Nahwu & Sharaf Kelas 5A',
    mataPelajaran: 'Bahasa Arab (Nahwu)',
    kelas: '5A',
    semester: 'Ganjil' as const,
    alokasiWaktuMenit: 90,
    guruPembuat: 'Ustadz Ahmad Fauzi, S.Pd.I',
    tanggalDibuat: '06 Sep 2026',
    tanggalMulai: '2026-09-01',
    jamMulai: '08:00',
    tanggalSelesai: '2026-12-31',
    jamSelesai: '23:59',
    totalSoal: 5,
    totalBobot: 100,
    status: 'Terpublikasi',
    isPublished: true,
    daftarSoal: [
      {
        id: 'soal-1',
        nomor: 1,
        tipe: 'Pilihan Ganda',
        pertanyaan: 'Manakah tanda i\'rab rafa\' yang menjadi tanda asli (al-ashlu) dalam kaidah Nahwu?',
        opsi: ['Dhammah', 'Fathah', 'Kasrah', 'Sukun'],
        kunciJawaban: 'Dhammah',
        bobot: 15,
      },
      {
        id: 'soal-2',
        nomor: 2,
        tipe: 'Pilihan Ganda',
        pertanyaan: 'Berikut ini yang termasuk Isim yang tidak menerima tanwin (Mamnu\' minash Sharf) dengan alasan \'illat tunggal adalah...',
        opsi: ['Shighat Muntahal Jumu\'', 'Alamiyah dan Ta\'nits', 'Washfiyah dan Ziyadah Alif Nun', 'Alamiyah dan Tarkib Mazji'],
        kunciJawaban: 'Shighat Muntahal Jumu\'',
        bobot: 15,
      },
      {
        id: 'soal-3',
        nomor: 3,
        tipe: 'Pilihan Ganda',
        pertanyaan: 'Huruf jazm yang menjazamkan dua fi\'il mudhari\' (fi\'il syarat dan jawab syarat) adalah...',
        opsi: ['Lam (لَمْ)', 'Lamma (لَمَّا)', 'In (إِنْ)', 'Laa Nahiyah (لَا)'],
        kunciJawaban: 'In (إِنْ)',
        bobot: 15,
      },
      {
        id: 'soal-4',
        nomor: 4,
        tipe: 'Esai',
        pertanyaan: 'Jelaskan perbedaan mendasar antara Kalimah (الكَلِمَةُ) dan Kalam (الكَلَامُ) menurut pengarang Kitab Al-Jurumiyyah beserta contoh kalimat lengkapnya!',
        kunciJawaban: 'Kalam adalah lafadz yang tersusun yang memberi faedah sempurna secara sengaja berbahasa Arab (al-lafdhul murakkabul mufidu bil wadl\'i), contoh: قام زيد. Sedangkan kalimah adalah qaul mufrod (kata tunggal), baik berupa isim, fi\'il, atau huruf.',
        bobot: 25,
      },
      {
        id: 'soal-5',
        nomor: 5,
        tipe: 'Esai',
        pertanyaan: 'Tentukan kedudukan I\'rab dan tanda i\'rab dari kata yang bergaris bawah pada kalimat: (يَشْرَبُ السَّالِمُ المَاءَ النَّقِيَّ)!',
        kunciJawaban: 'يَشْرَبُ = Fi\'il Mudhari marfu\' dengan dhammah. السَّالِمُ = Fa\'il marfu\' dengan dhammah. المَاءَ = Maf\'ul bih manshub dengan fathah. النَّقِيَّ = Na\'at tabi\' lil man\'ut fi nashbihi.',
        bobot: 30,
      },
    ],
  },
  {
    id: 'pkt-2',
    judul: 'Penilaian Harian (PH) Fiqih Muamalah: Rukun Jual Beli Kelas 5A',
    mataPelajaran: 'Fiqih Muamalah',
    kelas: '5A',
    semester: 'Ganjil' as const,
    alokasiWaktuMenit: 60,
    guruPembuat: 'Ustadz Ahmad Fauzi, S.Pd.I',
    tanggalDibuat: '02 Sep 2026',
    tanggalMulai: '2026-09-01',
    jamMulai: '08:00',
    tanggalSelesai: '2026-12-31',
    jamSelesai: '23:59',
    totalSoal: 3,
    totalBobot: 100,
    status: 'Terpublikasi',
    isPublished: true,
    daftarSoal: [
      {
        id: 'soal-2-1',
        nomor: 1,
        tipe: 'Pilihan Ganda',
        pertanyaan: 'Rukun jual beli menurut jumhur ulama terdiri dari empat perkara, kecuali...',
        opsi: ['Aqidain (Penjual & Pembeli)', 'Ma\'qud \'Alaih (Barang & Harga)', 'Sighat Ijab Qabul', 'Tempat Transaksi Berpagar'],
        kunciJawaban: 'Tempat Transaksi Berpagar',
        bobot: 30,
      },
      {
        id: 'soal-2-2',
        nomor: 2,
        tipe: 'Esai',
        pertanyaan: 'Apakah hukum jual beli barang yang belum diterima atau belum berada di tangan penjual (Bai\' Ma Lam Yuqbadh)? Jelaskan dalil haditsnya!',
        kunciJawaban: 'Hukumnya tidak sah / terlarang berdasarkan hadits Nabi SAW: Man isytara tha\'aman falaa yabi\'hu hatta yastaufiyahu (Barangsiapa membeli makanan janganlah menjualnya sampai ia menerimanya secara utuh).',
        bobot: 35,
      },
      {
        id: 'soal-2-3',
        nomor: 3,
        tipe: 'Esai',
        pertanyaan: 'Sebutkan 3 macam Khiyar dalam transaksi jual beli dan jelaskan fungsinya dalam melindungi hak pembeli maupun penjual!',
        kunciJawaban: '1. Khiyar Majelis (selama belum berpisah tempat), 2. Khiyar Syarat (kesepakatan tenggat waktu tertentu), 3. Khiyar Aib (hak membatalkan jika ditemukan cacat tersembunyi pada barang).',
        bobot: 35,
      },
    ],
  },
];

export const MOCK_PENGUMUMAN = [
  {
    id: 'pgm-1',
    judul: 'Jadwal Penilaian Tengah Semester (PTS) Ganjil 1447 H / 2026 M',
    tanggal: '05 September 2026',
    kategori: 'Akademik',
    sasaran: 'Seluruh Santri & Dewan Asatidz',
    isi: 'Diberitahukan kepada seluruh santri Madrasah Diniyah Takmiliyah Annajiyah 2 bahwa pelaksanaan PTS Ganjil akan dimulai pada hari Sabtu, 19 September 2026. Santri diharapkan menyelesaikan seluruh administrasi hafalan dan mutaba\'ah sebelum tanggal tersebut.',
  },
  {
    id: 'pgm-2',
    judul: 'Maklumat Disiplin Waktu Masuk KBM Diniyah Pukul 20.00 WIB',
    tanggal: '02 September 2026',
    kategori: 'Tata Tertib',
    sasaran: 'Santri & Dewan Guru Pengajar',
    isi: 'Sesuai tata tertib madrasah, jam KBM Diniyah dimulai tepat pukul 20.00 WIB hingga 21.10 WIB. Seluruh santri dan dewan guru diharapkan hadir tepat waktu di ruang kelas masing-masing.',
  },
  {
    id: 'pgm-3',
    judul: 'Haflah Imtihan & Khotmil Muhafadzoh Nadhom Tingkat Akhir',
    tanggal: '28 Agustus 2026',
    kategori: 'Muhafadzoh',
    sasaran: 'Wali Santri & Santri Kelas 6',
    isi: 'Ujian komprehensif muhafadzoh nadhom dan imtihan tahriri bagi santri kelas 6 akan diselenggarakan menjelang penutupan semester.',
  },
];

