import React,{useMemo,useState}from'react';
import{CheckCircle2,Edit2,FileSpreadsheet,Printer,Save,Search,X}from'lucide-react';
import{MAPEL_RESMI_PER_KELAS}from'./madinData';
import{academicGradeService,AcademicGradeRecord,AcademicMapelScore}from'./academicGradeService';
import{storageService}from'./storageServiceProduction';
import{UserProfile}from'./types';

interface NilaiViewProps{userRole?:string;currentUser?:UserProfile}
const showScore=(n:number|null|undefined)=>typeof n==='number'&&n>0?n:'—';
const num=(v:string)=>v===''?null:Number(v);

export const NilaiView:React.FC<NilaiViewProps>=({userRole='Guru',currentUser})=>{
 const isSiswa=userRole.toLowerCase()==='siswa'; const canEdit=!isSiswa;
 const tahunAjaran=storageService.getTahunAjaran(); const activeSemester=storageService.getSemester(); const students=storageService.getStudents();
 const[semester,setSemester]=useState<'Ganjil'|'Genap'>(activeSemester); const[kelas,setKelas]=useState('Semua'); const[query,setQuery]=useState(''); const[editing,setEditing]=useState<AcademicGradeRecord|null>(null); const[toast,setToast]=useState(''); const[,refresh]=useState(0);
 const visible=useMemo(()=>{const own=(currentUser?.nipOrNis||'').replace(/\D/g,'');const base=isSiswa?students.filter(s=>(own&&s.nis.replace(/\D/g,'')===own)||s.nama.toLowerCase()===currentUser?.name.toLowerCase()):students;const q=query.trim().toLowerCase();return base.filter(s=>(kelas==='Semua'||s.kelas===kelas)&&(!q||s.nama.toLowerCase().includes(q)||s.nis.toLowerCase().includes(q)))},[students,isSiswa,currentUser,kelas,query]);
 const defaults=(kelasSantri:string):AcademicMapelScore[]=>{const tingkat=kelasSantri.replace(/\D/g,'')||'1';const cfg=MAPEL_RESMI_PER_KELAS[tingkat]||MAPEL_RESMI_PER_KELAS['1'];const list=semester==='Ganjil'?cfg.ganjil:cfg.genap;return list.map((m,i)=>({no:i+1,mapel:m.mapel,kitab:m.kitab,nilai:null}))};
 const rec=(nis:string,k:string)=>academicGradeService.get(nis,tahunAjaran,semester,defaults(k));
 const muhafMap=useMemo(()=>new Map(storageService.getMuhafadzohList().map(m=>[m.nis,m.nilaiUjianMuhafadzoh??m.nilaiMuhafadzoh??null])),[]);
 const avg=(r:AcademicGradeRecord)=>{const ns=r.mapelScores.map(x=>x.nilai).filter((n):n is number=>typeof n==='number'&&n>0);return ns.length?(ns.reduce((a,b)=>a+b,0)/ns.length).toFixed(2):'—'};
 const save=(e:React.FormEvent)=>{e.preventDefault();if(!editing)return;academicGradeService.save(editing);setEditing(null);refresh(n=>n+1);setToast('Nilai semester berhasil disimpan.');setTimeout(()=>setToast(''),2500)};
 const changeMapel=(i:number,v:string)=>setEditing(e=>e?{...e,mapelScores:e.mapelScores.map((x,j)=>j===i?{...x,nilai:num(v)}:x)}:e);
 return <div className="space-y-6 pb-12">
  {toast&&<div className="fixed bottom-6 right-6 z-50 flex items-center gap-2 rounded-xl bg-emerald-900 px-4 py-3 text-xs font-bold text-white"><CheckCircle2 className="h-4 w-4"/>{toast}</div>}
  <header className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-black"><FileSpreadsheet className="h-6 w-6 text-emerald-700"/>Buku Nilai Santri</h1><p className="mt-1 text-xs text-slate-500">Semua nilai berasal dari input guru/admin; tidak ada nilai otomatis atau acak.</p></div><button onClick={()=>window.print()} className="rounded-xl border bg-white px-4 py-2 text-xs font-bold"><Printer className="mr-1 inline h-4 w-4"/>Cetak Rekap</button></header>
  <section className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-3"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari nama / NIS" className="w-full rounded-xl border py-2.5 pl-9 pr-3 text-xs"/></div><select value={kelas} onChange={e=>setKelas(e.target.value)} className="rounded-xl border px-3 py-2.5 text-xs font-bold"><option>Semua</option>{['1A','1B','2A','2B','3A','3B','3C','4A','4B','5A','5B','6'].map(c=><option key={c}>{c}</option>)}</select><select value={semester} onChange={e=>setSemester(e.target.value as 'Ganjil'|'Genap')} className="rounded-xl border px-3 py-2.5 text-xs font-bold"><option value="Ganjil">Semester 1 (Ganjil)</option><option value="Genap">Semester 2 (Genap)</option></select></section>
  <div className="space-y-4">{visible.map(s=>{const r=rec(s.nis,s.kelas);return <section key={s.nis} className="rounded-2xl border bg-white p-5"><div className="mb-4 flex justify-between gap-3 border-b pb-3"><div><div className="font-black">{s.nama}</div><div className="text-xs text-slate-500">NIS {s.nis} · Kelas {s.kelas} · {tahunAjaran} · {semester}</div></div>{canEdit&&<button onClick={()=>setEditing(JSON.parse(JSON.stringify(r)))} className="rounded-xl bg-amber-50 px-3 py-2 text-xs font-bold text-amber-900"><Edit2 className="mr-1 inline h-4 w-4"/>Input / Edit Nilai</button>}</div><div className="overflow-x-auto"><table className="w-full border-collapse text-xs"><thead><tr className="bg-slate-100"><th className="border p-2">No</th><th className="border p-2 text-left">Mata Pelajaran</th><th className="border p-2 text-left">Kitab</th><th className="border p-2">Nilai</th></tr></thead><tbody>{r.mapelScores.map(m=><tr key={`${m.no}-${m.mapel}`}><td className="border p-2 text-center">{m.no}</td><td className="border p-2 font-semibold">{m.mapel}</td><td className="border p-2">{m.kitab}</td><td className="border p-2 text-center font-bold">{showScore(m.nilai)}</td></tr>)}<tr className="font-bold"><td colSpan={3} className="border p-2">Rata-rata Ujian Tulis</td><td className="border p-2 text-center">{avg(r)}</td></tr><tr className="font-bold"><td colSpan={3} className="border p-2">Nilai Muhafadloh</td><td className="border p-2 text-center">{showScore(muhafMap.get(s.nis))}</td></tr></tbody></table></div></section>})}{!visible.length&&<div className="rounded-2xl border bg-white p-8 text-center text-sm text-slate-500">Tidak ada data sesuai filter.</div>}</div>
  {editing&&<div className="fixed inset-0 z-50 bg-slate-950/60 p-4 overflow-y-auto"><form onSubmit={save} className="mx-auto my-5 max-w-3xl rounded-3xl bg-white p-6"><div className="flex justify-between"><div><h2 className="font-black">Input Nilai Semester</h2><p className="text-xs text-slate-500">Kosong berarti belum dinilai.</p></div><button type="button" onClick={()=>setEditing(null)}><X className="h-5 w-5"/></button></div>
    <div className="mt-5 space-y-2">{editing.mapelScores.map((m,i)=><label key={`${m.no}-${m.mapel}`} className="grid grid-cols-[1fr_110px] items-center gap-3 text-xs"><span><b>{m.mapel}</b> <span className="text-slate-500">{m.kitab}</span></span><input type="number" min="0" max="100" value={m.nilai??''} onChange={e=>changeMapel(i,e.target.value)} className="rounded-lg border px-3 py-2"/></label>)}</div>
    <div className="mt-5 grid gap-3 sm:grid-cols-3"><N label="Madrasatul Qur'an — Kelancaran (25)" max={25} value={editing.madrasatulQuran.kelancaran} set={v=>setEditing({...editing,madrasatulQuran:{...editing.madrasatulQuran,kelancaran:v}})}/><N label="Makhroj (25)" max={25} value={editing.madrasatulQuran.makhroj} set={v=>setEditing({...editing,madrasatulQuran:{...editing.madrasatulQuran,makhroj:v}})}/><N label="Tajwid (50)" max={50} value={editing.madrasatulQuran.tajwid} set={v=>setEditing({...editing,madrasatulQuran:{...editing.madrasatulQuran,tajwid:v}})}/><N label="Pengajian Sore" max={100} value={editing.pengajianSore} set={v=>setEditing({...editing,pengajianSore:v})}/><T label="Kelakuan" value={editing.akhlak} set={v=>setEditing({...editing,akhlak:v})}/><T label="Kerajinan" value={editing.kerajinan} set={v=>setEditing({...editing,kerajinan:v})}/><T label="Kerapian" value={editing.kerapian} set={v=>setEditing({...editing,kerapian:v})}/><N label="Peringkat" value={editing.ranking} set={v=>setEditing({...editing,ranking:v})}/><N label="Sakit" value={editing.absensi.sakit} set={v=>setEditing({...editing,absensi:{...editing.absensi,sakit:v}})}/><N label="Izin" value={editing.absensi.izin} set={v=>setEditing({...editing,absensi:{...editing.absensi,izin:v}})}/><N label="Tanpa keterangan" value={editing.absensi.alpha} set={v=>setEditing({...editing,absensi:{...editing.absensi,alpha:v}})}/></div>
    <T label="Wali Kelas / Musrif" value={editing.musrif} set={v=>setEditing({...editing,musrif:v})}/><label className="mt-3 block text-xs font-bold">Catatan<textarea rows={2} value={editing.catatan} onChange={e=>setEditing({...editing,catatan:e.target.value})} className="mt-1 w-full rounded-lg border p-2"/></label><label className="mt-3 block text-xs font-bold">Keputusan<textarea rows={2} value={editing.keputusan} onChange={e=>setEditing({...editing,keputusan:e.target.value})} className="mt-1 w-full rounded-lg border p-2"/></label><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setEditing(null)} className="rounded-xl border px-4 py-2 text-xs font-bold">Batal</button><button className="rounded-xl bg-emerald-800 px-4 py-2 text-xs font-bold text-white"><Save className="mr-1 inline h-4 w-4"/>Simpan Nilai</button></div>
  </form></div>}
 </div>;
};
const N=({label,value,set,max}:{label:string;value:number|null;set:(v:number|null)=>void;max?:number})=><label className="text-xs font-bold">{label}<input type="number" min="0" max={max} value={value??''} onChange={e=>set(num(e.target.value))} className="mt-1 w-full rounded-lg border px-3 py-2 font-normal"/></label>;
const T=({label,value,set}:{label:string;value:string;set:(v:string)=>void})=><label className="mt-3 block text-xs font-bold">{label}<input value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2 font-normal"/></label>;
