import React,{useMemo,useState}from'react';
import{CheckCircle2,FileSignature,KeyRound,Save,Settings,Trash2,UserPlus,Users,X}from'lucide-react';
import{AppUserAccount,UserProfile,UserRole}from'./types';
import{storageService}from'./storageServiceProduction';

interface Props{onSwitchRole:(role:UserRole)=>void;currentRole:UserRole;currentUser?:UserProfile}
export const PengaturanView:React.FC<Props>=({currentRole,currentUser})=>{
 const isAdmin=String(currentRole).toLowerCase()==='admin';
 const[accounts,setAccounts]=useState<AppUserAccount[]>(()=>storageService.getUserAccounts());const[showAdd,setShowAdd]=useState(false);const[toast,setToast]=useState('');
 const[name,setName]=useState('');const[username,setUsername]=useState('');const[kelas,setKelas]=useState('');const[nipNis,setNipNis]=useState('');
 const[newPassword,setNewPassword]=useState('');const[confirmPassword,setConfirmPassword]=useState('');const[newUsername,setNewUsername]=useState(()=>currentUser&&isAdmin?(accounts.find(a=>a.id===currentUser.id)?.username||''):'');
 const[signatures,setSignatures]=useState(()=>storageService.getSignaturesAndMusrif());
 const managedAccounts=useMemo(()=>accounts.filter(a=>a.role!=='siswa'),[accounts]);const studentCount=accounts.filter(a=>a.role==='siswa').length;
 const notify=(t:string)=>{setToast(t);setTimeout(()=>setToast(''),3000)};
 const refreshAccounts=()=>setAccounts(storageService.getUserAccounts());
 const addGuru=(e:React.FormEvent)=>{e.preventDefault();if(!name.trim()||!username.trim()){notify('Nama dan username guru wajib diisi.');return}if(accounts.some(a=>a.username.toLowerCase()===username.trim().toLowerCase())){notify('Username sudah digunakan.');return}const acc:AppUserAccount={id:`usr-guru-${Date.now()}`,name:name.trim(),username:username.trim(),password:['1','2','3','4'].join(''),role:'guru',roleTitle:'Guru / Pengajar',nipOrNis:nipNis.trim()||username.trim(),kelas:kelas.trim()||undefined,status:'Aktif',permissions:['kbm','absensi','nilai','muhafadzoh']};storageService.addUserAccount(acc);refreshAccounts();setShowAdd(false);setName('');setUsername('');setKelas('');setNipNis('');notify('Akun guru dibuat dengan kata sandi awal 1234.')};
 const toggle=(a:AppUserAccount)=>{if(a.role==='admin'){notify('Akun administrator utama tidak dapat dinonaktifkan.');return}storageService.updateUserAccount(a.id,{status:a.status==='Aktif'?'Nonaktif':'Aktif'});refreshAccounts()};
 const remove=(a:AppUserAccount)=>{if(a.role!=='guru')return;if(!window.confirm(`Hapus akun guru ${a.name}?`))return;storageService.deleteUserAccount(a.id);refreshAccounts();notify('Akun guru dihapus.')};
 const changeOwnPassword=(e:React.FormEvent)=>{e.preventDefault();if(!currentUser||newPassword.length<4){notify('Kata sandi baru minimal 4 karakter.');return}if(newPassword!==confirmPassword){notify('Konfirmasi kata sandi tidak cocok.');return}if(!storageService.changeUserPassword(currentUser.id,newPassword)){notify('Akun aktif tidak ditemukan.');return}setNewPassword('');setConfirmPassword('');notify('Kata sandi berhasil diubah.')};
 const changeOwnUsername=(e:React.FormEvent)=>{e.preventDefault();if(!isAdmin||!currentUser)return;if(!storageService.changeAdminUsername(currentUser.id,newUsername)){notify('Username tidak valid atau sudah digunakan.');return}const updated=storageService.getUserAccounts().find(a=>a.id===currentUser.id);if(updated)try{sessionStorage.setItem('annajiyah_active_account',JSON.stringify(updated))}catch{}refreshAccounts();notify('Username administrator berhasil diubah.')};
 const saveDocs=(e:React.FormEvent)=>{e.preventDefault();storageService.saveSignaturesAndMusrif(signatures);notify('Identitas dokumen dan tanda tangan berhasil disimpan.')};
 return <div className="space-y-6 pb-12">{toast&&<div className="fixed bottom-6 right-6 z-50 flex items-center gap-2 rounded-xl bg-emerald-900 px-4 py-3 text-xs font-bold text-white"><CheckCircle2 className="h-4 w-4"/>{toast}</div>}<header><h1 className="flex items-center gap-2 text-2xl font-black"><Settings className="h-6 w-6 text-emerald-700"/>Pengaturan Sistem</h1><p className="mt-1 text-xs text-slate-500">Username santri dikunci ke NIS. Username guru ditetapkan admin saat akun dibuat.</p></header>
 <section className="rounded-2xl border bg-white p-5"><div className="mb-4 flex items-center gap-2"><KeyRound className="h-5 w-5 text-emerald-700"/><h2 className="font-black">Keamanan Akun Saya</h2></div>{isAdmin&&<form onSubmit={changeOwnUsername} className="mb-4 flex flex-col gap-3 sm:flex-row"><input value={newUsername} onChange={e=>setNewUsername(e.target.value)} placeholder="Username administrator" className="flex-1 rounded-xl border px-3 py-2.5 text-sm"/><button className="rounded-xl border border-emerald-700 px-4 py-2 text-xs font-bold text-emerald-800">Ubah Username Admin</button></form>}<form onSubmit={changeOwnPassword} className="grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="Kata sandi baru (min. 4)" className="rounded-xl border px-3 py-2.5 text-sm"/><input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} placeholder="Konfirmasi kata sandi" className="rounded-xl border px-3 py-2.5 text-sm"/><button className="rounded-xl bg-emerald-800 px-4 py-2 text-xs font-bold text-white"><Save className="mr-1 inline h-4 w-4"/>Simpan Password</button></form>{!isAdmin&&<p className="mt-3 text-[11px] text-slate-500">Username akun Anda tidak dapat diubah. Guru menggunakan username yang dibuat admin; santri menggunakan NIS.</p>}</section>
 {isAdmin&&<section className="rounded-2xl border bg-white p-5"><div className="mb-4 flex items-center gap-2"><FileSignature className="h-5 w-5 text-emerald-700"/><div><h2 className="font-black">Identitas Raport & Ijazah</h2><p className="mt-1 text-xs text-slate-500">Isi sesuai keputusan dan dokumen resmi madrasah.</p></div></div><form onSubmit={saveDocs} className="grid gap-3 sm:grid-cols-2"><Field label="Nama Pengasuh" value={signatures.namaPengasuh||''} set={v=>setSignatures({...signatures,namaPengasuh:v})}/><Field label="Jabatan Pengasuh" value={signatures.jabatanPengasuh||''} set={v=>setSignatures({...signatures,jabatanPengasuh:v})}/><Field label="Nama Kepala Madrasah" value={signatures.namaKepalaMadrasah||''} set={v=>setSignatures({...signatures,namaKepalaMadrasah:v})}/><Field label="Titimangsa Raport" value={signatures.titimangsaRaport||''} set={v=>setSignatures({...signatures,titimangsaRaport:v})}/><Field label="Tanggal Hijriah Raport (opsional)" value={signatures.tanggalHijriahRaport||''} set={v=>setSignatures({...signatures,tanggalHijriahRaport:v})}/><Field label="Titimangsa Ijazah" value={signatures.titimangsaIjazah||''} set={v=>setSignatures({...signatures,titimangsaIjazah:v})}/><Field label="Tanggal Hijriah Ijazah (opsional)" value={signatures.tanggalHijriahIjazah||''} set={v=>setSignatures({...signatures,tanggalHijriahIjazah:v})}/><Field label="Template Nomor Ijazah (gunakan {NIS} bila perlu)" value={signatures.nomorIjazahTemplate||''} set={v=>setSignatures({...signatures,nomorIjazahTemplate:v})}/><div className="sm:col-span-2"><button className="rounded-xl bg-emerald-800 px-4 py-2.5 text-xs font-bold text-white"><Save className="mr-1 inline h-4 w-4"/>Simpan Identitas Dokumen</button></div></form></section>}
 {isAdmin&&<section className="rounded-2xl border bg-white p-5"><div className="mb-4 flex items-center justify-between gap-3"><div className="flex items-center gap-2"><Users className="h-5 w-5 text-emerald-700"/><div><h2 className="font-black">Akun Admin & Guru</h2><p className="text-xs text-slate-500">{studentCount} akun santri dibuat otomatis dari NIS master. Kata sandi awal guru adalah 1234.</p></div></div><button onClick={()=>setShowAdd(true)} className="rounded-xl bg-emerald-800 px-4 py-2 text-xs font-bold text-white"><UserPlus className="mr-1 inline h-4 w-4"/>Tambah Guru</button></div><div className="overflow-x-auto"><table className="w-full border-collapse text-xs"><thead><tr className="bg-slate-100"><th className="border p-2 text-left">Nama</th><th className="border p-2">Username</th><th className="border p-2">Role</th><th className="border p-2">NIP</th><th className="border p-2">Kelas</th><th className="border p-2">Status</th><th className="border p-2">Aksi</th></tr></thead><tbody>{managedAccounts.map(a=><tr key={a.id}><td className="border p-2 font-bold">{a.name}</td><td className="border p-2 text-center font-mono">{a.username}</td><td className="border p-2 text-center uppercase">{a.role}</td><td className="border p-2 text-center">{a.nipOrNis}</td><td className="border p-2 text-center">{a.kelas||'—'}</td><td className="border p-2 text-center"><button onClick={()=>toggle(a)} className="rounded-full bg-slate-100 px-2 py-1 font-bold">{a.status}</button></td><td className="border p-2 text-center">{a.role==='guru'?<button onClick={()=>remove(a)} className="rounded-lg bg-rose-50 p-2 text-rose-700"><Trash2 className="h-4 w-4"/></button>:'—'}</td></tr>)}</tbody></table></div></section>}
 {!isAdmin&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-xs text-emerald-900">Pengelolaan akun guru dan identitas dokumen hanya tersedia untuk administrator.</div>}
 {isAdmin&&showAdd&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 p-4"><form onSubmit={addGuru} className="w-full max-w-xl rounded-3xl bg-white p-6"><div className="flex justify-between"><div><h2 className="font-black">Tambah Akun Guru</h2><p className="mt-1 text-xs text-slate-500">Username ditetapkan sekali oleh admin. Password awal otomatis 1234 dan dapat diubah sendiri oleh guru.</p></div><button type="button" onClick={()=>setShowAdd(false)}><X className="h-5 w-5"/></button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Nama Guru" value={name} set={setName}/><Field label="Username Guru" value={username} set={setUsername}/><Field label="NIP / Identitas (opsional)" value={nipNis} set={setNipNis}/><Field label="Kelas (opsional)" value={kelas} set={setKelas}/></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setShowAdd(false)} className="px-4 py-2 text-xs font-bold">Batal</button><button className="rounded-xl bg-emerald-800 px-4 py-2 text-xs font-bold text-white">Buat Akun Guru</button></div></form></div>}
 </div>;
};
const Field=({label,value,set}:{label:string;value:string;set:(v:string)=>void})=><label className="text-xs font-bold">{label}<input value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2 font-normal"/></label>;
