import React, { useState } from 'react';
import { BookOpen, Plus, Trash2 } from 'lucide-react';
type Item={id:string;kelas:string;semester:'Ganjil'|'Genap';mapel:string;kitab:string;materi:string;kompetensi:string;indikator:string;target:string;metode:string};
const KEY='annajiyah_v2_silabus_production';
const load=():Item[]=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
export const SilabusView:React.FC<{userRole?:string}>=({userRole='Guru'})=>{
 const isAdmin=userRole.toLowerCase()==='admin'; const [items,setItems]=useState<Item[]>(load); const [show,setShow]=useState(false);
 const [f,setF]=useState<Omit<Item,'id'>>({kelas:'1A',semester:'Ganjil',mapel:'',kitab:'',materi:'',kompetensi:'',indikator:'',target:'',metode:''});
 const save=(e:React.FormEvent)=>{e.preventDefault();if(!f.mapel.trim()||!f.kitab.trim()||!f.materi.trim())return;const n=[...items,{...f,id:`silabus-${Date.now()}`}];setItems(n);localStorage.setItem(KEY,JSON.stringify(n));setShow(false);setF({...f,mapel:'',kitab:'',materi:'',kompetensi:'',indikator:'',target:'',metode:''})};
 const del=(id:string)=>{const n=items.filter(x=>x.id!==id);setItems(n);localStorage.setItem(KEY,JSON.stringify(n))};
 return <div className="space-y-5 pb-12"><div className="flex items-end justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-black"><BookOpen className="h-6 w-6 text-emerald-700"/>Silabus</h1><p className="mt-1 text-xs text-slate-500">Tidak ada kompetensi, indikator, target, atau metode yang dibuat otomatis. Isian hanya berdasarkan keputusan kurikulum madrasah.</p></div>{isAdmin&&<button onClick={()=>setShow(true)} className="rounded-xl bg-emerald-800 px-4 py-2 text-xs font-bold text-white"><Plus className="mr-1 inline h-4 w-4"/>Tambah Silabus</button>}</div>{items.length===0?<div className="rounded-2xl border border-dashed bg-white p-10 text-center text-sm text-slate-500">Belum ada silabus yang dimasukkan.</div>:<div className="space-y-3">{items.map(x=><div key={x.id} className="rounded-2xl border bg-white p-4"><div className="flex justify-between gap-4"><div><div className="text-sm font-black">{x.mapel} · {x.kelas} · {x.semester}</div><div className="mt-1 text-xs text-slate-500">Kitab: {x.kitab}</div><p className="mt-2 text-xs">Materi: {x.materi}</p>{x.kompetensi&&<p className="mt-1 text-xs">Kompetensi: {x.kompetensi}</p>}{x.indikator&&<p className="mt-1 text-xs">Indikator: {x.indikator}</p>}{x.target&&<p className="mt-1 text-xs">Target: {x.target}</p>}{x.metode&&<p className="mt-1 text-xs">Metode: {x.metode}</p>}</div>{isAdmin&&<button onClick={()=>del(x.id)} className="text-rose-700"><Trash2 className="h-4 w-4"/></button>}</div></div>)}</div>}{show&&<div className="fixed inset-0 z-50 bg-slate-950/60 p-4"><div className="mx-auto mt-8 max-w-xl rounded-3xl bg-white p-6"><h3 className="font-black">Tambah Silabus</h3><form onSubmit={save} className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Kelas" value={f.kelas} set={v=>setF({...f,kelas:v})}/><label className="text-xs font-bold">Semester<select value={f.semester} onChange={e=>setF({...f,semester:e.target.value as 'Ganjil'|'Genap'})} className="mt-1 w-full rounded-xl border p-2.5 font-normal"><option>Ganjil</option><option>Genap</option></select></label><Field label="Mata Pelajaran" value={f.mapel} set={v=>setF({...f,mapel:v})}/><Field label="Kitab" value={f.kitab} set={v=>setF({...f,kitab:v})}/><Field label="Materi" value={f.materi} set={v=>setF({...f,materi:v})}/><Field label="Kompetensi" value={f.kompetensi} set={v=>setF({...f,kompetensi:v})}/><Field label="Indikator" value={f.indikator} set={v=>setF({...f,indikator:v})}/><Field label="Target" value={f.target} set={v=>setF({...f,target:v})}/><div className="sm:col-span-2"><Field label="Metode" value={f.metode} set={v=>setF({...f,metode:v})}/></div><div className="sm:col-span-2 flex justify-end gap-2"><button type="button" onClick={()=>setShow(false)} className="px-4 py-2 text-xs font-bold">Batal</button><button className="rounded-xl bg-emerald-800 px-4 py-2 text-xs font-bold text-white">Simpan</button></div></form></div></div>}</div>
};
const Field=({label,value,set}:{label:string;value:string;set:(v:string)=>void})=><label className="text-xs font-bold">{label}<input value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded-xl border p-2.5 font-normal"/></label>;
