import { AppUserAccount, Santri, SiswaMuhafadzoh, SesiAbsensi, HariLiburItem, KritikSaranItem, GuruJadwal, JadwalSlotItem, NilaiSiswaItem, KalenderPendidikanItem } from './types';
import { DATA_SISWA_247 } from './students247Data';
import { storageService as legacyStorageService, SignaturesConfig } from './storageService';

export type { SignaturesConfig } from './storageService';

const PROD_ACCOUNTS_KEY='annajiyah_prod_accounts_v1';
const ACCOUNT_POLICY_KEY='annajiyah_prod_account_policy_v2';
const DEFAULT_ADMIN_USERNAME='faza22';
const DEFAULT_ADMIN_PASSWORD=['6','4','2','4'].join('');
const DEFAULT_GURU_PASSWORD=['1','2','3','4'].join('');
const PREFIX='annajiyah_v2_';
const KEYS={tahun:`${PREFIX}tahun_ajaran`,semester:`${PREFIX}semester`,daftarTahun:`${PREFIX}daftar_tahun`,muhaf:`${PREFIX}muhafadzoh_list`,absensi:`${PREFIX}absensi_session`,libur:`${PREFIX}daftar_libur`,kritik:`${PREFIX}kritik_saran_list`,signatures:`${PREFIX}signatures_musrif`,settings:`${PREFIX}settings`,guruProd:`${PREFIX}teachers_prod`,jadwalProd:`${PREFIX}schedule_prod`,silabusProd:`${PREFIX}silabus_production`,kalenderProd:`${PREFIX}kalender_production`,peraturanProd:`${PREFIX}peraturan_guru_production`};
const readJson=<T,>(key:string,fallback:T):T=>{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw) as T:fallback}catch{return fallback}};const writeJson=(key:string,value:unknown)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}};

const buildStudentAccounts=(existing:AppUserAccount[]):AppUserAccount[]=>DATA_SISWA_247.map(s=>{const old=existing.find(a=>a.role==='siswa'&&a.nipOrNis.replace(/\D/g,'')===s.nis.replace(/\D/g,''));return{id:old?.id||`usr-siswa-${s.nis}`,username:s.nis,password:old?.password||s.nis,name:s.nama,role:'siswa',roleTitle:`Santri Kelas ${s.kelas}`,nipOrNis:s.nis,kelas:s.kelas,status:s.status==='Aktif'?'Aktif':'Nonaktif',permissions:['santri_portal']}});
const syncAccounts=():AppUserAccount[]=>{
 const stored=readJson<AppUserAccount[]>(PROD_ACCOUNTS_KEY,[]);let working=stored;
 try{if(localStorage.getItem(ACCOUNT_POLICY_KEY)!=='applied'){const nonAdmins=stored.filter(a=>a.role!=='admin');const primary:AppUserAccount={id:'admin-utama',username:DEFAULT_ADMIN_USERNAME,password:DEFAULT_ADMIN_PASSWORD,name:'Administrator Madrasah',role:'admin',roleTitle:'Administrator Madrasah',nipOrNis:'ADMIN',status:'Aktif',permissions:['admin_full']};working=[primary,...nonAdmins];localStorage.setItem(ACCOUNT_POLICY_KEY,'applied')}}catch{}
 const admin=working.find(a=>a.role==='admin')||{id:'admin-utama',username:DEFAULT_ADMIN_USERNAME,password:DEFAULT_ADMIN_PASSWORD,name:'Administrator Madrasah',role:'admin' as const,roleTitle:'Administrator Madrasah',nipOrNis:'ADMIN',status:'Aktif' as const,permissions:['admin_full']};
 const gurus=working.filter(a=>a.role==='guru').map(a=>({...a,role:'guru' as const,password:a.password||DEFAULT_GURU_PASSWORD}));
 const students=buildStudentAccounts(working);const next=[admin,...gurus,...students];writeJson(PROD_ACCOUNTS_KEY,next);return next;
};
const readAccounts=():AppUserAccount[]=>syncAccounts();const writeAccounts=(a:AppUserAccount[])=>writeJson(PROD_ACCOUNTS_KEY,a);

const sanitizeExtra=(s?:Santri|null):Partial<Santri>=>{if(!s)return{};const fakeNisn=s.nisn===`00${s.nis}88`;const fakeBirthPlace=s.tempatLahir==='Jombang';const fakeBirthDate=s.tanggalLahir==='10 Muharram 1430 H';const fakeGuardian=s.waliSantri===`Wali dari ${s.nama}`||s.namaWali===`Wali dari ${s.nama}`;const fakePhone=s.noHpWali==='0812-3456-7890';const fakeAddress=s.alamat==='Tambakberas, Jombang';const fakePhoto=Boolean(s.foto&&s.foto.includes('images.unsplash.com'));const fakeAcademicNote=Boolean(s.catatanWaliKelas&&(s.catatanWaliKelas.includes('Santri berakhlakul karimah')||s.catatanWaliKelas.includes('Calon wisudawan teladan')));return{nisn:fakeNisn?'':s.nisn,tempatLahir:fakeBirthPlace?'':s.tempatLahir,tanggalLahir:fakeBirthDate?'':s.tanggalLahir,namaWali:fakeGuardian?'':s.namaWali,waliSantri:fakeGuardian?'':s.waliSantri,noHpWali:fakePhone?'':s.noHpWali,alamat:fakeAddress?'':s.alamat,foto:fakePhoto?'':s.foto,kamarAsrama:s.kamarAsrama,tahunMasuk:s.tahunMasuk,prestasi:s.prestasi,pelanggaran:s.pelanggaran,waliKelas:s.waliKelas,catatanWaliKelas:fakeAcademicNote?'':s.catatanWaliKelas,hafalanJuz:undefined,mutqinSurah:undefined,kehadiranPercent:s.kehadiranPercent===96.5?undefined:s.kehadiranPercent,rataRataNilai:s.rataRataNilai===88.5?undefined:s.rataRataNilai,akhlakPredikat:s.akhlakPredikat==='Jayyid Jiddan'?undefined:s.akhlakPredikat};};
const officialBase=():Santri[]=>{let persisted:Santri[]=[];try{persisted=legacyStorageService.getSantriList()}catch{}const byNis=new Map(persisted.map(s=>[s.nis,s]));const officialNis=new Set(DATA_SISWA_247.map(s=>s.nis));const official=DATA_SISWA_247.map(src=>{const extra=sanitizeExtra(byNis.get(src.nis));return{...extra,id:`santri-${src.nis}`,nis:src.nis,nisn:extra.nisn||'',nama:src.nama,gender:src.jk,jenisKelamin:src.jk,kelas:src.kelas,status:src.status as any,tempatLahir:extra.tempatLahir||'',tanggalLahir:extra.tanggalLahir||'',namaWali:extra.namaWali||'',waliSantri:extra.waliSantri||'',noHpWali:extra.noHpWali||'',alamat:extra.alamat||'',foto:extra.foto||''}as Santri});const custom=persisted.filter(s=>!officialNis.has(s.nis)).map(s=>({...s,...sanitizeExtra(s),hafalanJuz:undefined,mutqinSurah:undefined}));return[...official,...custom]};
const emptyAbsensi=():SesiAbsensi=>({id:'',tanggal:'',kelas:'',mataPelajaran:'',jamKe:'',ruang:'',guruPengampu:'',isCompleted:false,records:[]});
const emptySignatures=():SignaturesConfig=>({namaPengasuh:'',jabatanPengasuh:'',namaKepalaMadrasah:'',titimangsaRaport:'',tanggalHijriahRaport:'',titimangsaIjazah:'',tanggalHijriahIjazah:'',nomorIjazahTemplate:'',catatanRaportDefault:'',keputusanLulusDefault:'',musrifPerKelas:{},signatureImageUrl:''});
const readMuhaf=():SiswaMuhafadzoh[]=>{const persisted=readJson<SiswaMuhafadzoh[]>(KEYS.muhaf,[]);const byNis=new Map(persisted.map(x=>[x.nis,x]));return DATA_SISWA_247.map(src=>{const p=byNis.get(src.nis);if(!p)return{...src};return{...src,capaian1:p.capaian1??null,capaian2:p.capaian2??null,capaian3:p.capaian3??null,capaian4:p.capaian4??null,capaian5:p.capaian5??null,capaian6:p.capaian6??null,capaian7:p.capaian7??null,capaian8:p.capaian8??null,ujianTulisS1:p.ujianTulisS1??null,ujianTulisS2:p.ujianTulisS2??null,ujianLisanS1:p.ujianLisanS1??null,ujianLisanS2:p.ujianLisanS2??null,kehadiran:p.kehadiran??null,catatan:p.catatan||'',nilaiUjianMuhafadzoh:(p.nilaiUjianMuhafadzoh===88&&!['capaian1','capaian2','capaian3','capaian4','capaian5','capaian6','capaian7','capaian8'].some(k=>Number((p as any)[k])>0))?undefined:p.nilaiUjianMuhafadzoh,nilaiMuhafadzoh:p.nilaiMuhafadzoh===88?undefined:p.nilaiMuhafadzoh}})};

export const storageService={
 ...legacyStorageService,
 getTahunAjaran():string{return readJson(KEYS.tahun,'2026/2027')},saveTahunAjaran(v:string):void{writeJson(KEYS.tahun,v)},getSemester():'Ganjil'|'Genap'{return readJson(KEYS.semester,'Ganjil')},saveSemester(v:'Ganjil'|'Genap'):void{writeJson(KEYS.semester,v)},getDaftarTahunAjaran():string[]{return readJson(KEYS.daftarTahun,['2026/2027'])},saveDaftarTahunAjaran(v:string[]):void{writeJson(KEYS.daftarTahun,v)},
 getSantriList():Santri[]{return officialBase()},getStudents():Santri[]{return this.getSantriList()},saveSantriList(v:Santri[]):void{legacyStorageService.saveSantriList(v)},saveStudents(v:Santri[]):void{this.saveSantriList(v)},addSantri(v:Santri):void{this.saveSantriList([v,...this.getSantriList()])},updateSantri(id:string,u:Partial<Santri>):void{legacyStorageService.saveSantriList(this.getSantriList().map(s=>s.id===id?{...s,...u}:s))},deleteSantri(id:string):void{legacyStorageService.saveSantriList(this.getSantriList().filter(s=>s.id!==id))},
 getMuhafadzohList():SiswaMuhafadzoh[]{return readMuhaf()},saveMuhafadzohList(v:SiswaMuhafadzoh[]):void{writeJson(KEYS.muhaf,v)},updateSingleSiswaMuhafadzoh(u:SiswaMuhafadzoh):SiswaMuhafadzoh[]{const n=readMuhaf().map(s=>s.nis===u.nis?u:s);writeJson(KEYS.muhaf,n);return n},
 getAbsensiSession():SesiAbsensi{return readJson(KEYS.absensi,emptyAbsensi())},saveAbsensiSession(v:SesiAbsensi):void{writeJson(KEYS.absensi,v)},
 getGuruList():GuruJadwal[]{return readJson(KEYS.guruProd,[])},saveGuruList(v:GuruJadwal[]):void{writeJson(KEYS.guruProd,v)},getJadwalSlots():JadwalSlotItem[]{return readJson(KEYS.jadwalProd,[])},saveJadwalSlots(v:JadwalSlotItem[]):void{writeJson(KEYS.jadwalProd,v)},getNilaiList():NilaiSiswaItem[]{return[]},saveNilaiList(_v:NilaiSiswaItem[]):void{},
 getDaftarLibur():HariLiburItem[]{return readJson(KEYS.libur,[])},getHariLibur():HariLiburItem[]{return this.getDaftarLibur()},saveDaftarLibur(v:HariLiburItem[]):void{writeJson(KEYS.libur,v)},addHariLibur(item:Omit<HariLiburItem,'id'|'dibuatPada'>):HariLiburItem[]{const n=[{...item,id:`libur-${Date.now()}`,dibuatPada:new Date().toISOString().slice(0,10)},...this.getDaftarLibur()];this.saveDaftarLibur(n);return n},deleteHariLibur(id:string):HariLiburItem[]{const n=this.getDaftarLibur().filter(x=>x.id!==id);this.saveDaftarLibur(n);return n},isTanggalLibur(d:string):{isLibur:boolean;keterangan?:string}{const h=this.getDaftarLibur().find(x=>d>=x.tanggalMulai&&d<=x.tanggalSelesai);return h?{isLibur:true,keterangan:h.keterangan}:{isLibur:false}},
 getKritikSaran():KritikSaranItem[]{return readJson(KEYS.kritik,[])},saveKritikSaran(v:KritikSaranItem[]):void{writeJson(KEYS.kritik,v)},getKalenderPendidikan():KalenderPendidikanItem[]{return[]},saveKalenderPendidikan(_v:KalenderPendidikanItem[]):void{},getPeraturanGuru():string{return localStorage.getItem(KEYS.peraturanProd)||''},savePeraturanGuru(v:string):void{localStorage.setItem(KEYS.peraturanProd,v)},getSilabusList():any[]{return readJson(KEYS.silabusProd,[])},
 getSignaturesAndMusrif():SignaturesConfig{return readJson(KEYS.signatures,emptySignatures())},saveSignaturesAndMusrif(v:SignaturesConfig):void{writeJson(KEYS.signatures,v)},getAppSettings():{namaPesantren:string;nspp:string;alamat:string}{return readJson(KEYS.settings,{namaPesantren:'Madrasah Diniyyah Takmiliyyah An-Najiyah 2',nspp:'',alamat:''})},saveAppSettings(v:{namaPesantren:string;nspp:string;alamat:string}):void{writeJson(KEYS.settings,v)},
 getUserAccounts():AppUserAccount[]{return readAccounts()},saveUserAccounts(v:AppUserAccount[]):void{writeAccounts(v)},addUserAccount(v:AppUserAccount):void{if(v.role==='guru')writeAccounts([v,...readAccounts()])},updateUserAccount(id:string,u:Partial<AppUserAccount>):void{writeAccounts(readAccounts().map(a=>a.id===id?{...a,...u,username:a.role==='siswa'?a.nipOrNis:a.username}:a))},deleteUserAccount(id:string):void{writeAccounts(readAccounts().filter(a=>a.id!==id||a.role==='admin'||a.role==='siswa'))},
 changeUserPassword(idOrUsername:string,newPass:string):boolean{if(newPass.length<4)return false;let changed=false;const k=idOrUsername.trim().toLowerCase();const n=readAccounts().map(a=>{if(a.id.toLowerCase()===k||a.username.toLowerCase()===k||a.nipOrNis.replace(/\W/g,'').toLowerCase()===k.replace(/\W/g,'')){changed=true;return{...a,password:newPass}}return a});if(changed)writeAccounts(n);return changed},
 changeAdminUsername(id:string,newUsername:string):boolean{const clean=newUsername.trim();if(!clean)return false;const accounts=readAccounts();const target=accounts.find(a=>a.id===id&&a.role==='admin');if(!target||accounts.some(a=>a.id!==id&&a.username.toLowerCase()===clean.toLowerCase()))return false;writeAccounts(accounts.map(a=>a.id===id?{...a,username:clean}:a));return true},
 verifyLogin(username:string,pass:string):AppUserAccount|null{const u=username.trim().toLowerCase();return readAccounts().find(a=>a.status==='Aktif'&&a.password===pass&&a.username.toLowerCase()===u)||null}
};
